import {
  QuantitativeReasoningQuestion,
  QRQuestionData,
  generateMCAnswers,
} from "../types";

// GMAT Practice Questions (Official) - Quantitative Reasoning
// Source: GMAT Practice QR (Not Started)
// Questions 1-82: Difficulty Easy
// Questions 83-132: Difficulty Medium
// Questions 133-207: Difficulty Hard

export const quantitativeReasoningQuestionsPQ: QuantitativeReasoningQuestion[] = [
  // ============================================
  // QUESTIONS 83-132: MEDIUM DIFFICULTY
  // ============================================
  {
    id: "QR-GMAT-PQ_-00083",
    question_number: 83,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "If $\\frac{1}{2}$ the result obtained when 2 is subtracted from $5x$ is equal to the sum of 10 and $3x$, what is the value of $x$?",
      options: {
        a: "$-22$",
        b: "$-4$",
        c: "$4$",
        d: "$18$",
        e: "$22$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("a"),
    explanation: "The result obtained when 2 is subtracted from $5x$ is $5x - 2$, and the sum of 10 and $3x$ is $10 + 3x$.\n\nTherefore, it is given that $\\frac{1}{2}$ of $5x - 2$ is equal to $10 + 3x$, or $\\frac{1}{2}(5x - 2) = 10 + 3x$.\n\n$\\frac{1}{2}(5x - 2) = 10 + 3x$ given\n\n$5x - 2 = 20 + 6x$ multiply both sides by 2\n\n$-22 = x$ subtract both $5x$ and 20 from both sides",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00084",
    question_number: 84,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "If Car A took $n$ hours to travel 2 miles and Car B took $m$ hours to travel 3 miles, which of the following expresses the time it would take Car C, traveling at the average (arithmetic mean) of those rates, to travel 5 miles?",
      options: {
        a: "$\\frac{10nm}{3n + 2m}$",
        b: "$\\frac{3n + 2m}{10(n + m)}$",
        c: "$\\frac{2n + 3m}{5nm}$",
        d: "$\\frac{10(n + m)}{2n + 3m}$",
        e: "$\\frac{5(n + m)}{2n + 3m}$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("a"),
    explanation: "This is a rate problem that can be solved by several applications of the formula\n\nrate $\\times$ time $=$ distance.\n\nLet $r_A$ and $r_B$ be the rates, respectively and in miles per hour, of Car A and Car B. Then omitting units for simplicity, for Car A this formula becomes $r_A \\times n = 2$, or $r_A = \\frac{2}{n}$, and for Car B this formula becomes $r_B \\times m = 3$, or $r_B = \\frac{3}{m}$. Thus, the average of the two rates is\n\n$\\frac{1}{2}(r_A + r_B) = \\frac{1}{2}(\\frac{2}{n} + \\frac{3}{m}) = \\frac{1}{2}(\\frac{2m + 3n}{mn}) = \\frac{3n + 2m}{2mn}$. Therefore, if $t$ is the desired time, in\n\nhours, that Car C traveled, then the above formula for Car C becomes $\\frac{3n + 2m}{2mn} \\times t = 5$, or\n\n$t = 5 \\times \\frac{2mn}{3n + 2m} = \\frac{10mn}{3n + 2m}$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00085",
    question_number: 85,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "If $x$, $y$, and $k$ are positive and $x$ is less than $y$, then $\\frac{x + k}{y + k}$ is",
      options: {
        a: "$1$",
        b: "greater than $\\frac{x}{y}$",
        c: "equal to $\\frac{x}{y}$",
        d: "less than $\\frac{x}{y}$",
        e: "less than $\\frac{x}{y}$ or greater than $\\frac{x}{y}$ depending on the value of $k$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "$x < y$ given\n\n$kx < ky$ multiply by positive $k$\n\n$xy + kx < xy + ky$ add $xy$\n\n$x(y + k) < y(x + k)$ factor\n\n$x < \\frac{y(x+k)}{y+k}$ divide by positive $y + k$\n\n$\\frac{x}{y} < \\frac{x+k}{y+k}$ divide by positive $y$\n\nThus, $\\frac{x+k}{y+k} > \\frac{x}{y}$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00086",
    question_number: 86,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Consider the following set of inequalities: $p > q$, $s > r$, $q > t$, $s > p$, and $r > q$. Between which two quantities is no relationship established?",
      options: {
        a: "$p$ and $r$",
        b: "$s$ and $t$",
        c: "$s$ and $q$",
        d: "$p$ and $t$",
        e: "$r$ and $t$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("a"),
    explanation: "Using $r > q$ and $q > t$ gives $r > t$, so a relationship is established between $r$ and $t$. The correct answer is NOT E.\n\nUsing $p > q$ and $q > t$ gives $p > t$, so a relationship is established between $p$ and $t$. The correct answer is NOT D.\n\nUsing $s > r$ and $r > q$ gives $s > q$, so a relationship is established between $s$ and $q$. The correct answer is NOT C.\n\nUsing $s > r$, $r > q$, and $q > t$ gives $s > t$, so a relationship is established between $s$ and $t$. The correct answer is NOT B.\n\nAlternately, the diagram below shows the given relationships and does not establish a relationship between $p$ and $r$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00087",
    question_number: 87,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Carl averaged $2m$ miles per hour on a trip that took him $h$ hours. If Ruth made the same trip in $\\frac{2}{3}h$ hours, what was her average speed in miles per hour?",
      options: {
        a: "$\\frac{1}{3}mh$",
        b: "$\\frac{2}{3}mh$",
        c: "$m$",
        d: "$\\frac{3}{2}m$",
        e: "$3m$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "Using distance $=$ rate $\\times$ time, the distance Carl traveled on the trip was $2mh$ miles. Using $\\text{rate} = \\frac{\\text{distance}}{\\text{time}}$, Ruth's rate was $\\frac{2mh}{\\frac{2}{3}h} = \\frac{3}{2}(2m) = 3m$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00088",
    question_number: 88,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Of three persons, two take relish, two take pepper, and two take salt. The one who takes no salt takes no pepper, and the one who takes no pepper takes no relish. Which of the following statements must be true?\nI. The person who takes no salt also takes no relish.\nII. Any of the three persons who takes pepper also takes relish and salt.\nIII. The person who takes no relish is not one of those who takes salt.",
      options: {
        a: "I only",
        b: "II only",
        c: "III only",
        d: "I and II only",
        e: "I, II, and III",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "Although this problem can be solved by the use of a Venn diagram, it is probably simpler to use ordinary reasoning. The single person who takes no salt takes no pepper, and the single person who takes no pepper takes no relish, so exactly one person does not take any of the three. Thus, each of the other two people take all three. The table below shows these results where Person 1 does not take any of the three and Persons 2 and 3 each take all three.\n\n| Person | Relish | Pepper | Salt |\n|---|---|---|---|\n| 1 | no | no | no |\n| 2 | yes | yes | yes |\n| 3 | yes | yes | yes |\n\nThe only person who takes no salt is Person 1, who also takes no relish, so I must be true.\n\nThe only people who take pepper are Persons 2 and 3, and each of them also takes relish and salt, so II must be true.\n\nThe only person who takes no relish is Person 1, who is not a person who takes salt, so III must be true.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00089",
    question_number: 89,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "If the number of $2$ consecutive odd integers is a multiple of $5$, which of the following could NOT be the sum of those $2$ integers?",
      options: {
        a: "$-8$",
        b: "$12$",
        c: "$22$",
        d: "$52$",
        e: "$252$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "Since the smaller of the 2 consecutive odd integers is a multiple of 5, let it be represented by $5n$ for some integer $n$. Then the other odd integer can be represented by $5n + 2$. The sum of these two integers is $10n + 2$. The sum is $-8$ when $n = -1$ and $5n = (5)(-1)$ is odd. The sum is 12 when $n = 1$ and $5n = (5)(1)$ is odd. The sum is 22 when $n = 2$, but $5n = (5)(2)$ is not odd. There is no need to check the D and E because it has been determined that 22 cannot be the sum of the 2 consecutive odd integers. For completeness, the sum is 52 when $n = 5$ and $5n = (5)(5)$ is odd. The sum is 252 when $n = 25$ and $5n = (5)(25)$ is odd.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00090",
    question_number: 90,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Eight light bulbs numbered $1$ through $8$ are arranged in a circle as shown above. The bulbs are wired so that every third bulb, counting in a clockwise direction, flashes until all bulbs have flashed once. If the bulbs numbered $1$ flashes first, which numbered bulb will flash last?",
      options: {
        a: "$2$",
        b: "$3$",
        c: "$4$",
        d: "$6$",
        e: "$7$",
      },
      image_url: "images/QR_PQ_90.png",
      image_options: null,
      context_text: "Note: Question references a diagram showing 8 light bulbs arranged in a circle.",
    } as QRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "The easiest way to do this problem might be by just counting every third bulb going clockwise around the circle starting at Bulb 1, which flashes, skipping 2 bulbs and getting to Bulb 4, which flashes, skipping 2 bulbs and getting to Bulb 7, which flashes, skipping 2 bulbs and getting to Bulb 2, which flashes, skipping 2 bulbs and getting to Bulb 5, which flashes, skipping 2 bulbs and getting to Bulb 8, which flashes, skipping 2 bulbs and getting to Bulb 3, which flashes, and finally skipping 2 bulbs and getting to Bulb 6, which flashes. Now, all 8 bulbs have flashed once and the last one to flash was Bulb 6.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00091",
    question_number: 91,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "A certain financial analyst defines the \"volatility\" of a stock during a given week to be the result of the following procedure: find the absolute difference in the stock's closing price for each pair of consecutive days in that week and then find the average (arithmetic mean) of those $4$ values. What is the volatility of Stock $X$ during the week shown in the table?",
      options: {
        a: "$0.50$",
        b: "$1.80$",
        c: "$2.00$",
        d: "$2.25$",
        e: "$2.50$",
      },
      image_url: null,
      image_options: null,
      table_title: "Closing Prices of Stock X During a Certain Week (in dollars)",
      column_headers: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
      table_data: [
        ["$21$", "$19$", "$22$", "$24\\frac{1}{2}$", "$23$"]
      ],
    } as QRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "The volatility of Stock X during the week is the average of the 4 values associated with the 4 pairs of consecutive days during the week.\n\n$\\frac{(\\text{Mon } \\& \\text{ Tue}) + (\\text{Tue } \\& \\text{ Wed}) + (\\text{Wed } \\& \\text{ Thu}) + (\\text{Thu } \\& \\text{ Fri})}{4}$\n\n$= \\frac{|19 - 21| + |22 - 19| + |24.5 - 22| + |23 - 24.5|}{4}$\n\n$= \\frac{|-2| + |3| + |2.5| + |-1.5|}{4} = \\frac{2 + 3 + 2.5 + 1.5}{4} = \\frac{9}{4} = 2.25$",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00092",
    question_number: 92,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "If $y = \\frac{3x - 5}{-x^2 - 3}$, for what value of $x$ will the value of $y$ be greatest?",
      options: {
        a: "$-5$",
        b: "$-\\frac{3}{5}$",
        c: "$0$",
        d: "$\\frac{3}{5}$",
        e: "$\\frac{5}{3}$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "Since the absolute value of any real number is greater than or equal to zero, it follows that $|3x - 5| \\geq 0$. Also, for any real number $x$ we have $-x^2 \\leq 0$, and hence $-x^2 - 3 < 0$. Subtracting 3 from both sides of the last inequality gives $-x^2 - 3 \\leq -3$. Therefore, the numerator of the expression for $y$ is greater than or equal to zero and the denominator of the expression for $y$ is negative. It follows that the value of $y$ cannot be greater than 0. However, the value of $y$ is equal to 0 when $|3x - 5| = 0$, or $3x - 5 = 0$, or $x = \\frac{5}{3}$. Therefore, the value of $x$ for which the value of $y$ is greatest (i.e., when $y = 0$) is $x = \\frac{5}{3}$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00093",
    question_number: 93,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "What values of $x$ have a corresponding value of $y$ that satisfies both $xy > 0$ and $xy = x + y$?",
      options: {
        a: "$x \\leq -1$",
        b: "$-1 < x \\leq 0$",
        c: "$0 < x \\leq 1$",
        d: "$x > 1$",
        e: "All real numbers",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "First, use $xy = x + y$ to solve for $y$ in terms of $x$.\n\n$xy = x + y$ given\n\n$xy - y = x$ subtract $y$ from both sides\n\n$y(x - 1) = x$ factor\n\n$y = \\frac{x}{x - 1}$ divide both sides by $x - 1$\n\nNote that the division by $x - 1$ requires $x \\neq 1$, and thus $x = 1$ needs to be considered separately. However, if $x = 1$, then $xy = x + y$ becomes $y = 1 + y$, which is not true for any value of $y$. Using $y = \\frac{x}{x - 1}$, it follows that the inequality $xy > 0$ is equivalent to $\\frac{x^2}{x - 1} > 0$. Since $x^2 \\geq 0$ for each value of $x$, the quotient $\\frac{x^2}{x - 1}$ can only be positive when $x \\neq 0$ and $x - 1$ is positive, or when $x > 1$.\n\nAlternatively, the correct answer can be found by eliminating the incorrect answers, which can be accomplished by considering the endpoints of the intervals given in the answer choices.\n\nCase 1: If $x = -1$, then $xy = x + y$ becomes $-y = -1 + y$, or $y = \\frac{1}{2}$. However, in this case $xy = (-1)\\left(\\frac{1}{2}\\right)$ is negative, and thus $xy > 0$ is not true. Therefore, the answer cannot be A or E.\n\nCase 2: If $x = 0$, then $xy = 0$, and thus $xy > 0$ is not true. Therefore, the answer cannot be B or E.\n\nCase 3: If $x = 1$, then $xy = x + y$ becomes $y = 1 + y$, which is not true for any value of $y$. Therefore, the answer cannot be C or E.\n\nSince the answer cannot be A, B, C, or E, it follows that the answer is D.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00094",
    question_number: 94,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Employee $X$'s annual salary is $\\$12,000$ more than half of Employee $Y$'s annual salary. Employee $Z$'s annual salary is $\\$15,000$ more than half of Employee $Y$'s annual salary. If Employee $X$'s annual salary is $\\$27,500$, which of the following lists these people in order of increasing annual salary?",
      options: {
        a: "$Y, Z, X$",
        b: "$Y, X, Z$",
        c: "$Z, X, Y$",
        d: "$X, Y, Z$",
        e: "$X, Z, Y$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "Letting $x$, $y$, and $z$ represent the annual salary, in dollars, of Employee X, Employee Y, and Employee Z, respectively, the following information is given:\n\n1. $x = 12,000 + \\frac{y}{2}$\n\n2. $x = 15,000 + \\frac{z}{2}$\n\n3. $x = 27,500$\n\nFrom (1) and (3), it follows that $27,500 = 12,000 + \\frac{y}{2}$ or $y = 2(27,500 - 12,000) = 31,000$. From (2) and (3), it follows that $z = 15,000 + \\frac{27,500}{2} = 28,750$. Therefore, $x < z < y$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00095",
    question_number: 95,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The formula above gives the contribution $C$, in dollars, to a certain profit-sharing plan for a participant with a salary of $s$ dollars. How many more dollars is the contribution for a participant with a salary of $\\$70,000$ than for a participant with a salary of $\\$50,000$?",
      options: {
        a: "$\\$800$",
        b: "$\\$1,400$",
        c: "$\\$2,000$",
        d: "$\\$2,400$",
        e: "$\\$2,800$",
      },
      image_url: null,
      image_options: null,
      context_text: "$C = \\begin{cases} 0.10s, & \\text{if } s \\leq 60,000 \\\\ 0.10s + 0.04(s - 60,000), & \\text{if } s > 60,000 \\end{cases}$",
    } as QRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "For a participant with a salary of \\$70,000,\n$C = 0.1(\\$70,000) + 0.04(\\$70,000 - \\$60,000) = \\$7,000 + \\$400 = \\$7,400$. For a participant with a salary of \\$50,000, $C = 0.1(\\$50,000) = \\$5,000$. The difference is $\\$7,400 - \\$5,000 = \\$2,400$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00096",
    question_number: 96,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Next month, Ron and Cathy will each begin working part-time at $\\frac{3}{5}$ of their respective current salaries. If the sum of their reduced salaries will be equal to Cathy's current salary, then Ron's current salary is what fraction of Cathy's current salary?",
      options: {
        a: "$\\frac{1}{3}$",
        b: "$\\frac{2}{5}$",
        c: "$\\frac{1}{2}$",
        d: "$\\frac{3}{5}$",
        e: "$\\frac{2}{3}$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "Letting $R$ and $C$, respectively, represent Ron's and Cathy's current salaries, it is given that $\\frac{3}{5}R + \\frac{3}{5}C = C$. It follows that $\\frac{3}{5}R = \\frac{2}{5}C$ and $R = \\frac{5}{3}\\left(\\frac{2}{5}C\\right) = \\frac{2}{3}C$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00097",
    question_number: 97,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "David and Ron are ordering food for a business lunch. David thinks that there should be twice as many sandwiches as there are pastries, but Ron thinks the number of pastries should be 12 more than one-fourth of the number of sandwiches. How many sandwiches should be ordered so that David and Ron can agree on the number of pastries to order?",
      options: {
        a: "$12$",
        b: "$16$",
        c: "$20$",
        d: "$24$",
        e: "$48$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "Let $S$ be the number of sandwiches that should be ordered and let $P$ be the number of pastries that should be ordered. Then David desires $S = 2P$ and Ron desires $P = 12 + \\frac{1}{4}S$.\n\n$S = 2P$ given\n\n$S = 2\\left(12 + \\frac{1}{4}S\\right)$ $P = 12 + \\frac{1}{4}S$\n\n$S = 24 + \\frac{1}{2}S$ distributive law\n\n$\\frac{1}{2}S = 24$ subtract $\\frac{1}{2}S$ from both sides\n\n$S = 48$ multiply both sides by 2",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00098",
    question_number: 98,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The cost of purchasing each box of candy from a certain mail order catalog is $v$ dollars per pound of candy, plus a shipping charge of $h$ dollars. How many dollars does it cost to purchase $2$ boxes of candy, one containing $s$ pounds of candy and the other containing $t$ pounds of candy, from this catalog?",
      options: {
        a: "$h + stv$",
        b: "$2h + stv$",
        c: "$2hstv$",
        d: "$2h + s + t + v$",
        e: "$2h + v(s + t)$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "The cost, in dollars, to purchase the 2 boxes of candy is the sum of 2 shipping charges and the cost of $s + t$ pounds of candy.\n\ncost $= (2 \\text{ shipping charges}) + (v)(s + t)$\n\ncost $= 2(h) + (v)(s + t)$\n\ncost $= 2h + v(s + t)$",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00099",
    question_number: 99,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "If $x \\neq -\\frac{1}{2}$, then $\\frac{6x^3 + 3x^2 - 8x - 4}{2x + 1} =$",
      options: {
        a: "$3x^2 + \\frac{3}{2}x - 8$",
        b: "$3x^2 + \\frac{3}{2}x - 4$",
        c: "$3x^2 - 4$",
        d: "$3x - 4$",
        e: "$3x + 4$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "$\\frac{6x^3 + 3x^2 - 8x - 4}{2x + 1} = \\frac{(6x^3 + 3x^2) - (8x + 4)}{2x + 1}$ group\n\n$= \\frac{3x^2(2x + 1) - 4(2x + 1)}{2x + 1}$ factor\n\n$= \\frac{(3x^2 - 4)(2x + 1)}{2x + 1}$ factor\n\n$= 3x^2 - 4$ cancel since $x \\neq -\\frac{1}{2}$\n\nAlternatively, sometimes it is easier or quicker to test one-variable expressions for equality by substituting a convenient value for the variable and eliminating answer choices for which the value of the expression in that answer choice does not equal the value of the given expression. For example, choose $x = 0$, since calculations for $x = 0$ are minimal. Then, as shown in the table below, $\\frac{6x^3 + 3x^2 - 8x - 4}{2x + 1} = \\frac{-4}{1} = -4$, but $3x^2 + \\frac{3}{2}x - 8 = -8$ and $3x + 4 = 4$, neither of which equals $-4$, so answer choices A and E can be eliminated. Another convenient value to choose for $x$ is 1. There is no need to evaluate answer choices A and E at 1 since they have already been eliminated. As shown, when $x = 1$, $\\frac{6x^3 + 3x^2 - 8x - 4}{2x + 1} = -1$, but $3x^2 + \\frac{3}{2}x - 4 = \\frac{1}{2} \\neq -1$, so answer choice B can be eliminated. A third convenient value for $x$ is $-1$. There is no need to evaluate answer choices A, B, and E at $-1$ since they have already been eliminated. As shown, when $x = -1$, $\\frac{6x^3 + 3x^2 - 8x - 4}{2x + 1} = -1$, but $3x - 4 = -7 \\neq -1$, so answer choice D can be eliminated. Note that, if $x = -1$ had been chosen initially, A, B, D, and E would have been eliminated immediately since $3x^2 + \\frac{3}{2}x - 8 = -6\\frac{1}{2} \\neq -1$, $3x^2 + \\frac{3}{2}x - 4 = -2\\frac{1}{2} \\neq -1$, $3x - 4 = -7 \\neq -1$, and $3x + 4 = 1 \\neq -1$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00100",
    question_number: 100,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "If $x^2 + bx + 5 = (x + c)^2$ for all numbers $x$, where $b$ and $c$ are positive constants, what is the value of $b$?",
      options: {
        a: "$\\sqrt{5}$",
        b: "$\\sqrt{10}$",
        c: "$2\\sqrt{5}$",
        d: "$2\\sqrt{10}$",
        e: "$10$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "Given that $x^2 + bx + 5 = (x + c)^2$, since $(x + c)^2 = x^2 + 2cx + c^2$, it follows that $5 = c^2$ and $b = 2c$. The possible values of $c$ are $-\\sqrt{5}$ and $\\sqrt{5}$, but since $c$ is positive, $c = \\sqrt{5}$ and $b = 2c = 2\\sqrt{5}$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00101",
    question_number: 101,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Last year Shannon listened to a certain public radio station $10$ hours per week and contributed $\\$35$ to the station. Of the following, which is closest to Shannon's contribution per minute of listening time last year?",
      options: {
        a: "$\\$0.001$",
        b: "$\\$0.010$",
        c: "$\\$0.025$",
        d: "$\\$0.058$",
        e: "$\\$0.067$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("a"),
    explanation: "Since there are 52 weeks in 1 year and 60 minutes in 1 hour, 10 hours per week is equivalent to $(10)(52)(60) = 31,200$ minutes per year. Shannon's \\$35 contribution is then $\\frac{35}{31,200}$ dollars per minute, which is closest to \\$0.001 per minute.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00102",
    question_number: 102,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Each of the $20$ employees at Company J is to receive an end-of-year bonus this year. Agnes will receive a larger bonus than any other employee, but only $\\$500$ more than Cheryl will receive. None of the employees will receive a smaller bonus than Cheryl. If the amount of money to be distributed in bonuses at Company J this year totals $\\$60,000$, what is the largest bonus Agnes can receive?",
      options: {
        a: "$\\$3,250$",
        b: "$\\$3,325$",
        c: "$\\$3,400$",
        d: "$\\$3,475$",
        e: "$\\$3,500$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "Since the total amount of the bonuses is fixed, the largest possible bonus that Agnes can receive will occur when the total amount received by the 19 employees other than Agnes is the smallest possible. Let $A$ be the bonus, in dollars, that Agnes receives. Then, in dollars, Cheryl will receive $(A - 500)$, and each of the remaining 18 employees will receive between $(A - 500)$ and $A$. Therefore, the total amount received by the 19 employees other than Agnes is smallest when each of these 19 employees receives $(A - 500)$ dollars.\n\n$19(A - 500) + A = 60,000$ total of 20 bonuses is \\$60,000\n\n$19A - 9,500 + A = 60,000$ distributive law\n\n$20A - 9,500 = 60,000$ combine like terms\n\n$20A = 69,500$ add 9,500 to both sides\n\n$A = 3,475$ divide both sides by 20",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00103",
    question_number: 103,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Beth, Naomi, and Juan raised a total of $\\$55$ for charity. Naomi raised $\\$5$ less than Juan, and Juan raised twice as much as Beth. How much did Beth raise?",
      options: {
        a: "$\\$9$",
        b: "$\\$10$",
        c: "$\\$12$",
        d: "$\\$13$",
        e: "$\\$15$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "Let $B$, $N$, and $J$ be the amounts raised, respectively and in dollars, by Beth, Naomi, and Juan.\n\n$B + N + J = 55$ given\n\n$N = J - 5$ given\n\n$J = 2B$ given\n\n$J = 55 - B - N$ subtract $B + N$ from both sides of first equation",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00104",
    question_number: 104,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The set of solutions for the equation $(x^2 - 25)^2 = x^2 - 10x + 25$ contains how many real numbers?",
      options: {
        a: "$0$",
        b: "$1$",
        c: "$2$",
        d: "$3$",
        e: "$4$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "$(x^2 - 25)^2 = x^2 - 10x + 25$ given\n\n$(x + 5)^2(x - 5)^2 = (x - 5)^2$ factor\n\n$(x + 5)^2(x - 5)^2 - (x - 5)^2 = 0$ subtract $(x - 5)^2$\n\n$(x - 5)^2[(x + 5)^2 - 1] = 0$ factor\n\n$(x - 5)^2[(x + 5) - 1][(x + 5) + 1] = 0$ factor\n\n$(x - 5)^2(x + 4)(x + 6) = 0$ subtraction, addition\n\nThus, the solution set of $(x^2 - 25)^2 = x^2 - 10x + 25$ contains 3 real numbers: 5, $-4$, and $-6$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00105",
    question_number: 105,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "An aerosol can is designed so that its bursting pressure, $B$, in pounds per square inch, is $120\\%$ of the pressure, $F$, in pounds per square inch, to which it is initially filled. Which of the following formulas expresses the relationship between $B$ and $F$?",
      options: {
        a: "$B = 1.2F$",
        b: "$B = 120F$",
        c: "$B = 1 + 0.2F$",
        d: "$B = \\frac{F}{1.2}$",
        e: "$B = \\frac{1.2}{F}$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("a"),
    explanation: "We are given that $B$ is 120% of $F$, so $B = (120\\%)F$, or $B = 1.2F$. Note that both $B$ and $F$ are given in pounds per square inch, so there are no unit conversions involved.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00106",
    question_number: 106,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The average (arithmetic mean) of the positive integers $x$, $y$, and $z$ is $3$. If $x < y < z$, what is the greatest possible value of $z$?",
      options: {
        a: "$5$",
        b: "$6$",
        c: "$7$",
        d: "$8$",
        e: "$9$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "It is given that $\\frac{x + y + z}{3} = 3$, or $x + y + z = 9$, or $z = 9 + (-x - y)$. It follows that the greatest possible value of $z$ occurs when $-x - y = -(x + y)$ has the greatest possible value, which occurs when $x + y$ has the least possible value. Because $x$ and $y$ are different positive integers, the least possible value of $x + y$ occurs when $x = 1$ and $y = 2$. Therefore, the greatest possible value of $z$ is $9 - 1 - 2 = 6$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00107",
    question_number: 107,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The product of $3,305$ and the $1$-digit integer $x$ is a $5$-digit integer. The units (ones) digit of the product is $5$ and the hundreds digit is $y$. If $A$ is the set of all possible values of $x$ and $B$ is the set of all possible values of $y$, then which of the following gives the members of $A$ and $B$?",
      options: {
        a: "$\\{1, 3, 5, 7, 9\\}$ $\\{0, 1, 2, 3, 4, 5, 6, 7, 8, 9\\}$",
        b: "$\\{1, 3, 5, 7, 9\\}$ $\\{1, 3, 5, 7, 9\\}$",
        c: "$\\{3, 5, 7, 9\\}$ $\\{1, 5, 7, 9\\}$",
        d: "$\\{5, 7, 9\\}$ $\\{1, 5, 7\\}$",
        e: "$\\{5, 7, 9\\}$ $\\{1, 5, 9\\}$",
      },
      image_url: null,
      image_options: null,
      context_text: "Note: Options show sets in the format (A set values) (B set values)",
    } as QRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "Since the products of 3,305 and 1, 3,305 and 2, and 3,305 and 3 are the 4-digit integers 3,305, 6,610, and 9,915, respectively, it follows that $x$ must be among the 1-digit integers 4, 5, 6, 7, 8, and 9. Also, since the units digit of the product of 3,305 and $x$ is 5, it follows that $x$ cannot be 4 (product has units digit 0), or 8 (product has units digit 0). Therefore, $A = \\{5, 7, 9\\}$. The possibilities for $y$ will be the hundreds digits of the products $(3,305)(5) = 16,525$, $(3,305)(7) = 23,135$, and $(3,305)(9) = 29,745$. Thus, $y$ can be 5, 1, or 7, and so $B = \\{1, 5, 7\\}$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00108",
    question_number: 108,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "If $x$ and $y$ are integers such that $2 < x \\leq 8$ and $2 < y \\leq 9$, what is the maximum value of $\\frac{1}{x} - \\frac{x}{y}$?",
      options: {
        a: "$-3\\frac{1}{8}$",
        b: "$0$",
        c: "$\\frac{1}{4}$",
        d: "$\\frac{5}{18}$",
        e: "$2$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "Because $x$ and $y$ are both positive, the maximum value of $\\frac{1}{x} - \\frac{x}{y}$ will occur when the value of $\\frac{1}{x}$ is maximum and the value of $\\frac{x}{y}$ is minimum. The value of $\\frac{1}{x}$ is maximum when the value of $x$ is minimum or when $x = 3$. The value of $\\frac{x}{y}$ is minimum when the value of $x$ is minimum (or when $x = 3$) and the value of $y$ is maximum (or when $y = 9$). Thus, the maximum value of $\\frac{1}{x} - \\frac{x}{y}$ is $\\frac{1}{3} - \\frac{3}{9} = 0$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00109",
    question_number: 109,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Items that are purchased together at a certain discount store are priced at $\\$3$ for the first item purchased and $\\$1$ for each additional item purchased. What is the maximum number of items that could be purchased together for a total price that is less than $\\$30$?",
      options: {
        a: "$25$",
        b: "$26$",
        c: "$27$",
        d: "$28$",
        e: "$29$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "After the first item is purchased, $\\$29.99 - \\$3.00 = \\$26.99$ remains to purchase the additional items. Since the price for each of the additional items is \\$1.00, a maximum of 26 additional items could be purchased. Therefore, a maximum of $1 + 26 = 27$ items could be purchased for less than \\$30.00.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00110",
    question_number: 110,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "What is the least integer $z$ for which $(0.000125)(0.0025)(0.00000125) \\times 10^z$ is an integer?",
      options: {
        a: "$18$",
        b: "$10$",
        c: "$0$",
        d: "$-10$",
        e: "$-18$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("a"),
    explanation: "Considering each of the three decimal numbers in parentheses separately, we know that $0.000125 \\times 10^6$ is the integer 125, $0.0025 \\times 10^4$ is the integer 25, and $0.00000125 \\times 10^8$ is the integer 125. We thus know that $(0.000125) \\times 10^8 \\times (0.0025) \\times 10^4 \\times (0.00000125) \\times 10^8 = (0.000125)(0.0025)(0.00000125) \\times 10^6 \\times 10^4 \\times 10^8 = (0.000125)(0.0025)(0.00000125) \\times 10^{6 + 4 + 8} = (0.000125)(0.0025)(0.00000125) \\times 10^{18}$ is the integer $125 \\times 25 \\times 125$. We therefore know that if $z = 18$, then $(0.000125)(0.0025)(0.00000125) \\times 10^z$ is an integer.\n\nNow, if the product $125 \\times 25 \\times 125$ were divisible by 10, then for at least one integer $z$ less than 18, $(0.000125)(0.0025)(0.00000125) \\times 10^z$ would be an integer. However, each of the three numbers being multiplied in the product $125 \\times 25 \\times 125$ is odd (not divisible by 2). We thus know that $125 \\times 25 \\times 125$ is not divisible by 2 in the product $125 \\times 25 \\times 125$ is odd (not divisible by 2). We thus know that $125 \\times 25 \\times 125$ is not divisible by 2 and is therefore odd. Because only even numbers are divisible by 10, we know that $125 \\times 25 \\times 125$ is not divisible by 10. We thus know that 18 is the *least* integer $z$ such that $(0.000125)(0.0025)(0.00000125) \\times 10^z$ is an integer.\n\nNote that it is not necessary to perform the multiplication $125 \\times 25 \\times 125$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00111",
    question_number: 111,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The average (arithmetic mean) length per film for a group of $21$ films is $t$ minutes. If a film that runs for $66$ minutes is removed from the group and replaced by one that runs for $52$ minutes, what is the average length per film, in minutes, for the new group of films, in terms of $t$?",
      options: {
        a: "$t + \\frac{2}{3}$",
        b: "$t - \\frac{2}{3}$",
        c: "$21t - 14$",
        d: "$t + \\frac{3}{2}$",
        e: "$t - \\frac{3}{2}$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "Let $S$ denote the sum of the lengths, in minutes, of the 21 films in the original group. Since the average length is $t$ minutes, it follows that $\\frac{S}{21} = t$. If a 66-minute film is replaced by a 52-minute film, then the sum of the lengths of the 21 films in the resulting group is $S - 66 + 52 = S - 14$. Therefore, the average length of the resulting 21 films is $\\frac{S - 14}{21} = \\frac{S}{21} - \\frac{14}{21} = t - \\frac{2}{3}$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00112",
    question_number: 112,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "A garden center sells a certain grass seed in $5$-pound bags at $\\$13.85$ per bag, $10$-pound bags at $\\$20.43$ per bag, and $25$-pound bags at $\\$32.25$ per bag. If a customer is to buy at least $65$ pounds of the grass seed, but no more than $80$ pounds, what is the least possible cost of the grass seed that the customer will buy?",
      options: {
        a: "$\\$94.03$",
        b: "$\\$96.75$",
        c: "$\\$98.78$",
        d: "$\\$102.07$",
        e: "$\\$105.36$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "Let $x$ represent the amount of grass seed, in pounds, the customer is to buy. It follows that $65 \\leq x \\leq 80$. Since the grass seed is available in only 5-pound, 10-pound, and 25-pound bags, then the customer must buy either 65, 70, 75, or 80 pounds of grass seed. Because the seed is more expensive per pound for smaller bags, the customer should minimize the number of the smaller bags and maximize the number of 25-pound bags to incur the least possible cost for the grass seed. The possible purchases are given in the table below.\n\n| $x$ | Number of 25-pound bags | Number of 10-pound bags | Number of 5-pound bags | Total cost |\n|-----|------------------------|------------------------|----------------------|------------|\n| 65 | 2 | 1 | 1 | \\$98.78 |\n| 70 | 2 | 2 | 0 | \\$105.36 |\n| 75 | 3 | 0 | 0 | \\$96.75 |\n| 80 | 3 | 0 | 1 | \\$110.60 |\n\nThe least possible cost is then $3(\\$32.25) = \\$96.75$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00113",
    question_number: 113,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "If $x = -|w|$, which of the following must be true?",
      options: {
        a: "$x = -w$",
        b: "$x = w$",
        c: "$x^2 = w$",
        d: "$x^2 = w^2$",
        e: "$x^3 = w^3$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "Squaring both sides of $x = -|w|$ gives $x^2 = (-|w|)^2$, or $x^2 = |w|^2 = w^2$.\n\nAlternatively, if $(x, w)$ is equal to either of the pairs $(-1, 1)$ or $(-1, -1)$, then $x = -|w|$ is true. However, each of the answer choices except $x^2 = w^2$ is false for at least one of these two pairs.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00114",
    question_number: 114,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "A certain financial institution reported that its assets totaled $\\$2,377,366.30$ on a certain day. Of this amount, $\\$31,724.54$ was held in cash. Approximately what percent of the reported assets was held in cash on that day?",
      options: {
        a: "$0.00013\\%$",
        b: "$0.0013\\%$",
        c: "$0.013\\%$",
        d: "$0.13\\%$",
        e: "$1.3\\%$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "The requested percent can be estimated by converting the values into scientific notation.\n\n$\\frac{31,724.54}{2,377,366.30}$ value as fraction\n\n$= \\frac{3.172454 \\times 10^4}{2.37736630 \\times 10^6}$ convert to scientific notation\n\n$= \\frac{3.172454}{2.37736630} \\times \\frac{10^4}{10^6}$ arithmetic property of fractions\n\n$= \\frac{3.172454}{2.37736630} \\times 10^{-2}$ subtract exponents\n\n$\\approx \\frac{3}{2} \\times 10^{-2}$ approximate\n\n$= 1.5 \\times 10^{-2}$ convert to decimal fraction\n\n$= 0.015$ multiply\n\n$= 1.5\\%$ convert to percent\n\nA more detailed computation would show that 1.3% is a better approximation. However, in order to select the best value from the values given as answer choices, the above computation is sufficient.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00115",
    question_number: 115,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "In the correctly worked addition problem shown, where the sum of the two-digit positive integers $AB$ and $BA$ is the three-digit integer $ACB$, and $A$, $B$, and $C$ are different digits, what is the units digit of the integer $ACB$?",
      options: {
        a: "$9$",
        b: "$6$",
        c: "$3$",
        d: "$2$",
        e: "$0$",
      },
      image_url: "images/QR_PQ_115.png",
      image_options: null,
      context_text: "$\\begin{array}{r} AB \\\\ + BA \\\\ \\hline ACB \\end{array}$",
    } as QRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "Determine the value of $C$.\n\nIt is given that $(10A + B) + (10B + A) = 100A + 10A + C$ or $11A + 11B = 110A + C$. Thus, $11B - 99A = C$, or $11(B - 9A) = C$. Therefore, $C$ is divisible by 11, and 0 is the only digit that is divisible by 11.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00116",
    question_number: 116,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The hard drive, monitor, and printer for a certain desktop computer system cost a total of $\\$2,500$. The cost of the printer is $\\frac{2}{3}$ the cost of the hard drive. If the cost of the printer is $\\$100$ more than the cost of the monitor, what is the cost of the printer?",
      options: {
        a: "$\\$800$",
        b: "$\\$600$",
        c: "$\\$550$",
        d: "$\\$500$",
        e: "$\\$350$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "Letting $d$, $m$, and $p$, respectively, represent the cost of the hard drive, monitor, and printer, the following equations are given:\n\n1. $d + m + p = 2,500$\n\n2. $p + m = \\frac{2}{3}d$\n\n3. $p = m + 100$\n\nUsing (2) and substituting $\\frac{2}{3}d$ for $m + p$ in (1) gives $\\frac{5}{3}d = 2,500$, from which $d = 1,500$. Then from (1), $p + m = 1,000$, but $m = p - 100$ from (2), so $2p - 100 = 1,000$, $2p = 1,100$, and $p = 550$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00117",
    question_number: 117,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Given the inequalities above, which of the following CANNOT be the value of $r$?",
      options: {
        a: "$-20$",
        b: "$-5$",
        c: "$0$",
        d: "$5$",
        e: "$20$",
      },
      image_url: null,
      image_options: null,
      context_text: "$3r \\leq 4s + 5$\n$|s| \\leq 5$",
    } as QRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "Since $|s| \\leq 5$, it follows that $-5 \\leq s \\leq 5$. Therefore, $-20 \\leq 4s \\leq 20$, and hence $-15 \\leq 4s + 5 \\leq 25$. Since $3r \\leq 4s + 5$ (given) and $4s + 5 \\leq 25$ (end of previous sentence), it follows that $3r \\leq 25$. Among the answer choices, $3r \\leq 25$ is false only for $r = 20$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00118",
    question_number: 118,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "If $m$ is an even integer, $v$ is an odd integer, and $m > v > 0$, which of the following represents the number of even integers less than $m$ and greater than $v$?",
      options: {
        a: "$\\frac{m - v}{2} - 1$",
        b: "$\\frac{m - v - 1}{2}$",
        c: "$\\frac{m - v}{2}$",
        d: "$m - v - 1$",
        e: "$m - v$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "Since there is only one correct answer, one method of solving the problem is to choose values for $m$ and $v$ and determine which of the expressions gives the correct number for these values. For example, if $m = 6$ and $v = 1$, then there are 2 even integers less than 6 and greater than 1, namely the even integers 2 and 4. As the table below shows, $\\frac{m - v - 1}{2}$ is the only expression given that equals 2.\n\n$\\frac{m - v}{2} - 1 = 1.5$\n\n$\\frac{m - v - 1}{2} = 2$\n\n$\\frac{m - v}{2} = 2.5$\n\n$m - v - 1 = 4$\n\n$m - v = 5$\n\nTo solve this problem it is not necessary to show that $\\frac{m - v - 1}{2}$ always gives the correct number of even integers. However, one way this can be done is by the following method, first shown for a specific example and then shown in general. For the specific example, suppose $v = 15$ and $m = 144$. Then a list—call it the first list—of the even integers greater than $v$ and less than $m$ is 16, 18, 20, …, 140, 142. Now subtract 14 (chosen so that the second list will begin with 2) from each of the integers in the first list to form a second list, which has the same number of integers as the first list: 2, 4, 6, …, 128. Finally, divide each of the integers in the second list (all of which are even) by 2 to form a third list, which also has the same number of integers as the first list: 1, 2, 3, …, $\\frac{m - v - 3}{2}$, $\\frac{m - v - 1}{2}$. Since the number of integers in the third list is $\\frac{m - v - 1}{2}$, it follows that the number of integers in the first list is $\\frac{m - v - 1}{2}$.\n\nFor the general situation, the first list is the following list of even integers: $v + 1$, $v + 3$, $v + 5$, …, $m - 4$, $m - 2$. Now subtract the even integer $v - 1$ from (i.e., add $-(v-1)$) to each of the integers in the first list to obtain the second list: 2, 4, 6, …, $m - 4 - (v - 1) = m - v - 3$, $m - 2 - (v - 1) = m - v - 1$. Finally, divide each of the integers (all of which are even) in the second list by 2 to obtain the third list: 1, 2, 3, …, $\\frac{m - v - 3}{2}$, $\\frac{m - v - 1}{2}$. Since the number of integers in the third list is $\\frac{m - v - 1}{2}$, it follows that the number of integers in the first list is $\\frac{m - v - 1}{2}$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00119",
    question_number: 119,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "A positive integer is divisible by $9$ if and only if the sum of its digits is divisible by $9$. If $n$ is a positive integer, for which of the following values of $k$ is $25 \\times 10^n + k \\times 10^{2n}$ divisible by $9$?",
      options: {
        a: "$9$",
        b: "$16$",
        c: "$23$",
        d: "$35$",
        e: "$47$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "Since $n$ can be any positive integer, let $n = 2$. Then $25 \\times 10^n = 2,500$, so its digits consist of the digits 2 and 5 followed by two digits of 0. Also, $k \\times 10^{2n} = k \\times 10,000$, so its digits consist of the digits of $k$ followed by four digits of 0. Therefore, the digits of $(25 \\times 10^n) + (k \\times 10^{2n})$ consist of the digits of $k$ followed by the digits 2 and 5, followed by two digits of 0. The table below shows this for $n = 2$ and $k = 35$:\n\n$25 \\times 10^n = 2,500$\n\n$35 \\times 10^{2n} = 350,000$\n\n$(25 \\times 10^n) + (35 \\times 10^{2n}) = 352,500$\n\nThus, when $n = 2$, the sum of the digits of $(25 \\times 10^n) + (k \\times 10^{2n})$ will be $2 + 5 = 7$ plus the sum of the digits of $k$. Of the answer choices, this sum of digits is divisible by 9 only for $k = 47$, which gives $2 + 5 + 4 + 7 = 18$. It can also be verified that, for each positive integer $n$, the only such answer choice is $k = 47$, although this additional verification is not necessary to obtain the correct answer.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00120",
    question_number: 120,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "On the number line, the shaded interval is the graph of which of the following inequalities?",
      options: {
        a: "$|x| \\leq 4$",
        b: "$|x| \\leq 8$",
        c: "$|x - 2| \\leq 4$",
        d: "$|x - 2| \\leq 6$",
        e: "$|x + 2| \\leq 6$",
      },
      image_url: null,
      image_options: null,
      context_text: "Number line showing shaded interval from -4 to 5 (including both endpoints)",
    } as QRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "The midpoint of the interval from $-8$ to 4, inclusive, is $\\frac{-8 + 4}{2} = -2$ and the length of the interval from $-8$ to 4, inclusive, is $4 - (-8) = 12$, so the interval consists of all numbers within a distance of $\\frac{12}{2} = 6$ from $-2$. Using an inequality involving absolute values, this can be described by $|x - (-2)| \\leq 6$, or $|x + 2| \\leq 6$.\n\nAlternatively, the inequality $-8 \\leq x \\leq 4$ can be written as the conjunction $-8 \\leq x$ and $x \\leq 4$. Rewrite this conjunction so that the lower value, $-8$, and the upper value, 4, are shifted to values that have the same magnitude. This can be done by adding 2 to each side of each inequality, which gives $-6 \\leq x + 2$ and $x + 2 \\leq 6$. Thus, $x + 2$ lies between $-6$ and 6, inclusive, and it follows that $|x + 2| \\leq 6$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00121",
    question_number: 121,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Last year members of a certain professional organization for teachers consisted of teachers from $49$ different school districts, with an average (arithmetic mean) of $9.8$ schools per district. Last year the average number of teachers at these schools who were members of the organization was $22$. Which of the following is closest to the total number of members of the organization last year?",
      options: {
        a: "$10^7$",
        b: "$10^6$",
        c: "$10^5$",
        d: "$10^4$",
        e: "$10^3$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "There are 49 school districts and an average of 9.8 schools per district, so the number of schools is $(49)(9.8) \\approx (50)(10) = 500$. There are approximately 500 schools and an average of 22 teachers at each school, so the number of teachers is approximately $(500)(22) \\approx (500)(20) = 10,000 = 10^4$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00122",
    question_number: 122,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Of all the students in a certain dormitory, $\\frac{1}{2}$ are first-year students and the rest are second-year students. If $\\frac{4}{5}$ of the first-year students have not declared a major and if the fraction of second-year students who have declared a major is $3$ times the fraction of first-year students who have declared a major, what fraction of all the students in the dormitory are second-year students who have not declared a major?",
      options: {
        a: "$\\frac{1}{15}$",
        b: "$\\frac{1}{5}$",
        c: "$\\frac{4}{15}$",
        d: "$\\frac{1}{3}$",
        e: "$\\frac{2}{5}$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "Consider the table below in which $T$ represents the total number of students in the dormitory. Since $\\frac{1}{2}$ of the students are first-year students and the rest are second-year students, it follows that $\\frac{1}{2}$ of the students are second-year students, and so the totals for the first-year and second-year columns are both $0.5T$. Since $\\frac{4}{5}$ of the first-year students have not declared a major, it follows that the middle entry in the first-year column is $\\frac{4}{5}(0.5T) = 0.4T$ and the first entry in the first-year column is $0.5T - 0.4T = 0.1T$. Since the fraction of second-year students who have declared a major is 3 times the fraction of first-year students who have declared a major, it follows that the first entry in the second-year column is $3(0.1T) = 0.3T$ and the second entry in the second-year column is $0.5T - 0.3T = 0.2T$. Thus, the fraction of students that are second-year students who have not declared a major is $\\frac{0.2T}{T} = 0.2 = \\frac{1}{5}$.\n\n|  | First-year | Second-year | Total |\n|---|---|---|---|\n| Declared major | $0.1T$ | $0.3T$ | $0.4T$ |\n| Not declared major | $0.4T$ | $0.2T$ | $0.6T$ |\n| Total | $0.5T$ | $0.5T$ | $T$ |",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00123",
    question_number: 123,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "If the average (arithmetic mean) of $x$, $y$, and $z$ is $7x$, what is the ratio of $x$ to the sum of $y$ and $z$?",
      options: {
        a: "$1:21$",
        b: "$1:20$",
        c: "$1:6$",
        d: "$6:1$",
        e: "$20:1$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "Given that the average of $x$, $y$, and $z$ is $7x$, it follows that $\\frac{x + y + z}{3} = 7x$, or $x + y + z = 21x$, or $y + z = 20x$. Dividing both sides of the last equation by $20(y + z)$ gives $\\frac{1}{20} = \\frac{x}{y + z}$, so the ratio of $x$ to the sum of $y$ and $z$ is 1:20.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00124",
    question_number: 124,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Jonah drove the first half of a $100$-mile trip in $x$ hours and the second half in $y$ hours. Which of the following is equal to Jonah's average speed, in miles per hour, for the entire trip?",
      options: {
        a: "$\\frac{50}{x + y}$",
        b: "$\\frac{100}{x + y}$",
        c: "$\\frac{25}{x} + \\frac{25}{y}$",
        d: "$\\frac{50}{x} + \\frac{50}{y}$",
        e: "$\\frac{100}{x} + \\frac{100}{y}$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "Using average speed $= \\frac{\\text{total distance}}{\\text{total time}}$, it follows that Jonah's average speed for his entire 100-mile trip is $\\frac{100}{x + y}$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00125",
    question_number: 125,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "If the amount of federal estate tax due on an estate valued at $\\$1.35$ million is $\\$437,000$ plus $43$ percent of the value of the estate in excess of $\\$1.25$ million, then the federal tax due is approximately what percent of the value of the estate?",
      options: {
        a: "$30\\%$",
        b: "$35\\%$",
        c: "$40\\%$",
        d: "$45\\%$",
        e: "$50\\%$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "The amount of tax divided by the value of the estate is\n\n$\\frac{[0.437 + (0.43)(1.35 - 1.25)]}{1.35}$ value as fraction\n\n$= \\frac{0.437 + (0.43)(0.1)}{1.35}$ arithmetic\n\n$= \\frac{0.48}{1.35} = \\frac{48}{135}$ arithmetic\n\nBy long division, $\\frac{48}{135}$ is approximately 35.6, so the closest answer choice is 35%.\n\nAlternatively, $\\frac{48}{135}$ can be estimated by $\\frac{48}{136} = \\frac{6}{17} \\approx \\frac{6}{18} = \\frac{1}{3} \\approx 33\\%$, so the closest answer choice is 35%. Note that $\\frac{48}{135}$ is greater than $\\frac{48}{136}$, and $\\frac{6}{17}$ is greater than $\\frac{6}{18}$, so the correct value is greater than 33%, which rules out 30% being the closest.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00126",
    question_number: 126,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "A manufacturer wants to produce $x$ balls and $y$ boxes. Resource constraints require that $x$ and $y$ satisfy the inequalities shown. What is the maximum number of balls and boxes combined that can be produced given the resource constraints?",
      options: {
        a: "$5,000$",
        b: "$6,000$",
        c: "$7,000$",
        d: "$8,000$",
        e: "$10,000$",
      },
      image_url: null,
      image_options: null,
      context_text: "$7x + 6y \\leq 38,000$\n$4x + 5y \\leq 28,000$",
    } as QRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "We are to determine the maximum value of $x + y$ given the inequalities above. Note that if $A \\leq B$ and $C \\leq D$, then we can \"add inequalities\" to obtain $A + C \\leq B + D$, since (roughly speaking) the sum of two smaller numbers is less than the sum of two larger numbers. Adding the inequalities shown above gives $(7x + 6y) + (4x + 5y) \\leq 38,000 + 28,000$, or $11x + 11y \\leq 66,000$. Dividing both sides of this last inequality by 11 gives $x + y \\leq 6,000$. Therefore, the values of $x + y$ are at most 6,000, and hence the maximum value of $x + y$ is *at most* 6,000.\n\nThe fact that the maximum value of $x + y$ is *equal* to 6,000 follows from the fact that the system of simultaneous equations $7x + 6y = 38,000$ and $4x + 5y = 28,000$ has a solution, which in turn follows from the fact that these two equations correspond to a pair of nonparallel lines in the standard $(x, y)$ coordinate plane. In particular, the pair $x = 2,000$ and $y = 4,000$ satisfy both the two inequalities and the equation $x + y = 6,000$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00127",
    question_number: 127,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "If $\\frac{3}{10^4} = x\\%$, then $x =$",
      options: {
        a: "$0.3$",
        b: "$0.03$",
        c: "$0.003$",
        d: "$0.0003$",
        e: "$0.00003$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "Given that $\\frac{3}{10^4} = x\\%$, and writing $x\\%$ as $\\frac{x}{100}$, it follows that $\\frac{3}{10^4} = \\frac{x}{100}$. Multiplying both sides by 100 gives $x = \\frac{300}{10^4} = \\frac{300}{10,000} = \\frac{3}{100} = 0.03$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00128",
    question_number: 128,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "What is the remainder when $3^{24}$ is divided by $5$?",
      options: {
        a: "$0$",
        b: "$1$",
        c: "$2$",
        d: "$3$",
        e: "$4$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "A pattern in the units digits of the numbers 3, $3^2 = 9$, $3^3 = 27$, $3^4 = 81$, $3^5 = 243$, etc., can be found by observing that the units digit of a product of two integers is the same as the units digit of the product of the units digit of the two integers. For example, the units digit of $3^5 = 3 \\times 3^4 = 3 \\times 81$ is 3 since the units digit of $3 \\times 1$ is 3, and the units digit of $3^6 = 3 \\times 3^5 = 3 \\times 243$ is 9 since the units digit of $3 \\times 3$ is 9. From this it follows that the units digit of the powers of 3 follow the pattern 3, 9, 7, 1, 3, 9, 7, 1, etc., with a units digit of 1 for $3^4$, $3^8$, $3^{12}$, ..., $3^{24}$, .... Therefore, the units digit of $3^{24}$ is 1. Thus, $3^{24}$ is 1 more than a multiple of 10, and hence $3^{24}$ is 1 more than a multiple of 5, and so the remainder when $3^{24}$ is divided by 5 is 1.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00129",
    question_number: 129,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "José has a collection of $100$ coins, consisting of nickels, dimes, quarters, and half-dollars. If he has a total of $35$ nickels and dimes, a total of $45$ dimes and quarters, and a total of $50$ nickels and quarters, how many half-dollars does he have?",
      options: {
        a: "$15$",
        b: "$20$",
        c: "$25$",
        d: "$30$",
        e: "$35$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "Letting $n$, $d$, $q$, and $h$, respectively, represent the numbers of nickels, dimes, quarters, and half-dollars José has, determine the value of $h$.\n\nThe following are given:\n\n1. $n + d + q + h = 100$\n\n2. $n + d = 35$\n\n3. $d + q = 45$\n\n4. $n + q = 50$\n\nAdding (2), (3), and (4) gives $2n + 2d + 2q = 130$ or $n + d + q = 65$. Subtracting this equation from (1) gives $h = 100 - 65 = 35$.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00130",
    question_number: 130,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "David used part of $\\$100,000$ to purchase a house. Of the remaining portion, he invested $\\frac{1}{3}$ of it at $4$ percent simple annual interest and $\\frac{2}{3}$ of it at $6$ percent simple annual interest. If after a year the income from the two investments totaled $\\$320$, what was the purchase price of the house?",
      options: {
        a: "$\\$96,000$",
        b: "$\\$94,000$",
        c: "$\\$88,000$",
        d: "$\\$75,000$",
        e: "$\\$40,000$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "Let $x$ be the amount, in dollars, that David used to purchase the house. Then David invested $(100,000 - x)$ dollars, $\\frac{1}{3}$ at 4% simple annual interest and $\\frac{2}{3}$ of it at 6% simple annual interest. After one year the total interest, in dollars, on this investment was $\\frac{1}{3}(100,000 - x)(0.04) + \\frac{2}{3}(100,000 - x)(0.06) = 320$. Solve this equation to find the value of $x$.\n\n$\\frac{1}{3}(100,000 - x)(0.04) + \\frac{2}{3}(100,000 - x)(0.06) = 320$ given\n\n$(100,000 - x)(0.04) + 2(100,000 - x)(0.06) = 960$ multiply both sides by 3\n\n$4,000 - 0.04x + 12,000 - 0.12x = 960$ distributive property\n\n$16,000 - 0.16x = 960$ combine like terms\n\n$16,000 - 960 = 0.16x$ add $0.16x - 960$ to both sides\n\n$100,000 - 6,000 = x$ divide both sides by 0.16\n\n$94,000 = x$\n\nTherefore, the purchase price of the house was \\$94,000.",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00131",
    question_number: 131,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "A certain manufacturer sells its product to stores in $113$ different regions worldwide, with an average (arithmetic mean) of $181$ stores per region. If last year these stores sold an average of $51,752$ units of the manufacturer's product per store, which of the following is closest to the total number of units of the manufacturer's product sold worldwide last year?",
      options: {
        a: "$10^6$",
        b: "$10^7$",
        c: "$10^8$",
        d: "$10^9$",
        e: "$10^{10}$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "$(113)(181)(51,752) \\approx (100)(200)(50,000)$\n\n$= 10^2 \\times (2 \\times 10^2) \\times (5 \\times 10^4)$\n\n$= (2 \\times 5) \\times 10^{2+2+4}$\n\n$= 10^1 \\times 10^8 = 10^9$",
    categories: [],
  },
  {
    id: "QR-GMAT-PQ_-00132",
    question_number: 132,
    section: "Quantitative Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Andrew started saving at the beginning of the year and had saved $\\$240$ by the end of the year. He continued to save and by the end of $2$ years had saved a total of $\\$540$. Which of the following is closest to the percent increase in the amount Andrew saved during the second year compared to the amount he saved during the first year?",
      options: {
        a: "$11\\%$",
        b: "$25\\%$",
        c: "$44\\%$",
        d: "$56\\%$",
        e: "$125\\%$",
      },
      image_url: null,
      image_options: null,
    } as QRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "Andrew saved \\$240 in the first year and $\\$540 - \\$240 = \\$300$ in the second year. The percent increase in the amount Andrew saved in the second year compared to the amount he saved in the first year is\n\n$\\left(\\frac{300 - 240}{240} \\times 100\\right)\\% = \\left(\\frac{60}{240} \\times 100\\right)\\% = \\left(\\frac{1}{4} \\times 100\\right)\\% = 25\\%$.",
    categories: [],
  },
];
