// Official Guide Reading Comprehension Passages

export const PASSAGE_001 = {
  id: "RC-OG-PASSAGE-001",
  title: "Circadian Rhythms and the SCN",
  content: `Scientists long believed that two nerve clusters in the human hypothalamus, called suprachiasmatic nuclei (SCNs), were what controlled our circadian rhythms. Those rhythms are the biological cycles that recur approximately every 24 hours in synchronization with the cycle of sunlight and darkness caused by Earth's rotation. Studies have demonstrated that in some animals, the SCNs control daily fluctuations in blood pressure, body temperature, activity level, and alertness, as well as the nighttime release of the sleep-promoting agent melatonin. Furthermore, cells in the human retina dedicated to transmitting information about light levels to the SCNs have recently been discovered.

Four critical genes governing circadian cycles have been found to be active in every tissue, however, not just the SCNs, of flies, mice, and humans. In addition, when laboratory rats that usually ate at will were fed only once a day, peak activity of a clock gene in their livers shifted by 12 hours, whereas the same clock gene in the SCNs remained synchronized with light cycles. While scientists do not dispute the role of the SCNs in controlling core functions such as the regulation of body temperature and blood pressure, scientists now believe that circadian clocks in other organs and tissues may respond to external cues other than light—including temperature changes—that recur regularly every 24 hours.`,
  topic: "science"
};

export const PASSAGE_002 = {
  id: "RC-OG-PASSAGE-002",
  title: "Service Guarantees in Restaurants",
  content: `In their study of whether offering a guarantee of service quality will encourage customers to visit a particular restaurant, Tucci and Talaga have found that the effect of such guarantees is mixed. For higher-priced restaurants, there is some evidence that offering a guarantee increases the likelihood of customer selection, probably reflecting the greater financial commitment involved in choosing an expensive restaurant. For lower-priced restaurants, where one expects less assiduous service, Tucci and Talaga found that a guarantee could actually have a negative effect: a potential customer might think that a restaurant offering a guarantee is worried about its service. Moreover, since customers understand a restaurant's product and know what to anticipate in terms of service, they are empowered to question its quality. This is not generally true in the case of skilled activities such as electrical work, where, consequently, a guarantee might have greater customer appeal.

For restaurants generally, the main benefit of a service guarantee probably lies not so much in customer appeal as in managing and motivating staff. Staff members would know what service standards are expected of them and also know that the success of the business relies on their adhering to those standards. Additionally, guarantees provide some basis for defining the skills needed for successful service in areas traditionally regarded as unskilled, such as waiting tables.`,
  topic: "business"
};

export const PASSAGE_003 = {
  id: "RC-OG-PASSAGE-003",
  title: "Rain Forest Preservation and Agricultural Technology",
  content: `One proposal for preserving rain forests is to promote the adoption of new agricultural technologies, such as improved plant varieties and use of chemical herbicides, which would increase productivity and slow deforestation by reducing demand for new cropland. Studies have shown that farmers in developing countries who have achieved certain levels of education, wealth, and security of land tenure are more likely to adopt such technologies. But these studies have focused on villages with limited land that are tied to a market economy rather than on the relatively isolated, self-sufficient communities with ample land characteristic of rain-forest regions. A recent study of the Tawahka people of the Honduran rain forest found that farmers with some formal education were more likely to adopt improved plant varieties but less likely to use chemical herbicides and that those who spoke Spanish (the language of the market economy) were more likely to adopt both technologies. Nonland wealth was also associated with more adoption of both technologies, but availability of uncultivated land reduced the incentive to employ the productivity-enhancing technologies. Researchers also measured land-tenure security in Tawahka society, kinship ties are a more important indicator of this than are legal property rights, so researchers measured it by a household's duration of residence in its village. They found that longer residence correlated with more adoption of improved plant varieties but less adoption of chemical herbicides.`,
  topic: "social science"
};

export const PASSAGE_004 = {
  id: "RC-OG-PASSAGE-004",
  title: "Monetizing Ecosystem Functions",
  content: `The argument for "monetizing"—or putting a monetary value on—ecosystem functions may be stated thus: Concern about the depletion of natural resources is widespread, but this concern, in the absence of an economic argument for conservation, has not translated into significant conservational progress. Some critics blame this impasse on environmentalists, whom they believe fail to address the economic issues of environmental degradation. Conservation can appear unprofitable when compared with the economic returns derived from converting natural assets (pristine coastlines, for example) into explicitly commercial ones (such as resort hotels). But according to David Pearce, that illusion stems from the fact that "services" provided by ecological systems are not traded on the commodities market, and thus have no readily quantifiable value. To remedy this, says Pearce, one has to show that all ecosystems have economic value—indeed, that all ecological services are economic services. Tourists visiting wildlife preserves, for example, create jobs and generate income for national economies; undisturbed forests and wetlands regulate water runoff and act as water-purifying systems, saving millions of dollars worth of damage to property and to marine ecosystems. In Gretchen Daily's view, monetization, while unpopular with many environmentalists, reflects the dominant role that economic considerations play in human behavior, and the expression of economic value in a common currency helps inform environmental decision-making processes.`,
  topic: "economics"
};

export const PASSAGE_005 = {
  id: "RC-OG-PASSAGE-005",
  title: "Social Learning in Animals: Food Preferences",
  content: `Social learning in animals is said to occur when direct or indirect social interaction facilitates the acquisition of a novel behavior. It usually takes the form of an experienced animal (the demonstrator) performing a behavior such that the naive animal (the observer) subsequently expresses the same behavior sooner, or more completely, than it would have otherwise. One example of social learning is the acquisition of preferences for novel foods.

Some experiments have suggested that among mammals, social learning facilitates the identification of beneficial food items, but that among birds, social learning helps animals avoid toxic substances. For example, one study showed that when red-wing blackbirds observed others consuming a colored food or a food in a distinctly marked container and then becoming ill, they subsequently avoided food associated with that color or container. Another experiment showed house sparrows consumed less red food after they observed others eating red food that was treated so as to be noxious. Studies on nonavian species have not produced similar results, leading researchers to speculate avian social learning may be fundamentally different from that of mammals.

But Sherwin's recent experiments with domestic hens do not support the notion that avian social learning necessarily facilitates aversion to novel foods that are noxious or toxic. Even when demonstrator hens reacted with obvious disgust to a specific food via vigorous headshaking and bill-wiping, there was no evidence that observers subsequently avoided eating that food. Sherwin's research team speculated that ecological or social constraints during the evolution of this species might have resulted in there being little benefit from the social learning of unpalatability. For instance, selective pressures for this mode of learning would be reduced if the birds rarely encountered noxious or toxic food or rarely interacted after eating such food, or if the consequences of ingestion were minimal. In a related experiment, the same researchers showed if observer hens watched demonstrator hens react favorably to food of a particular color, then observer hens ate more food of that color than they ate of food of other colors. These results confirmed avian species can develop preferences for palatable food through social learning.`,
  topic: "science"
};

export const PASSAGE_006 = {
  id: "RC-OG-PASSAGE-006",
  title: "Banks and Economic Growth in Early United States",
  content: `Historians remain divided over the role of banks in facilitating economic growth in the United States in the late eighteenth and early nineteenth centuries. Some scholars contend that banks played a minor role in the nation's growing economy. Financial institutions, they argue, appeared only after the economy had begun to develop, and once organized, followed conservative lending practices, providing aid to established commercial enterprises but shunning those, such as manufacturing and transportation projects, that were more uncertain and capital-intensive (i.e., requiring greater expenditures in the form of capital than in labor).

A growing number of historians argue, in contrast, that banks were crucial in transforming the early national economy. When state legislatures began granting more bank charters in the 1790s and early 1800s, the supply of credit rose accordingly. Unlike the earliest banks, which had primarily provided short-term loans to well-connected merchants, the banks of the early nineteenth century issued credit widely. As Paul Gilje asserts, the expansion and democratization of credit in the early nineteenth century became the driving force of the American economy, as banks began furnishing large amounts of capital to transportation and industrial enterprises. The exception, such historians argue, was in the South; here, the overwhelmingly agrarian nature of the economy generated outright opposition to banks, which were seen as monopolistic institutions controlled by an elite group of planters.`,
  topic: "history"
};

export const PASSAGE_007 = {
  id: "RC-OG-PASSAGE-007",
  title: "Strategic Partnerships in Western and Japanese Business",
  content: `In recent years, Western business managers have been heeding the exhortations of business journalists and academics to move their companies toward long-term, collaborative "strategic partnerships" with their external business partners (e.g., suppliers). The experts' advice comes as a natural reaction to numerous studies conducted during the past decade that compared Japanese production and supply practices with those of the rest of the world. The link between the success of a certain well-known Japanese automaker and its effective management of its suppliers, for example, has led to an unquestioning belief within Western management circles in the value of strategic partnerships. Indeed, in the automobile sector all three United States manufacturers and most of their European competitors have launched programs to reduce their total number of suppliers and move toward having strategic partnerships with a few.

However, new research concerning supplier relationships in various industries demonstrates that the widespread assumption of Western managers and business consultants that Japanese firms manage their suppliers primarily through strategic partnerships is unjustified. Not only do Japanese firms appear to conduct a far smaller proportion of their business through strategic partnerships than is commonly believed, but they also make extensive use of "market-exchange" relationships, in which either party can turn to the marketplace and shift to different business partners at will, a practice usually associated with Western manufacturers.`,
  topic: "business"
};

export const PASSAGE_008 = {
  id: "RC-OG-PASSAGE-008",
  title: "Executive Retention and Acquisition Outcomes",
  content: `In an effort to explain why business acquisitions often fail, scholars have begun to focus on the role of top executives of acquired companies. Acquired companies that retain their top executives tend to have more successful outcomes than those that do not. Furthermore, existing research suggests that retaining the highest-level top executives, such as the CEO (chief executive officer) and COO (chief operating officer), is related more positively to postacquisition success than retaining lower-ranked top executives. However, this explanation, while insightful, suffers from two limitations. First, the focus on positional rank does not recognize the variation in length of service that may exist in top executive posts across companies, nor does it address which particular top executives (with respect to length of service) should be retained to achieve a successful acquisition outcome. Second, the relationship between retained top executives and acquisition outcomes offered by existing research is subject to opposing theoretical explanations related to length of service. The resource-based view (RBV) suggests that keeping acquired company top executives with longer organizational tenure would lead to more successful outcomes, as those executives have idiosyncratic and nontransferable knowledge of the acquired company that would be valuable for the effective implementation of the acquisition. The opposing position, offered by the upper echelons perspective (UEP), suggests that retaining top executives having short organizational tenure would lead to more successful outcomes, as they would have the adaptability to manage most effectively during the uncertainty of the acquisition process.

Responding to these limitations, Bergh conducted a study of executive retention and acquisition outcome that focused on the organizational tenure of retained company top executives in 104 acquisitions, followed over 5 years. Bergh considered the acquisition successful if the acquired company was retained and unsuccessful if it was divested. Bergh's findings support the RBV position. Apparently, the benefits of long organizational tenure lead to more successful outcomes than the benefits of short organizational tenure. While longer-tenured top executives may have trouble adapting to change, it appears that their perspectives and knowledge bases offer unique value after the acquisition. Although from the UEP position it seems sensible to retain less-tenured executives and allow more-tenured ones to leave, such a strategy appears to lower the probability of acquisition success.`,
  topic: "business"
};

export const PASSAGE_009 = {
  id: "RC-OG-PASSAGE-009",
  title: "Marcus Garvey and African American Revitalization",
  content: `When Jamaican-born social activist Marcus Garvey came to the United States in 1916, he arrived at precisely the right historical moment. What made the moment right was the return of African American soldiers from the First World War in 1918, which created an ideal constituency for someone with Garvey's message of unity, pride, and improved conditions for African American communities.

Hoping to participate in the traditional American ethos of individual success, many African American people entered the armed forces with enthusiasm, only to find themselves segregated from white troops and subjected to numerous indignities. They returned to a United States that was as segregated as it had been before the war. Considering similar experiences, anthropologist Anthony F. C. Wallace has argued that when a perceptible gap arises between a culture's expectations and the reality of that culture, the resulting tension can inspire a revitalization movement: an organized, conscious effort to construct a culture that fulfills long-standing expectations.

Some scholars have argued that Garvey created the consciousness from which he built, in the 1920s, the largest revitalization movement in African American history. But such an argument only tends to obscure the consciousness of identity, strength, and sense of history that already existed in the African American community. Garvey did not create this consciousness; rather, he gave this consciousness its political expression.`,
  topic: "history"
};

export const PASSAGE_010 = {
  id: "RC-OG-PASSAGE-010",
  title: "Sloth Bears and Cub-Carrying Behavior",
  content: `The sloth bear, an insect-eating animal native to Nepal, exhibits only one behavior that is truly distinct from that of other bear species: The females carry their cubs (at least part time) until the cubs are about nine months old even though the cubs can walk on their own at six months. Cub-carrying also occurs among some other myrmecophagous (ant-eating) mammals; therefore, one explanation is cub-carrying is necessitated by myrmecophagy since myrmecophagy entails a low metabolic rate and high energy expenditure in walking between food patches. However, although polar bears' locomotion is similarly inefficient, polar bear cubs walk along with their mother. Furthermore, the daily movements of sloth bears and American black bears—which are similar in size to sloth bears and have similarly sized home ranges—reveal similar travel rates and distances, suggesting if black bear cubs are able to keep up with their mother, so too should sloth bear cubs.

An alternative explanation is defense from predation. Black bear cubs use trees for defense, whereas brown bears and polar bears, which regularly inhabit treeless environments, rely on aggression to protect their cubs. Like brown bears and polar bears (and unlike other myrmecophagous mammals, which are noted for their passivity), sloth bears are easily provoked to aggression. Sloth bears also have relatively large canine teeth, which appear to be more functional for fighting than for foraging. Like brown bears and polar bears, sloth bears may have evolved in an environment with few trees. They are especially attracted to food-rich grasslands; although few grasslands persist today on the Indian subcontinent, this type of habitat was once widespread there. Grasslands support high densities of tigers, which fight and sometimes kill sloth bears. Sloth bears also coexist with and have been killed by tree-climbing leopards and are often confronted and chased by rhinoceroses and elephants, which can topple trees. Collectively these factors probably selected against tree-climbing as a defensive strategy for sloth bear cubs. Because sloth bears are smaller than brown and polar bears and are under greater threat from dangerous animals, they may have adopted the extra precaution of carrying their cubs. Although cub-carrying may also be adaptive for myrmecophagous foraging, the behavior of sloth bear cubs, which climb on their mother's back at the first sign of danger, suggests that predation was a key stimulus.`,
  topic: "science"
};

export const PASSAGE_011 = {
  id: "RC-OG-PASSAGE-401",
  title: "Asteroid Rotation Rates and Structural Composition",
  content: `When asteroids collide, some collisions cause an asteroid to spin faster; others slow it down. If asteroids are all monoliths—single rocks—undergoing random collisions, a graph of their rotation rates should show a bell-shaped distribution with statistical "tails" of very fast and very slow rotators. If asteroids are rubble piles, however, the tail representing the very fast rotators would be missing, because any loose aggregate spinning faster than once every few hours (depending on the asteroid's bulk density) would fly apart. Researchers have discovered that all but five observed asteroids obey a strict limit on rate of rotation. The exceptions are all smaller than 200 meters in diameter, with an abrupt cutoff for asteroids larger than that.

The evident conclusion—that asteroids larger than 200 meters across are multicomponent structures or rubble piles—agrees with recent computer modeling of collisions, which also finds a transition at that diameter. A collision can blast a large asteroid to bits, but after the collision, those bits will usually move slower than their mutual escape velocity. Over several hours, gravity will reassemble all but the fastest pieces into a rubble pile. Because collisions among asteroids are relatively frequent, most large bodies have already suffered this fate. Conversely, most small asteroids should be monolithic, because impact fragments easily escape their feeble gravity.`,
  topic: "science"
};

export const PASSAGE_012 = {
  id: "RC-OG-PASSAGE-402",
  title: "Quantum Tunneling and Superluminal Particle Speeds",
  content: `Most attempts by physicists to send particles faster than the speed of light involve a remarkable phenomenon called quantum tunneling, in which particles travel through solid barriers that appear to be impenetrable. If you throw a ball at a wall, you expect it to bounce back, not to pass straight through it. Yet subatomic particles perform the equivalent feat. Quantum theory says that there is a distinct, albeit small, probability that such a particle will tunnel its way through a barrier; the probability declines exponentially as the thickness of the barrier increases. Though the extreme rapidity of quantum tunneling was noted as early as 1932, not until 1955 was it hypothesized—by Wigner and Eisenbud—that tunneling particles sometimes travel faster than light. Their grounds were calculations that suggested that the time it takes a particle to tunnel through a barrier increases with the thickness of the barrier until tunneling time reaches a maximum; beyond that maximum, tunneling time stays the same regardless of barrier thickness. This would imply that once maximum tunneling time is reached, tunneling speed will increase without limit as barrier thickness increases. Several recent experiments have supported this hypothesis that tunneling particles sometimes reach superluminal speed. According to measurements performed by Raymond Chiao and colleagues, for example, photons can pass through an optical filter at 1.7 times the speed of light.`,
  topic: "science"
};

export const PASSAGE_013 = {
  id: "RC-OG-PASSAGE-403",
  title: "Keystone Species and Ecosystem Context Dependency",
  content: `While the most abundant and dominant species within a particular ecosystem is often crucial in perpetuating the ecosystem, a "keystone" species, here defined as one whose effects are much larger than would be predicted from its abundance, can also play a vital role. But because complex species interactions may be involved, identifying a keystone species by removing the species and observing changes in the ecosystem is problematic. It might seem that certain traits would clearly define a species as a keystone species; for example, Pisaster ochraceus is often a keystone predator because it consumes and suppresses mussel populations, which in the absence of this starfish can be a dominant species. But such predation on a dominant or potentially dominant species occurs in systems that do as well as in systems that do not have species that play keystone roles. Moreover, whereas P. ochraceus occupies an unambiguous keystone role on wave-exposed rocky headlands, in more wave-sheltered habitats the impact of P. ochraceus predation is weak or nonexistent, and at certain sites sand burial is responsible for eliminating mussels. Keystone status appears to depend on context, whether of particular geography or of such factors as community diversity (for example, a reduction in species diversity may thrust more of the remaining species into keystone roles) and length of species interaction (since newly arrived species in particular may dramatically affect ecosystems).`,
  topic: "science"
};

export const PASSAGE_014 = {
  id: "RC-OG-PASSAGE-404",
  title: "Conodonts and the Evolution of Vertebrate Skeletons",
  content: `Conodonts, the spiky phosphatic remains (bones and teeth composed of calcium phosphate) of tiny marine animals that probably appeared about 520 million years ago, were once among the most controversial of fossils. Both the nature of the organism to which the remains belonged and the function of the remains were unknown. However, since the 1981 discovery of fossils preserving not just the phosphatic elements but also other remains of the tiny soft-bodied animals (also called conodonts) that bore them, scientists' reconstructions of the animals' anatomy have had important implications for hypotheses concerning the development of the vertebrate skeleton.

The vertebrate skeleton had traditionally been regarded as a defensive development, champions of this view postulating that it was only with the much later evolution of jaws that vertebrates became predators. The first vertebrates, which were soft-bodied, would have been easy prey for numerous invertebrate carnivores, especially if these early vertebrates were sedentary suspension feeders. Thus, traditionalists argued, these animals developed coverings of bony scales or plates, and teeth were secondary features, adapted from the protective bony scales. Indeed, external skeletons of this type are common among the well-known fossils of ostracoderms, jawless vertebrates that existed from approximately 500 to 400 million years ago.

However, other paleontologists argued that many of the definitive characteristics of vertebrates, such as paired eyes and muscular and skeletal adaptations for active life, would not have evolved unless the first vertebrates were predatory. Teeth were more primitive than external armor according to this view, and the earliest vertebrates were predators.

The stiffening notochord along the back of the body, V-shaped muscle blocks along the sides, and posterior tail fins help to identify conodonts as among the most primitive of vertebrates. The lack of any mineralized structures apart from the elements in the mouth indicates that conodonts were more primitive than the armored jawless fishes such as the ostracoderms. It now appears that the hard parts that first evolved in the mouth of an animal improved its efficiency as a predator, and that aggression rather than protection was the driving force behind the origin of the vertebrate skeleton.`,
  topic: "science"
};

export const PASSAGE_015 = {
  id: "RC-OG-PASSAGE-405",
  title: "American Patent System and Judicial Attitudes",
  content: `Because the framers of the United States Constitution (written in 1787) believed that protecting property rights relating to inventions would encourage the new nation's economic growth, they gave Congress—the national legislature—a constitutional mandate to grant patents for inventions. The resulting patent system has served as a model for those in other nations. Recently, however, scholars have questioned whether the American system helped achieve the framers' goals. These scholars have contended that from 1794 to roughly 1830, American inventors were unable to enforce property rights because judges were "antipatent" and routinely invalidated patents for arbitrary reasons. This argument is based partly on examination of court decisions in cases where patent holders ("patentees") brought suit alleging infringement of their patent rights. In the 1820s, for instance, 75 percent of verdicts were decided against the patentee.

The proportion of verdicts for the patentee began to increase in the 1830s, suggesting to these scholars that judicial attitudes toward patent rights began shifting then.

Not all patent disputes in the early nineteenth century were litigated, however, and litigated cases were not drawn randomly from the population of disputes. Therefore, the rate of verdicts in favor of patentees cannot be used by itself to gauge changes in judicial attitudes or enforceability of patent rights. If early judicial decisions were prejudiced against patentees, one might expect that subsequent courts—allegedly more supportive of patent rights—would reject the former legal precedents. But pre-1830 cases have been cited as frequently as later decisions, and they continue to be cited today, suggesting that the early decisions, many of which clearly declared that patent rights were a just recompense for inventive ingenuity, provided a lasting foundation for patent law.

The proportion of judicial decisions in favor of patentees began to increase during the 1830s because of a change in the underlying population of cases brought to trial. This change was partly due to an 1836 revision to the patent system: an examination procedure, still in use today, was instituted in which each application is scrutinized for its adherence to patent law. Previously, patents were automatically granted upon payment of a $30 fee.`,
  topic: "history"
};

export const PASSAGE_016 = {
  id: "RC-OG-PASSAGE-406",
  title: "Renaissance Women Writers and Feminist Scholarship",
  content: `Jacob Burckhardt's view that Renaissance European women "stood on a footing of perfect equality" with Renaissance men has been repeatedly cited by feminist scholars as a prelude to their presentation of rich historical evidence of women's inequality. In striking contrast to Burckhardt, Joan Kelly in her famous 1977 essay, "Did Women Have a Renaissance?" argued that the Renaissance was a period of economic and social decline for women relative both to Renaissance men and to medieval women. Recently, however, a significant trend among feminist scholars has entailed a rejection of both Kelly's dark vision of the Renaissance and Burckhardt's rosy one. Many recent works by these scholars stress the ways in which differences among Renaissance women—especially in terms of social status and religion—work to complicate the kinds of generalizations both Burckhardt and Kelly made on the basis of their observations about upper-class Italian women.

The trend is also evident, however, in works focusing on those middle- and upper-class European women whose ability to write gives them disproportionate representation in the historical record. Such women were, simply by virtue of their literacy, members of a tiny minority of the population, so it is risky to take their descriptions of their experiences as typical of "female experience" in any general sense. Tina Krontiris, for example, in her fascinating study of six Renaissance women writers, does tend at times to conflate "women" and "women writers," assuming that women's gender, irrespective of other social differences, including literacy, allows us to view women as a homogeneous social group and make that group an object of analysis. Nonetheless, Krontiris makes a significant contribution to the field and is representative of those authors who offer what might be called a cautiously optimistic assessment of Renaissance women's achievements, although she also stresses the social obstacles Renaissance women faced when they sought to raise their "oppositional voices." Krontiris is concerned to show women intentionally negotiating some power for themselves (at least in the realm of public discourse) against potentially constraining ideologies, but in her sober and thoughtful concluding remarks, she suggests that such verbal opposition to cultural stereotypes was highly circumscribed; women seldom attacked the basic assumptions in the ideologies that oppressed them.`,
  topic: "history"
};

export const PASSAGE_017 = {
  id: "RC-OG-PASSAGE-505",
  title: "Fish Schooling Theories and Predator Defense",
  content: `Biologists have advanced two theories to explain why schooling of fish occurs in so many fish species. Because schooling is particularly widespread among species of small fish, both theories assume that schooling offers the advantage of some protection from predators.

Proponents of theory A dispute the assumption that a school of thousands of fish is highly visible. Experiments have shown that any fish can be seen, even in very clear water, only within a sphere of 200 meters in diameter. When fish are in a compact group, the spheres of visibility overlap. Thus the chance of a predator finding the school is only slightly greater than the chance of the predator finding a single fish swimming alone. Schooling is advantageous to the individual fish because a predator's chance of finding any particular fish swimming in the school is much smaller than its chance of finding at least one of the same group of fish if the fish were dispersed throughout an area.

However, critics of theory A point out that some fish form schools even in areas where predators are abundant and thus little possibility of escaping detection exists. They argue that the school continues to be of value to its members even after detection. They advocate theory B, the "confusion effect," which can be explained in two different ways.

Sometimes, proponents argue, predators simply cannot decide which fish to attack. This indecision supposedly results from a predator's preference for striking prey that is distinct from the rest of the school in appearance. In many schools the fish are almost identical in appearance, making it difficult for a predator to select one. The second explanation for the "confusion effect" has to do with the sensory confusion caused by a large number of prey moving around the predator. Even if the predator makes the decision to attack a particular fish, the movement of other prey in the school can be distracting. The predator's difficulty can be compared to that of a tennis player trying to hit a tennis ball when two are approaching simultaneously.`,
  topic: "science"
};

export const PASSAGE_018 = {
  id: "RC-OG-PASSAGE-509",
  title: "Water Rights and American Indian Reservations",
  content: `In Winters v. United States (1908), the Supreme Court held that the right to use waters flowing through or adjacent to the Fort Berthold Indian Reservation was reserved to American Indians by the treaty establishing the reservation. Although this treaty did not mention water rights, the Court ruled that the federal government, when it created the reservation, intended to deal fairly with American Indians by reserving for them the waters without which their lands would have been useless. Later decisions, citing Winters, established that courts can find federal rights to reserve water for particular purposes if (1) the land in question lies within an enclave under exclusive federal jurisdiction; (2) the land has been formally withdrawn from federal public lands—i.e., withdrawn from the stock of federal lands available for private use under federal land use laws—and set aside or reserved; and (3) the circumstances reveal the government intended to reserve water as well as land when establishing the reservation.

Some American Indian tribes have also established water rights through the courts based on their traditional diversion and use of certain waters prior to the United States' acquisition of sovereignty. For example, the Rio Grande pueblos already existed when the United States acquired sovereignty over New Mexico in 1848. Although they at that time became part of the United States, the pueblo lands never formally constituted a part of federal public lands; in any event, no treaty, statute, or executive order has ever designated or withdrawn the pueblos from public lands as American Indian reservations. This fact, however, has not barred application of the Winters doctrine. What constitutes an American Indian reservation is a question of practice, not of legal definition, and the pueblos have always been treated as reservations by the United States. This pragmatic approach is buttressed by Arizona v. California (1963), wherein the Supreme Court indicated that the manner in which any type of federal reservation is created does not affect the application to it of the Winters doctrine. Therefore, the reserved water rights of Pueblo Indians have priority over other citizens' water rights as of 1848, the year in which pueblos must be considered to have become reservations.`,
  topic: "legal"
};

export const PASSAGE_019 = {
  id: "RC-OG-PASSAGE-515",
  title: "The Black Death Debate Among Historians",
  content: `The Black Death, a severe epidemic that ravaged fourteenth-century Europe, has intrigued scholars ever since Francis Gasquet's 1893 study contending that this epidemic greatly intensified the political and religious upheaval that ended the Middle Ages. Thirty-six years later, historian George Coulton agreed but, paradoxically, attributed a silver lining to the Black Death: Prosperity engendered by diminished competition for food, shelter, and work led survivors of the epidemic into the Renaissance and subsequent rise of modern Europe.

In the 1930s, however, Evgeny Kosminsky and other Marxist historians claimed the epidemic was merely an ancillary factor contributing to a general agrarian crisis stemming primarily from the inevitable decay of European feudalism. In arguing that this decline of feudalism was economically determined both Kosminsky and other Marxist historians asserted that the Black Death was a relatively insignificant factor. This became the prevailing view until after World War II, when studies of specific regions and towns revealed astonishing mortality rates ascribed to the epidemic, thus restoring the central role of the Black Death in history.

This central role of the Black Death (traditionally attributed to bubonic plague brought from Asia) has recently been challenged from another direction. Building on bacteriologist John Shrewsbury's speculations about mislabeled epidemics, zoologist Graham Twigg employs urban case studies suggesting the rat population in Europe was both too sparse and insufficiently migratory to have spread plague. Moreover, Twigg disputes the traditional trade-ship explanation for plague transmissions by extrapolating from data on the number of dead rats aboard Nile sailing vessels in 1912. The Black Death, which he conjectures was anthrax instead of bubonic plague, therefore caused far less havoc and fewer deaths than historians typically claim.

Although correctly citing the exacting conditions needed to start or spread bubonic plague, Twigg ignores virtually a century of scholarship contradictory to his findings and employs faulty logic in his single-minded approach to the Black Death. His speculative generalizations about the numbers of rats in medieval Europe are based on isolated studies unrepresentative of medieval conditions, while his unconvincing trade-ship argument overlooks land-based caravans, the overland migration of infected rodents, and the many other animals that carry plague.`,
  topic: "history"
};

export const PASSAGE_020 = {
  id: "RC-OG-PASSAGE-517",
  title: "Corporate Purchasing and Supplier Competitive Scrutiny",
  content: `In corporate purchasing, competitive scrutiny is typically limited to suppliers of items that are directly related to end products. With "indirect" purchases (such as computers, advertising, and legal services), which are not directly related to production, corporations often favor "supplier partnerships" (arrangements in which the purchaser forgoes the right to pursue alternative suppliers), which can inappropriately shelter suppliers from rigorous competitive scrutiny that might afford the purchaser economic leverage. There are two independent variables—availability of alternatives and ease of changing suppliers—that companies should use to evaluate the feasibility of subjecting suppliers of indirect purchases to competitive scrutiny. This can create four possible situations.

In Type 1 situations, there are many alternatives and change is relatively easy. Open pursuit of alternatives—by frequent competitive bidding, if possible—will likely yield the best results. In Type 2 situations, where there are many alternatives but change is difficult—as for providers of employee health care benefits—it is important to continuously test the market and use the results to secure concessions from existing suppliers. Alternatives provide a credible threat to suppliers, even if the ability to switch is constrained. In Type 3 situations, there are few alternatives, but the ability to switch without difficulty creates a threat that companies can use to negotiate concessions from existing suppliers. In Type 4 situations, where there are few alternatives and change is difficult, partnerships may be unavoidable.`,
  topic: "business"
};

export const PASSAGE_021 = {
  id: "RC-OG-PASSAGE-522",
  title: "Carotenoids and Mate Selection Signals",
  content: `Carotenoids, a family of natural pigments, form an important part of the colorful signals used by many animals. Animals acquire carotenoids either directly (from the plants and algae that produce them) or indirectly (by eating insects) and store them in a variety of tissues. Studies of several animal species have shown that when choosing mates, females prefer males with brighter carotenoid-based coloration. Owens and Olson hypothesize that the presence of carotenoids, as signaled by coloration, would be meaningful in the context of mate selection if carotenoids were either rare or required for health. The conventional view is that carotenoids are meaningful because they are rare: healthier males can forage for more of the pigments than can their inferior counterparts. Although this may be true, there is growing evidence that carotenoids are meaningful also because they are required: they are used by the immune system and for detoxification processes that are important for maintaining health.

It may be that males can use scarce carotenoids either for immune defense and detoxification or for attracting females. Males that are more susceptible to disease and parasites will have to use their carotenoids to boost their immune systems, whereas males that are genetically resistant will use fewer carotenoids for fighting disease and will advertise this by using the pigments for flashy display instead.`,
  topic: "science"
};
