// Passage content for reuse across multiple questions

export const PASSAGE_NIGHTINGALE = {
  id: "RC-PASSAGE-00001",
  title: "Florence Nightingale's Historical Significance",
  content: `Two recent publications offer different assessments of the career of the famous British nurse Florence Nightingale. A book by Anne Summers seeks to debunk the idealizations and present a reality at odds with Nightingale's heroic reputation. According to Summers, Nightingale's importance during the Crimean War has been exaggerated: not until near the war's end did she become supervisor of the female nurses. Additionally, Summers writes that the contribution of the nurses to the relief of the wounded was at best marginal. The prevailing problems of military medicine were caused by army organizational practices, and the addition of a few nurses to the medical staff could be no more than symbolic. Nightingale's place in the national pantheon, Summers asserts, is largely due to the propagandistic efforts of contemporary newspaper reporters.\nBy contrast, the editors of a new volume of Nightingale's letters view Nightingale as a person who significantly influenced not only her own age but also subsequent generations. They highlight her ongoing efforts to reform sanitary conditions after the war. For example, when she learned that peacetime living conditions in British barracks were so horrible that the death rate of enlisted men far exceeded that of neighboring civilian populations, she succeeded in persuading the government to establish a Royal Commission on the Health of the Army. She used sums raised through public contributions to found a nurses' training hospital in London. Even in administrative matters, the editors assert, her practical intelligence was formidable: as recently as 1947 the British Army's medical services were still using the cost-accounting system she had devised in the 1860's.\nI believe that the evidence of her letters supports continued respect for Nightingale's brilliance and creativity. When counseling a village schoolmaster to encourage children to use their faculties of observation, she sounds like a modern educator. Her insistence on classifying the problems of the needy in order to devise appropriate treatments is similar to the approach of modern social workers. In sum, although Nightingale may not have achieved all of her goals during the Crimean War, her breadth of vision and ability to realize ambitious projects have earned her an eminent place among the ranks of social pioneers.`,
  topic: "history"
};

export const PASSAGE_METEOR_STREAM = {
  id: "RC-PASSAGE-00002",
  title: "Meteor Streams and Computer Modeling",
  content: `A meteor stream is composed of dust particles that have been ejected from a parent comet at a variety of velocities. These particles follow the same orbit as the parent comet, but due to their differing velocities they slowly gain on or fall behind the disintegrating comet until a shroud of dust surrounds the entire cometary orbit. Astronomers have hypothesized that a meteor stream should broaden with time as the dust particles' individual orbits are perturbed by planetary gravitational fields. A recent computer-modeling experiment tested this hypothesis by tracking the influence of planetary gravitation over a projected 5,000-year period on the positions of a group of hypothetical dust particles. In the model, the particles were randomly distributed throughout a computer simulation of the orbit of an actual meteor stream, the Geminid. The researcher found, as expected, that the computer-model stream broadened with time. Conventional theories, however, predicted that the distribution of particles would be increasingly dense toward the center of a meteor stream. Surprisingly, the computer-model meteor stream gradually came to resemble a thick-walled, hollow pipe.\nWhenever the Earth passes through a meteor stream, a meteor shower occurs. Moving at a little over 1,500,000 miles per day around its orbit, the Earth would take, on average, just over a day to cross the hollow, computer-model Geminid stream if the stream were 5,000 years old. Two brief periods of peak meteor activity during the shower would be observed, one as the Earth entered the thick-walled "pipe" and one as it exited. There is no reason why the Earth should always pass through the stream's exact center, so the time interval between the two bursts of activity would vary from one year to the next.\nHas the predicted twin-peaked activity been observed for the actual yearly Geminid meteor shower? The Geminid data between 1970 and 1979 show just such a bifurcation, a secondary burst of meteor activity being clearly visible at an average of 19 hours (1,200,000 miles) after the first burst. The time intervals between the bursts suggest the actual Geminid stream is about 3,000 years old.`,
  topic: "science"
};

export const PASSAGE_TRADING_COMPANIES = {
  id: "RC-PASSAGE-00003",
  title: "Early Trading Companies and Modern Multinationals",
  content: `The modern multinational corporation is described as having originated when the owner-managers of nineteenth-century British firms carrying on international trade were replaced by teams of salaried managers organized into hierarchies. Increases in the volume of transactions in such firms are commonly believed to have necessitated this structural change. Nineteenth-century inventions like the steamship and the telegraph, by facilitating coordination of managerial activities, are described as key factors. Sixteenth- and seventeenth-century chartered trading companies, despite the international scope of their activities, are usually considered irrelevant to this discussion: the volume of their transactions is assumed to have been too low and the communications and transport of their day too primitive to make comparisons with modern multinationals interesting.\nIn reality, however, early trading companies successfully purchased and outfitted ships, built and operated offices and warehouses, manufactured trade goods for use abroad, maintained trading posts and production facilities overseas, procured goods for import, and sold those goods both at home and in other countries. The large volume of transactions associated with these activities seems to have necessitated hierarchical management structures well before the advent of modern communications and transportation. For example, in the Hudson's Bay Company, each far-flung trading outpost was managed by a salaried agent, who carried out the trade with the Native Americans, managed day-to-day operations, and oversaw the post's workers and servants. One chief agent, answerable to the Court of Directors in London through the correspondence committee, was appointed with control over all of the agents on the bay.\nThe early trading companies did differ strikingly from modern multinationals in many respects. They depended heavily on the national governments of their home countries and thus characteristically acted abroad to promote national interests. Their top managers were typically owners with a substantial minority share, whereas senior managers' holdings in modern multinationals are usually insignificant. They operated in a preindustrial world, grafting a system of capitalist international trade onto a premodern system of artisan and peasant production. Despite these differences, however, early trading companies organized effectively in remarkably modern ways and merit further study as analogues of more modern structures.`,
  topic: "economics"
};

export const PASSAGE_TRADE_PROMOTIONS = {
  id: "RC-PASSAGE-00004",
  title: "Trade Promotions and Retailer Opportunism",
  content: `A primary concern among manufacturers polled in a 1998 survey was the inefficiency of trade promotions—inducements offered by manufacturers to retailers to encourage them to reduce retail prices temporarily so as to boost sales volume. Such inducements may include temporarily reduced costs of goods, free goods, or display allowances (fees manufacturers pay retailers to encourage them to allocate premium shelf space to a product). At the heart of manufacturers' dissatisfaction lies concern regarding widespread retailer opportunism. Although consumers know from experience the approximate frequency of promotional pricing, they do not typically have complete information about ongoing trade promotions in a given period, so retailers can profit by sometimes choosing not to pass along their own savings to their customers. Inefficient use of trade promotion dollars has prompted several large manufacturers to adopt an "everyday low price" policy for their goods, but at least one diaper manufacturer found it had to revert to its former pricing strategies in the face of increasing promotional competition from other brands. Adopting an alternative approach, some manufacturers have themselves advertised ongoing promotions. By informing at least some customers about promotions, manufacturers believe they can regulate retailer opportunism by increasing customers' propensity to search for discounted prices.`,
  topic: "business"
};

export const PASSAGE_CARBON_WOODLANDS = {
  id: "RC-PASSAGE-00005",
  title: "Carbon and the Northern Woodlands",
  content: `Atmospheric carbon dioxide (CO_2) has been increasing since 1700, but the amount of CO_2 produced in that time by burning fossil fuels should have resulted in a much greater increase than has been observed. Plant ecologist Allen Auclair claims that the woodlands of the Northern Hemisphere have been acting as a carbon sink, absorbing carbon from the atmosphere and turning it into wood. Auclair uses measurements of factors affecting the area and density of a forest—such as logging, fires, and pests—and estimates of tree growth rates to argue that increases in the growth rates of individual trees in these forests since 1920 have created a large volume of wood that accounts for the missing carbon.
To determine whether the woodlands as a whole are releasing or absorbing carbon, the volume of wood added to the woodlands must be compared with the wood lost. Auclair's analysis of the past hundred years shows the woodlands changing from a carbon source to a carbon sink. Before 1890, northern woodlands were a source of CO_2 mainly because of forest fires and logging. Such deforestation releases CO_2 because debris from the forest floor rots more quickly when the trees are cleared. After 1920, the steep increase in tree growth rates surpassed the losses stemming from fire and logging, turning the northern forests from a carbon source into a carbon sink and storing CO_2 from fossil fuel over the next fifty years.`,
  topic: "science"
};

export const PASSAGE_ANCIENT_DNA = {
  id: "RC-PASSAGE-00006",
  title: "Ancient DNA Research",
  content: `Research directed toward recovering ancient DNA began in 1984, when pieces of DNA were extracted from museum specimens of an animal extinct for about a century. Most such genetic material recovered from biological relics consists of tiny fragments, rather than the strings of thousands of molecules typically found in living organisms, but these fragments may contain sufficient information to identify a species through comparison with modern DNA from descendant species. However, the need to verify whether particular fragments actually come from ancient organisms or whether they come from modern contaminants, such as the sweat of people who have handled the specimens, is crucial. For example, some scientists claim to have extracted DNA fragments from 17-million-year-old magnolia leaves found in an unusual fossil deposit in Idaho. But other scientists suggest that this DNA is a modern contaminant; they argue that even under the most favorable conditions, the rate of degradation of DNA is such that useful genetic material could not be recovered from fossils that old and that since the leaves were trapped in wet deposits, it is particularly unlikely that any DNA would have survived so long. A solution to this debate lies in the fact that any ancient DNA should differ from that of related modern species. If the DNA extracted from the fossil leaves were actually a modern contaminant, this fact would be apparent from the information contained in the DNA.`,
  topic: "science"
};

export const PASSAGE_FUNGUS_MIMICRY = {
  id: "RC-PASSAGE-00007",
  title: "Fungus Mimicry in Plants",
  content: `In the late nineteenth century, the highly esteemed Italian botanist Arcangeli made a claim that at that time was considered "unbelievable" but that has been verified by subsequent research. It concerned the curious little arum lily Arisarum proboscideum, known as the mousetail plant. Its flower cluster develops inside a cylindrical, vertical chamber whose upper part is bent over and ends in a dark-colored, slender, drawn-out, and curved tip, the "mousetail." The chamber is completely closed except for an elliptical window that faces earthward.
A small flying insect, coming up from the forest floor and entering the chamber through the window, is immediately confronted by the flower cluster's appendix—a structure that extends into the bent part, well above the flowers that make up the cluster. In this case the appendix is not hard and smooth as it is in many arum lilies but spongy and full of little depressions. It is also off-white in color so that the overall visual impression it gives is deceptively like that of the underside of the cap of a Boletus mushroom. Arcangeli claimed that the plant's pollinators were fungus gnats—insects that normally breed in decaying mushrooms. The mousetail plant fools them so successfully that the females deposit their eggs—which will not be able to survive—on the appendix. Before the gnats can find their way out of the chamber, they also accidentally contact the flowers, transferring pollen.
Fungus mimicry turns out to be a fairly widespread pollination strategy. Most of the fungus mimics are forest dwellers, which remain close to the ground and produce dark purple or brown flowers with pale or translucent patterns. To the human nose at least they are either scentless or musky in odor. Usually the flowers are simple urn- or kettle-shaped traps containing structures that closely resemble the gills or pores of mushrooms. Another element in their fungus mimicry is their exudation of moisture during the period when the flower is active. Fungus gnats of both sexes are involved in the pollination and are misled by a combination of fungus-like features—odor, color, shape, texture, and humidity.`,
  topic: "science"
};
