import {
  VerbalReasoningQuestion,
  VRQuestionData,
  generateMCAnswers,
} from "../types";
import {
  PASSAGE_001,
  PASSAGE_002,
  PASSAGE_003,
  PASSAGE_004,
  PASSAGE_005,
  PASSAGE_006,
  PASSAGE_020,
  PASSAGE_021,
} from "./passages_OG";

export const verbalReasoningQuestionsOG_RC_Medium: VerbalReasoningQuestion[] = [
  {
    id: "VR-GMAT-OG__-00517",
    question_number: 517,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Which of the following can be inferred about supplier partnerships, as they are described in the passage?",
      options: {
        a: "They cannot be sustained unless the goods or services provided are available from a large number of suppliers.",
        b: "They can result in purchasers paying more for goods and services than they would in a competitive-bidding situation.",
        c: "They typically are instituted at the urging of the supplier rather than the purchaser.",
        d: "They are not feasible when the goods or services provided are directly related to the purchasers' end products.",
        e: "They are least appropriate when the purchasers' ability to change suppliers is limited."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_020.id,
      passage_text: PASSAGE_020.content,
    } as VRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "According to the passage, in supplier partnerships a corporate purchaser forgoes the right to pursue alternative suppliers for certain goods or services. This tends to reduce or eliminate the threat of competition for the supplier in the partnership. It can be inferred that the corporate purchaser in a supplier partnership risks paying more for goods or services than it would if the supplier had to compete for the business. The passage indicates that supplier partnerships, by definition, reduce the supplier's exposure to competition, and it can be inferred from this that a purchaser in such a partnership could sometimes pay more for the supplied goods or services than if not in the partnership.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00518",
    question_number: 518,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Which of the following best describes the relation of the second paragraph to the first?",
      options: {
        a: "The second paragraph offers proof of an assertion made in the first paragraph.",
        b: "The second paragraph provides an explanation for the occurrence of a situation described in the first paragraph.",
        c: "The second paragraph discusses the application of a strategy proposed in the first paragraph.",
        d: "The second paragraph examines the scope of a problem presented in the first paragraph.",
        e: "The second paragraph discusses the contradictions inherent in a relationship described in the first paragraph."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_020.id,
      passage_text: PASSAGE_020.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "The first paragraph recommends that a corporate purchaser of certain categories of goods and services should consider two variables to evaluate how, if at all, it might exert pressure on a supplier to gain economic advantage. Applying the two variables, the second paragraph identifies four different scenarios and, for each scenario, explains how the purchaser can gain some economic advantage. The first paragraph recommends that corporate purchasers consider two variables in analyzing the feasibility of exerting pressure on suppliers with a view to gaining economic advantage; the second paragraph shows how purchasers can apply those variables to identify four different types of situations affecting the degree to which economic advantage can be gained by exerting competitive pressure.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00519",
    question_number: 519,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "It can be inferred that the author of the passage would be most likely to make which of the following recommendations to a company purchasing health care benefits for its employees?",
      options: {
        a: "Devise strategies for circumventing the obstacles to replacing the current provider of health care benefits.",
        b: "Obtain health care benefits from a provider that also provides other indirect products and services.",
        c: "Obtain bids from other providers of health care benefits in order to be in a position to negotiate a better deal with the current provider.",
        d: "Switch providers of health care benefits whenever a different provider offers a more competitive price.",
        e: "Acknowledge the difficulties involved in replacing the current provider of health care benefits and offer to form a partnership with the provider."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_020.id,
      passage_text: PASSAGE_020.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "In the passage, health care benefits are used as an example of a Type 2 situation, where there are many competing providers but changing from one provider to another is difficult. In Type 2 situations, the author of the passage recommends that the corporate purchaser examine the alternative providers to provide leverage in bargaining with the existing provider. The recommendation offered in the passage is to review competitive alternatives to the existing provider, with a view to bargaining effectively for better terms with the existing provider.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00520",
    question_number: 520,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Which of the following is one difference between Type 2 situations and Type 4 situations, as they are described in the passage?",
      options: {
        a: "The number of alternative suppliers available to the purchaser",
        b: "The most effective approach for the purchaser to use in obtaining competitive bids from potential suppliers",
        c: "The degree of difficulty the purchaser encounters when changing suppliers",
        d: "The frequency with which each type of situation occurs in a typical business environment",
        e: "The likelihood that any given purchase will be an indirect purchase"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_020.id,
      passage_text: PASSAGE_020.content,
    } as VRQuestionData,
    answers: generateMCAnswers("a"),
    explanation: "According to the passage, Type 2 situations are those where there are several competitive alternative suppliers available but changing from the existing supplier would be difficult. Type 4 situations are those where there are few competitive alternative suppliers and changing from the existing supplier would be difficult. The two types of situations differ in the number of competitive alternatives to the existing supplier that are available: in Type 2 situations there are several; in Type 4 situations there are few.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00521",
    question_number: 521,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "According to the passage, which of the following factors distinguishes an indirect purchase from other purchases?",
      options: {
        a: "The ability of the purchasing company to subject potential suppliers of the purchased item to competitive scrutiny",
        b: "The number of suppliers of the purchased item available to the purchasing company",
        c: "The methods of negotiation that are available to the purchasing company",
        d: "The relationship of the purchased item to the purchasing company's end product",
        e: "The degree of importance of the purchased item in the purchasing company's business operations"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_020.id,
      passage_text: PASSAGE_020.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "The passage characterizes a purchase of goods or services as indirect when the goods or services are not directly related to the end products of the purchasing corporation. Examples given are computers, advertising, and legal services. By implication, direct purchases by an automobile manufacturer could include steel, batteries, and tires: these would obviously be inputs embodied in the final products. The passage defines direct purchases as those directly related to the purchasing firm's end products; indirect purchases are purchases that are not related to the end products.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00522",
    question_number: 522,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "According to the \"conventional view\" referred to in line 13 of the passage, brighter carotenoid-based coloration in certain species suggests that an individual",
      options: {
        a: "lives in a habitat rich in carotenoid-bearing plants and insects",
        b: "has efficient detoxification processes",
        c: "has a superior immune system",
        d: "possesses superior foraging capacity",
        e: "is currently capable of reproducing"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_021.id,
      passage_text: PASSAGE_021.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "According to the \"conventional view\" referred to in line 13 of the passage, brighter carotenoid-based coloration in certain species suggests that an individual has efficient detoxification processes, has a superior immune system, possesses superior foraging capacity, or is currently capable of reproducing. The passage represents the conventional view as holding that more brightly colored males seem to females to be more effective foragers, and therefore healthier.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00523",
    question_number: 523,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The idea that carotenoid-based coloration is significant partly because carotenoids are required for health suggests that a lack of bright coloration in a male is most likely to indicate which of the following?",
      options: {
        a: "Inefficient detoxification processes",
        b: "Immunity to parasite infestation",
        c: "Low genetic resistance to disease",
        d: "Lack of interest in mating",
        e: "Lack of carotenoid-storing tissues"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_021.id,
      passage_text: PASSAGE_021.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "The passage states that carotenoids are used by the immune system and for detoxification processes that help maintain health. Males that are more susceptible to disease and parasites, i.e., males that lack high genetic resistance to such things, must use up the carotenoids they accumulate to boost their immune systems. The passage suggests that consequently, male animals perceived by females of the species as having used up their carotenoids would be perceived as having relatively low genetic resistance to disease and parasites. The passage indicates that a male's having relatively bright coloration could indicate relatively high genetic resistance to disease, and having relatively less bright coloration could indicate relatively low genetic resistance, because the carotenoids that create bright coloration would have been used to boost immunity or aid detoxification processes.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00524",
    question_number: 524,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The passage suggests that relatively bright carotenoid-based coloration is a signal of which of the following characteristics in males of certain animal species?",
      options: {
        a: "Readiness for mating behavior",
        b: "Ability to fight",
        c: "Particular feeding preferences",
        d: "Recovery from parasite infestation",
        e: "Fitness as a mate"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_021.id,
      passage_text: PASSAGE_021.content,
    } as VRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "According to the passage, studies of several animal species have shown that when choosing mates, females prefer males with brighter, carotenoid-based coloration. The passage examines two mechanisms by which carotenoid-based coloration might affect mate selection: either signaling good health or signaling high genetic resistance to infection. It is implicit in the discussion that whichever mechanism is in question, bright coloration would function to signal fitness as a mate. The passage discussion indicates that, whatever the precise mechanism, bright carotenoid-based coloration in males of certain species functions to signal fitness as a mate.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00525",
    question_number: 525,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The passage implies which of the following about the insects from which animals acquire carotenoids?",
      options: {
        a: "They do not produce carotenoids themselves.",
        b: "They use carotenoids primarily for coloration.",
        c: "They maintain constant levels of carotenoids in their tissues.",
        d: "They are unable to use carotenoids to boost their immune system.",
        e: "They are available in greater abundance than are carotenoid-bearing plants."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_021.id,
      passage_text: PASSAGE_021.content,
    } as VRQuestionData,
    answers: generateMCAnswers("a"),
    explanation: "The passage says that animals acquire carotenoids either directly (from the plants and algae that produce them) or indirectly (by eating insects). The passage indicates that the phrase acquire . . . directly signifies in this context acquisition from the ultimate source of carotenoids, so the phrase acquire . . . indirectly signifies an acquisition that is not from the ultimate source. This implies that insects do not produce their own carotenoids, but rather derive them by consuming plants, algae, or other insects.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00526",
    question_number: 526,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Information in the passage suggests that which of the following is true of carotenoids that a male animal uses for detoxification processes?",
      options: {
        a: "They were not acquired directly from plants and algae.",
        b: "They cannot be replenished through foraging.",
        c: "They cannot be used simultaneously to brighten coloration.",
        d: "They do not affect the animal's susceptibility to parasites.",
        e: "They increase the chances that the animal will be selected as a mate."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_021.id,
      passage_text: PASSAGE_021.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "The passage states that carotenoids are used by the immune system and for detoxification processes. To the extent that any carotenoids are used for these purposes, the passage suggests, they would not also be available for bright-colored display to potential mates. The passage implies that the quantity of carotenoids used for detoxification is no longer available for any other purpose, such as display of bright coloration.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00527",
    question_number: 527,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "According to the passage, Kerber maintained that which of the following led to an increase in educational opportunities for women in the United States after the American Revolution?",
      options: {
        a: "An unprecedented demand by women for greater educational opportunities in the decades following the Revolution",
        b: "A new political ideology calling for equality of opportunity between women and men in all aspects of life",
        c: "A belief that the American educational system could be reformed only if women participated more fully in that system",
        d: "A belief that women needed to be educated if they were to contribute to the success of the nation's new form of government",
        e: "A recognition that women needed to be educated if they were to take an active role in the nation's schools and churches"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_001.id,
      passage_text: PASSAGE_001.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "The passage ascribes to Linda Kerber the claim that there was a surge of educational opportunities for women in the United States after the American Revolution, and that this surge resulted from a new ideology of \\\"republican motherhood.\\\" According to the passage, Kerber argued that the nation's leaders advocated education for women to equip them, in their family role, to raise politically virtuous sons. According to the passage, Kerber argued that educational opportunities for women increased because the nation's leaders believed that successful democratic government would require that women raise politically virtuous sons within their families, and that women could do so only if they had access to education themselves.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00528",
    question_number: 528,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "According to the passage, within the field of educational history, Thomas Woody's 1929 work was",
      options: {
        a: "innovative because it relied on newspaper advertisements as evidence",
        b: "exceptional in that it concentrated on the period before the American Revolution",
        c: "unusual in that it focused on educational attitudes rather than on educational practices",
        d: "controversial in its claims regarding educational opportunities for boys",
        e: "atypical in that it examined the education of girls"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_001.id,
      passage_text: PASSAGE_001.content,
    } as VRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "According to the passage, within the field of educational history, Thomas Woody's 1929 work was a notable exception as contrast to the work of other educational historians, who barely mentioned women and girls. As stated above, the passage describes Woody's work as a notable exception, i.e., atypical, with respect to his discussion of education for girls.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00529",
    question_number: 529,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The passage suggests that Woody would have agreed with which of the following claims regarding \"An Essay on Woman\"?",
      options: {
        a: "It expressed attitudes concerning women's education that were reflected in new educational opportunities for women after 1750.",
        b: "It persuaded educators to offer greater educational opportunities to women in the 1750s.",
        c: "It articulated ideas about women's education that would not be realized until after the American Revolution.",
        d: "It offered one of the most original arguments in favor of women's education in the United States in the eighteenth century.",
        e: "It presented views about women's education that were still controversial in Woody's own time."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_001.id,
      passage_text: PASSAGE_001.content,
    } as VRQuestionData,
    answers: generateMCAnswers("a"),
    explanation: "According to the passage, Woody characterized \\\"An Essay on Woman\\\" (1753) as reflecting a shift in view, and the context indicates that this shift concerned new attitudes that accompanied increased opportunities after 1750 for girls to become educated women. Based on the passage, this is a claim with which Woody would likely have agreed.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00530",
    question_number: 530,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The passage suggests that, with regard to the history of women's education in the United States, Kerber's work differs from Woody's primarily concerning which of the following?",
      options: {
        a: "The extent to which women were interested in pursuing educational opportunities in the eighteenth century",
        b: "The extent of the support for educational opportunities for girls prior to the American Revolution",
        c: "The extent of public resistance to educational opportunities for women after the American Revolution",
        d: "Whether attitudes toward women's educational opportunities changed during the eighteenth century",
        e: "Whether women needed to be educated in order to contribute to the success of a republican form of government"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_001.id,
      passage_text: PASSAGE_001.content,
    } as VRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "The passage represents Kerber as claiming that the American Revolution led to a surge in educational opportunities for women because the nation's leaders believed women needed to be educated if they were to raise politically virtuous sons. Woody, however, is represented as claiming that there was a significant increase in such opportunities and significant advocacy for women's education well before the Revolution. The passage attributes to Woody the view that practical education for females had many advocates before the Revolution, notably in the 1750s, and that the Revolution at most accelerated an earlier trend of changing attitudes. This is contrary to the views attributed to Kerber.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00531",
    question_number: 531,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "According to the passage, Kerber argued that political leaders thought that the form of government adopted by the United States after the American Revolution depended on which of the following for its success?",
      options: {
        a: "Women assuming the sole responsibility for instilling political virtue in children",
        b: "Girls becoming the primary focus of a reformed educational system that emphasized political virtue",
        c: "The family serving as one of the primary means by which children were imbued with political virtue",
        d: "The family assuming many of the functions previously performed by schools and churches",
        e: "Men and women assuming equal responsibility for the management of schools, churches, and the family"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_001.id,
      passage_text: PASSAGE_001.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "The passage attributes to Kerber the claim that the nation's leaders believed a virtuous citizenry was essential to the success of the nation's republican form of government, and that women would play a primary role in raising future citizens who would be politically virtuous. Kerber argues that political leaders emphasized the family as the primary means by which future citizens would be imbued with political virtue.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00532",
    question_number: 532,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "It can be inferred from the passage that geologists today would be most likely to agree with which of the following statements about Wegener's The Origin of Continents and Oceans?",
      options: {
        a: "It was a worthy scientific effort that was ahead of its time.",
        b: "It was based on evidence that was later disproved.",
        c: "It was directly responsible for the acceptance of the theory of plate tectonics.",
        d: "It has been disproved by continental drift theory.",
        e: "It misrepresented how horizontal displacements cause the formation of mountain chains."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_002.id,
      passage_text: PASSAGE_002.content,
    } as VRQuestionData,
    answers: generateMCAnswers("a"),
    explanation: "Notice what is asserted in the passage's first paragraph about the attitudes or beliefs of today's geologists. We read that most geologists today consider Wegener's book \"an impressive and prescient document\" because its ideas significantly overlap with those of plate tectonics, the theory now accepted by most geologists today. But the passage stops short of attributing the development of plate tectonics to Wegener's ideas, which were widely rejected by Wegener's peer geologists. The passage tells us that today's geologists find Wegener's book to be impressive, i.e., respectable as a work of science, as well as \"prescient,\" i.e., it anticipated some of the key assumptions of plate tectonics.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00533",
    question_number: 533,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The author of the passage suggests the most likely explanation for the geological community's response to continental drift theory in its day was that the theory",
      options: {
        a: "was in conflict with certain aspects of plate tectonics theory",
        b: "failed to account for how mountains were formed",
        c: "did not adequately explain how continents moved through the ocean floor",
        d: "was contradicted by the geophysical data of the time",
        e: "was based on a kind of evidence that was considered insufficiently convincing"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_002.id,
      passage_text: PASSAGE_002.content,
    } as VRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "Why did Wegener's scientific peers reject his continental drift theory? In the passage's second paragraph, the author suggests that the most likely cause was \"the nature of the evidence\" Wegener offered in support of it. Wegener's evidence was derived from \"direct observations of rocks in the field\" using simple tools such as hammers and hand lenses, whereas plate tectonics used technically sophisticated instruments. The passage contrasts the kind of data related to \"similarities of patterns and forms\" with the more precise kind of data that plate tectonics collected. Wegener's data was collected using hammers and hand lenses, whereas the data collected by plate tectonics used technical instruments. This difference is offered to explain why Wegener's peers found his data less convincing. According to the author, this likely led to their rejection of continental drift theory.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00534",
    question_number: 534,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The author of the passage probably refers to the \"considerable overlap\" (see line 18) between the continental drift theory and plate tectonics theory in order to",
      options: {
        a: "suggest that plate tectonics theory is derived from Wegener's work",
        b: "introduce a discussion comparing the elements of the two theories",
        c: "examine the question of whether continental drift theory was innovative in its time",
        d: "provide a reason why it might seem surprising that continental drift theory was not more widely embraced by geologists",
        e: "cite an explanation that has been frequently offered for Wegener's high standing among geologists today"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_002.id,
      passage_text: PASSAGE_002.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "The sentence in line 18 has the following structure: Despite X and despite Y, what occurred was Z. The point being made is that it was surprising that Z occurred when X and Y would have led us to expect that Z would not occur. More concretely: Despite continental drift's overlap with plate tectonics and its initially plausible explanation for the origin of mountains, it was surprising that Wegener's peer geologists largely rejected continental drift theory. See the introductory analysis above. The sentence in line 18 provides two reasons why one would expect that continental drift theory would have gained acceptance among Wegener's peer geologists. Surprisingly, it did not.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00535",
    question_number: 535,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The author cites Hallam (see line 32) on the ice ages primarily in order to",
      options: {
        a: "provide an example of a geologic phenomenon with precise causes that are not fully understood by geologists today",
        b: "criticize the geological community for an apparent lack of consistency in its responses to new theories",
        c: "offer evidence held to undermine a common view of why Wegener's theory was not accepted in its day",
        d: "give an example of a modern scientist who believes Wegener's theory was rejected because it failed to adequately explain the mechanical basis of continental drift",
        e: "support some researchers' rationale for why Wegener's theory was rejected by most geologists in the early twentieth century"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_002.id,
      passage_text: PASSAGE_002.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "The point attributed to Hallam is that the acceptance of a new scientific phenomenon by the scientific community has often not required that the phenomenon have a satisfactory explanation provided for it. What is the author's purpose in citing this point? The point immediately precedes this one is that most of today's geologists and historians of science believe that Wegener's continental drift theory was rejected because it was deficient in explaining some of the phenomena it cited. The author disagrees with this view and cites Hallam as evidence to counter this widely held view of why Wegener's theory was not accepted by his contemporaries in geology. The purpose of the citation of Hallam is to help show the inadequacy of a widely accepted historical explanation concerning the nonacceptance of Wegener's theory by his contemporaries.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00536",
    question_number: 536,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The author of the passage most likely discusses the \"essential presumptions\" (see lines 12-13) of The Origin of Continents and Oceans in order to",
      options: {
        a: "indicate features of Wegener's theory that caused it to be doubted in its day",
        b: "show why Wegener's theory is now regarded as prescient",
        c: "indicate differences between plate tectonics and the theory of continental drift",
        d: "cite features of the theory of continental drift for which no evidence was available in Wegener's day",
        e: "point out aspects of Wegener's theory that were accepted well before the advent of plate tectonics"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_002.id,
      passage_text: PASSAGE_002.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "According to the passage, Wegener's book is regarded as \\\"prescient\\\" by most geologists today. This point is supported by detailing three \\\"essential presumptions\\\" of Wegener's theory that are shared by plate tectonics. Thus, the author aims to show that most geologists see Wegener's theory as anticipating, in some important respects, the scientific advances achieved by plate tectonics. The context of the phrase \\\"essential presumptions\\\" indicates that the author's purpose is to show how Wegener anticipated some of the important ideas in plate tectonics and was therefore prescient.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00537",
    question_number: 537,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The passage suggests that in order for a manufacturer in a capital-intensive industry to have a decisive advantage over competitors making similar products, the manufacturer must",
      options: {
        a: "be the first in the industry to build production facilities of theoretically optimal size",
        b: "make every effort to keep fixed and sunk costs as low as possible",
        c: "be one of the first to operate its manufacturing plants at minimum efficient scale",
        d: "produce goods of higher quality than those produced by direct competitors",
        e: "stockpile raw materials at production sites in order to ensure a steady flow of such materials"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_003.id,
      passage_text: PASSAGE_003.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "This question asks for an inference about what a manufacturer in a capital-intensive industry must do to have an advantage over competitors making similar products. The passage discusses this question by stating that advantage accrues to those firms that are the first to exploit the full potential of optimally sized, technologically sophisticated plants. In this context, exploiting the full potential of such plants means operating them at minimum efficient scale. Based on the definition in the first paragraph, this means that the plant must have an output of such a size that the cost per unit of output is at a minimum. Being among the first manufacturers to operate plants at minimum efficient scale means that those plants are being exploited to their full potential. This strategy would most likely give such manufacturers a decisive advantage over new firms hoping to compete effectively.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00538",
    question_number: 538,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The passage suggests that which of the following is true of a manufacturer's fixed and sunk costs?",
      options: {
        a: "The extent to which they are determined by market conditions for the goods being manufactured is frequently underestimated.",
        b: "If they are kept as low as possible, the manufacturer is very likely to realize significant profits.",
        c: "They are the primary factor that determines whether a manufacturer will realize economies of scale.",
        d: "They should be on a par with the fixed and sunk costs of the manufacturer's competitors.",
        e: "They are not affected by fluctuations in a manufacturing plant's throughput."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_003.id,
      passage_text: PASSAGE_003.content,
    } as VRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "This question asks about what the passage implies about fixed and sunk costs. The passage states that when production declines due to certain factors, such costs remain at the same level (which may be high), and the cost per unit produced (unit costs) rises sharply. According to the passage, throughput refers to the flow of materials through a plant. This flow can vary as a result of various factors, but fixed and sunk costs—financial resources already committed—remain the same regardless of such variation.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00539",
    question_number: 539,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "In the context of the passage as a whole, the second paragraph serves primarily to",
      options: {
        a: "provide an example to support the argument presented in the first paragraph",
        b: "evaluate various strategies discussed in the first paragraph",
        c: "introduce evidence that undermines the argument presented in the first paragraph",
        d: "anticipate possible objections to the argument presented in the first paragraph",
        e: "demonstrate the potential dangers of a commonly used strategy"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_003.id,
      passage_text: PASSAGE_003.content,
    } as VRQuestionData,
    answers: generateMCAnswers("a"),
    explanation: "This question asks about the rhetorical function of the second paragraph. While the first paragraph argues that a crucial factor in achieving economies of scale is intangible capital, or organized human capabilities, the second paragraph uses the example of new capital-intensive manufacturing industries to help show that this is indeed the case. The second paragraph provides an example that illustrates the claims made in the first paragraph. It discusses the way in which intangible capital—e.g., distribution networks, marketing systems, smooth production processes, and qualified management teams—enables manufacturers in new capital-intensive manufacturing industries to realize economies of scale and achieve market dominance.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00540",
    question_number: 540,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The passage LEAST supports the inference that a manufacturer's throughput could be adversely affected by",
      options: {
        a: "a mistake in judgment regarding the selection of a wholesaler",
        b: "a breakdown in the factory's machinery",
        c: "a labor dispute on the factory floor",
        d: "an increase in the cost per unit of output",
        e: "a drop in the efficiency of the sales network"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_003.id,
      passage_text: PASSAGE_003.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "This question may be best approached by using an elimination strategy—first finding the four choices that can reasonably be inferred from the passage, and then checking to make sure that the remaining choice cannot reasonably be inferred. This requires understanding the information the passage gives about throughput, then making inferences about what can cause throughput to drop. The passage defines throughput generally as the flow of materials through a plant and goes on to explain that it involves coordination of the production process itself, as well as obtaining materials from suppliers and marketing and distributing the manufactured products. Anything that damages this flow of materials and products would be said to have an adverse effect on throughput. The passage emphasizes that changes in throughput can cause increases or decreases in costs per unit. But the passage is not committed to any claims about how changes in costs per unit might affect throughput.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00541",
    question_number: 541,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The primary purpose of the passage is to",
      options: {
        a: "point out the importance of intangible capital for realizing economies of scale in manufacturing",
        b: "show that manufacturers frequently gain a competitive advantage from investment in large manufacturing facilities",
        c: "argue that large manufacturing facilities often fail because of inadequate investment in both tangible and intangible capital",
        d: "suggest that most new industries are likely to be dominated by firms that build large manufacturing plants early",
        e: "explain why large manufacturing plants usually do not help manufacturers achieve economies of scale"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_003.id,
      passage_text: PASSAGE_003.content,
    } as VRQuestionData,
    answers: generateMCAnswers("a"),
    explanation: "This question depends on understanding the passage as a whole. In general, it makes an argument for investing in intangible capital as a way for manufacturers to realize economies of scale, and it supports its argument with an example. The passage focuses on intangible capital as a crucial factor in realizing economies of scale.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00542",
    question_number: 542,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "According to the passage, which of the following is true of plant antiherbivore chemistry?",
      options: {
        a: "Changes in a plant's antiherbivore chemistry may affect insect feeding behavior.",
        b: "A plant's repellent effects often involve interactions between gum and resin.",
        c: "A plant's antiherbivore responses assist in combating bacterial infections.",
        d: "Plant antiherbivore chemistry plays only a minor role in the coevolution of plants and insects.",
        e: "Researchers first studied repellent effects in plants beginning in the 1950s."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_004.id,
      passage_text: PASSAGE_004.content,
    } as VRQuestionData,
    answers: generateMCAnswers("a"),
    explanation: "According to the passage, which of the following is true of plant antiherbivore chemistry? This question addresses what the information in the passage indicates about plant antiherbivore chemistry—that is, plants' chemical defenses against herbivore attacks. The second paragraph of the passage cites the views of various scientists regarding the possible role of resin in antiherbivore chemistry; plants could have evolved resin specifically to repel insects. According to the second paragraph, various scientists have suggested that a change in antiherbivore chemistry, here specifically involving resin, could repel insects; alternatively, some insects could have been attracted to resin, feeding more heavily on plants that produced it. Other researchers have suggested that even if resin does not directly repel or attract insects, it may indirectly affect insect-feeding behavior by mediating changes in plants' antiherbivore chemistry.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00543",
    question_number: 543,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Of the following topics, which would be most likely to be studied within the discipline of chemical ecology as it is described in the passage?",
      options: {
        a: "Seeds that become attached to certain insects, which in turn carry away the seeds and aid in the reproductive cycle of the plant species in question",
        b: "An insect species that feeds on weeds detrimental to crop health and yield, and how these insects might aid in agricultural production",
        c: "The effects of deforestation on the life cycles of subtropical carnivorous plants and the insect species on which the plants feed",
        d: "The growth patterns of a particular species of plant that has proved remarkably resistant to herbicides",
        e: "Insects that develop a tolerance for feeding on a plant that had previously been toxic to them, and the resultant changes within that plant species"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_004.id,
      passage_text: PASSAGE_004.content,
    } as VRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "The discipline of chemical ecology, as it is described in the passage, deals with how plants use chemicals to interact with other organisms—in particular, how they defend against attack—and how those interactions have evolved. To be studied within that discipline, a specific topic would need to address some aspect of that chemical interaction. Chemical ecology developed to deal with the interdependence between plants and insects. Insects' developing a tolerance for feeding on a once-toxic plant, and the plants' resultant changes, is a situation of just such interdependence: plants and insects coevolving.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00544",
    question_number: 544,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The author refers to \"bacterial infections\" (see line 11) most likely in order to",
      options: {
        a: "describe the physiological function that gum performs in plants",
        b: "demonstrate that sap is not the only substance that is transported through a plant's tissues",
        c: "explain how modern chemical analysis has been used to clarify the function of resin",
        d: "show that gum cannot serve as an effective defense against herbivores",
        e: "give an example of how confusion has arisen with regard to the nature of resin"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_004.id,
      passage_text: PASSAGE_004.content,
    } as VRQuestionData,
    answers: generateMCAnswers("a"),
    explanation: "The author mentions bacterial infections in the first paragraph as the reason why plants produce the substance known as gum. The author states directly that plants produce gum in response to bacterial infections.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00545",
    question_number: 545,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The author of the passage refers to Pliny most probably in order to",
      options: {
        a: "give an example of how the nature of amber has been misunderstood in the past",
        b: "show that confusion about amber has long been more pervasive than confusion about resin",
        c: "make note of the first known reference to amber as a semiprecious gem",
        d: "point out an exception to a generalization about the history of people's understanding of amber",
        e: "demonstrate that Pliny believed amber to be a mineral"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_004.id,
      passage_text: PASSAGE_004.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "The passage states generally that amber has been widely misunderstood but cites Pliny as noting correctly, in the first century, that amber resulted from a substance discharged by trees. Pliny's recognition that amber came from a substance discharged by trees stands, in the author's account, as an exception to the widespread incorrect identifications of the substance.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00546",
    question_number: 546,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The primary purpose of the passage is to",
      options: {
        a: "compare the impact of the Great Depression on Latin America with its impact on the United States",
        b: "criticize a school of economic historians for failing to analyze the Great Depression in Latin America within a global context",
        c: "illustrate the risks inherent in comparing different types of economic enterprises to explain economic phenomena",
        d: "call into question certain scholars' views concerning the severity of the Great Depression in Latin America",
        e: "demonstrate that the Great Depression had a more severe impact on industry in Latin America than in certain other regions"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_005.id,
      passage_text: PASSAGE_005.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "This question depends on understanding the passage as a whole. The passage first describes the view of many economic historians of the 1980s. It next describes the evidence on which that view is based. The remainder of the passage raises issues about the rationale for that view. The passage claims that certain scholars underestimate the severity of the Great Depression in Latin America.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00547",
    question_number: 547,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Which of the following conclusions about the Great Depression is best supported by the passage?",
      options: {
        a: "It did not impede Latin American industrial growth as much as historians had previously thought.",
        b: "It had a more severe impact on the Brazilian and the Mexican textile industries than it had on Latin America as a region.",
        c: "It affected the Latin American textile industry more severely than it did any other industry in Latin America.",
        d: "The overall impact on Latin American industrial growth should be reevaluated by economic historians.",
        e: "Its impact on Latin America should not be compared with its impact on the United States."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_005.id,
      passage_text: PASSAGE_005.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "This question asks which conclusion is most strongly supported by the passage. The passage presents the rationale of some historians for their conclusion that the Great Depression did not significantly interfere with economic growth in Latin America. It then critiques that rationale as questionable. By questioning the historians' claims, the passage suggests that a reevaluation of the Great Depression's effect on Latin America is needed. As presented in the passage, the passage author's critique of the historians' rationale for their claims provides significant support for the conclusion that their claims should be reevaluated.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00548",
    question_number: 548,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Which of the following, if true, would most strengthen the author's assertion regarding economic indicators in lines 25–27?",
      options: {
        a: "During an economic depression, European textile manufacturers' profits rise while their industrial output remains steady.",
        b: "During a national economic recession, United States microchips manufacturers' profits rise sharply while United States steel manufacturers' profits plunge.",
        c: "During the years following a severe economic depression, textile manufacturers' output levels and profit levels increase in Brazil and Mexico but not in the rest of Latin America.",
        d: "Although Japanese industry as a whole recovers after an economic recession, it does not regain its previously high levels of production.",
        e: "While European industrial output increases in the years following an economic depression, total output remains below that of Japan or the United States."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_001.id,
      passage_text: PASSAGE_001.content,
    } as VRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "The question involves applying information from outside the passage to a claim made by the author. The text in lines 25–27 asserts that broad economic indicators pertaining to a nation or region can obscure differences between individual firms or industries within that nation or region. The question asks which evidence would most strengthen the support for that conclusion. The phrase a national recession refers to a general economic indicator. Suppose that in a situation described as a national recession, one industry (microchip manufacturing) prospers while another industry (steel manufacturing) does not. This would provide some additional support, over and above that given in the passage, for the assertion that broad economic indicators may mask differences between industries.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00549",
    question_number: 549,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "It can be inferred from the passage that a large plant might have to spend more than a similar but smaller plant on environmental compliance because the larger plant is",
      options: {
        a: "more likely to attract attention from local regulators",
        b: "less likely to be exempt from permit and reporting requirements",
        c: "less likely to have regulatory costs passed on to it by companies that supply its raw materials",
        d: "more likely to employ older production technologies",
        e: "more likely to generate wastes that are more environmentally damaging than those generated by smaller plants"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_002.id,
      passage_text: PASSAGE_002.content,
    } as VRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "This item depends on understanding the implications of the passage's discussion of differences between large and small plants. It asks what might be true of a larger plant that would compel it to spend more than a smaller plant on environmental compliance. The passage addresses this issue by stating that smaller plants are often not subject to the same permit or reporting requirements that larger plants are. According to the passage, certain permit or reporting requirements may not apply to smaller plants; this suggests that larger plants are less likely than smaller plants to be exempt from these requirements, and thus that the larger plants would have to spend more to comply.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00550",
    question_number: 550,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "According to the passage, which of the following statements about sulfur dioxide and nitrogen oxide outputs is true?",
      options: {
        a: "Older production technologies cannot be adapted so as to reduce production of these outputs as waste products.",
        b: "Under the most recent environmental regulations, industrial plants are no longer permitted to produce these outputs.",
        c: "Although these outputs are environmentally hazardous, some plants still generate them as waste products despite the high compliance costs they impose.",
        d: "Many older plants have developed innovative technological processes that reduce the amounts of these outputs generated as waste products.",
        e: "Since the production processes that generate these outputs are less costly than alternative processes, these less expensive processes are sometimes adopted despite their acknowledged environmental hazards."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_002.id,
      passage_text: PASSAGE_002.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "This item depends on identifying what the passage states explicitly about outputs of sulfur dioxide and nitrogen oxide. The passage says that plants that produce these outputs are those that use older industrial coal-fired burners, and that such plants are subject to extensive compliance costs imposed by new regulations. The passage states that some companies are still using the older kinds of burners that generate sulfur dioxide and nitrogen oxide outputs, and that new regulations have imposed high compliance costs on these companies.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00551",
    question_number: 551,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Which of the following best describes the relationship of the statement about large plants (lines 12–17) to the passage as a whole?",
      options: {
        a: "It presents a hypothesis that is disproved later in the passage.",
        b: "It highlights an opposition between two ideas mentioned in the passage.",
        c: "It provides examples to support a claim made earlier in the passage.",
        d: "It exemplifies a misconception mentioned earlier in the passage.",
        e: "It draws an analogy between two situations described in the passage."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_002.id,
      passage_text: PASSAGE_002.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "This question asks about the role played in the passage by the following statement: Additionally, large plants can spread compliance costs across a larger revenue base; on the other hand, some smaller plants may not even be subject to certain provisions such as permit or reporting requirements by virtue of their size. This statement describes situations in which compliance costs for plants of different sizes may differ, which serve as evidence in support of the passage's main claim: that environmental regulations do not affect all competitors in a given industry uniformly. The statement provides examples to support the initial claim made in the passage that regulatory costs fall unevenly on competitors in an industry: large plants can spread compliance costs around, and smaller plants may not even have to pay certain costs.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00552",
    question_number: 552,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The primary purpose of the passage is to",
      options: {
        a: "address a widespread environmental management problem and suggest possible solutions",
        b: "illustrate varying levels of compliance with environmental regulation among different corporations",
        c: "describe the various alternatives to traditional methods of environmental management",
        d: "advocate increased corporate compliance with environmental regulation",
        e: "correct a common misconception about the impact of environmental regulations"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_002.id,
      passage_text: PASSAGE_002.content,
    } as VRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "This question depends on understanding the passage as a whole. Its first sentence indicates its main purpose: to dispel a myth about environmental regulations that is often taken as fact. The passage primarily aims to dispel the belief that environmental regulations affect all companies in an industry uniformly.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00553",
    question_number: 553,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The primary purpose of the passage is to",
      options: {
        a: "review research demonstrating the benefits of corporate mergers and acquisitions and examine some of the drawbacks that acquisition behavior entails",
        b: "contrast the effects of corporate mergers and acquisitions on acquiring firms and on firms that are acquired",
        c: "report findings that raise questions about a reason for corporate mergers and acquisitions and suggest possible alternative reasons",
        d: "explain changes in attitude on the part of acquiring firms toward corporate mergers and acquisitions",
        e: "account for a recent decline in the rate of corporate mergers and acquisitions"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_003.id,
      passage_text: PASSAGE_003.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "This question requires understanding what the passage as a whole is trying to do. The passage begins by citing three studies that demonstrate that when firms acquire other firms, there is not necessarily a worthwhile economic gain. The passage then cites economic interests as the reason given by firms when they acquire other firms but calls into question the veracity of this reasoning. The passage then goes on to speculate as to why mergers and acquisitions occur. The passage surveys reports that question the reason given by firms when they acquire other firms and suggests other reasons for these acquisitions.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00554",
    question_number: 554,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "It can be inferred from the passage that the author would be most likely to agree with which of the following statements about corporate acquisitions?",
      options: {
        a: "Their known benefits to national economies explain their appeal to individual firms during the 1970s and 1980s.",
        b: "Despite their adverse impact on some firms, they are the best way to channel resources from less to more productive sectors of a nation's economy.",
        c: "They are as likely to occur because of poor monitoring by boards of directors as to be caused by incentive compensation for managers.",
        d: "They will be less prevalent in the future, since their actual effects will gain wider recognition.",
        e: "Factors other than economic benefit to the acquiring firm help to explain the frequency with which they occur."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_003.id,
      passage_text: PASSAGE_003.content,
    } as VRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "This question requires understanding what view the author has about a particular issue. The three studies cited by the passage all suggest that mergers and acquisitions do not necessarily bring economic benefit to the acquiring firms. The author concludes therefore that factors having little to do with corporate economic interests explain acquisitions and then goes on to speculate as to what the reasons may actually be. The passage states that factors other than economic interests drive mergers and acquisitions.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00555",
    question_number: 555,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The author of the passage mentions the effect of acquisitions on national economies most probably in order to",
      options: {
        a: "provide an explanation for the mergers and acquisitions of the 1970s and 1980s overlooked by the findings discussed in the passage",
        b: "suggest that national economic interests played an important role in the mergers and acquisitions of the 1970s and 1980s",
        c: "support a noneconomic explanation for the mergers and acquisitions of the 1970s and 1980s that was cited earlier in the passage",
        d: "cite and point out the inadequacy of one possible explanation for the prevalence of mergers and acquisitions during the 1970s and 1980s",
        e: "explain how modeling affected the decisions made by managers involved in mergers and acquisitions during the 1970s and 1980s"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_003.id,
      passage_text: PASSAGE_003.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "This question requires understanding why a piece of information is included in the passage. After the passage cites the results of the three studies on mergers and acquisitions, the author concludes that even though acquiring firms state that their objectives are economic, factors having little to do with corporate economic interests explain acquisitions (lines 10–11). Among alternative explanations, the author points to managerial error in estimating the value of firms targeted for acquisition (lines 12–13) as possibly contributing to acquisition behavior in the 1970s and 1980s. The passage uses the mention of national economies as part of a larger point questioning the stated motivations behind firms' efforts to acquire other firms.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00556",
    question_number: 556,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The author of the passage implies that which of the following is a possible partial explanation for acquisition behavior during the 1970s and 1980s?",
      options: {
        a: "Managers wished to imitate other managers primarily because they saw how financially beneficial other firms' acquisitions were.",
        b: "Managers miscalculated the value of firms that were to be acquired.",
        c: "Lack of consensus within boards of directors resulted in their imposing conflicting goals on managers.",
        d: "Total compensation packages for managers increased during that period.",
        e: "The value of bidding firms' stock increased significantly when prospective mergers were announced."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_003.id,
      passage_text: PASSAGE_003.content,
    } as VRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "This question requires recognizing what can be inferred from the information in the passage. After providing the results of the studies of mergers and acquisitions, the author concludes that even though acquiring firms state that their objectives are economic, factors having little to do with corporate economic interests explain acquisitions (lines 10–11). Among alternative explanations, the author points to managerial error in estimating the value of firms targeted for acquisition (lines 12–13) as possibly contributing to acquisition behavior in the 1970s and 1980s. The author states that one explanation for acquisition behavior may be that managers erred when they estimated the value of firms being acquired.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00557",
    question_number: 557,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "According to the passage, which of the following statements regarding earthen mounds in the Dallas communities is accurate?",
      options: {
        a: "They served primarily as burial grounds.",
        b: "They were constructed in key locations on the perimeter of the village.",
        c: "They were elements in important structures in the community.",
        d: "They were used as storehouses for keeping valuable possessions safe.",
        e: "They contained utilitarian items made of nonlocal materials."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_004.id,
      passage_text: PASSAGE_004.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "This question requires recognizing what claim the passage makes about the earthen mounds in the Dallas communities. The passage states that in the largest Dallas communities, earthen mounds served as substructures for buildings that were important for civic and religious affairs. A. The passage does indicate that some individuals were buried in the mounds, but the mounds are also described as having served as substructures for buildings important to civic and religious affairs. The passage does not indicate whether either of these purposes was primary. B. The fact that the mounds served as substructures for important civic and religious buildings does not suggest that they were located on the perimeter of villages. C. Correct. The mounds are described in the passage as substructures for buildings that were important to civic and religious affairs. D. Valuable possessions are not described as being stored in the mounds for safekeeping, but rather as being buried there along with the high-status people interred there. E. The items described as being made of nonlocal materials are not utilitarian objects but rather finely crafted items that denoted the high political status of the people interred in the mounds.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00558",
    question_number: 558,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "In lines 26–28, the author of the passage raises the possibility that taller people achieved greater success most probably in order to",
      options: {
        a: "suggest that two explanations for a phenomenon are equally plausible",
        b: "introduce empirical data supporting a position",
        c: "anticipate an objection to an argument",
        d: "question the usefulness of relying solely on physical evidence",
        e: "point out a weakness in a traditional argument"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_004.id,
      passage_text: PASSAGE_004.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "This question requires recognizing what role the author intends lines 26-28 to play in the context of the passage. The passage points out that the burials of the Dallas communities formed a pattern, with the tallest skeletons being interred in the mounds, and progressively smaller skeletons interred progressively more distant from the mounds. The passage infers from this that the people buried further from the mounds were of lower status, and their lower status—because it is a relatively poor diet—led to those people being less tall. Lines 26-28—stating that it is possible that taller people had greater success in attaining high status—is presented as an alternative possible explanation, thus a potential objection to the implication the author makes. A. The passage does not suggest that two explanations are equally plausible, and in fact suggests one explanation is superior to the one expressed in lines 26-28. B. Lines 26-28 does not serve as empirical data supporting a position, but rather as a potential objection to the position the author supports. C. Correct. In lines 26-28, the author presents an explanation that is an alternative to the one the author proposes, thereby anticipating an objection to the author's argument. D. The author throughout the passage argues solely on the basis of physical evidence and does not question the usefulness of such evidence at this or any point. E. Nowhere is any argument characterized as a traditional argument.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00559",
    question_number: 559,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The passage suggests that the \"relationship\" mentioned in line 6 was initially recognized when archaeologists",
      options: {
        a: "attempted to trace the ancestry of the Timucua of Florida",
        b: "discovered a height differential among members of subgroups in the Dallas community",
        c: "realized that the Dallas communities endured periods of nutritional deprivation",
        d: "began to compare the social organization and economies of the Timucua with that of the Dallas communities",
        e: "became curious about differences in trace elements found in the bones of Dallas community members"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_004.id,
      passage_text: PASSAGE_004.content,
    } as VRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "This question requires recognizing what the passage suggests about the relationship mentioned in line 6. The passage begins with a brief mention of the Timucua of Florida, among whom the best food derived from harvesting and hunting went to families of high social status. The passage then shifts to its main focus, a similar relationship between diet and social status among the Dallas communities. Evidence for this relationship first came when archaeologists discovered that higher-status individuals in the Dallas community tended to be significantly taller than lower-status individuals. A. The passage makes no mention of attempts to trace the ancestry of the Timucua of Florida. B. Correct. The passage asserts that the first clue regarding the relationship between diet and social status in Dallas communities was when archaeologists noted the height differences between members of different socioeconomic subgroups. C. The passage makes no mention of periods of nutritional deprivation in the Dallas communities. It does mention times of economic stress among the Timucua, but this is not related to the recognition of the relationship between social status and diet in Dallas communities. D. The passage does mention similarities between the social organization and economies of the Timucua and those of the Dallas communities, but there is no indication in the passage of whether these comparisons were first made before or after the discovery of the relationship between status and diet among the Dallas communities. E. The fact that there are differences in trace elements found in Dallas community members is mentioned in the passage, and it is used as evidence for the existence of the relationship between social status and diet. Curiosity about these differences in trace elements, however, is not what the passage identifies as the first real clue about the existence of this relationship.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00560",
    question_number: 560,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The passage suggests which of the following about the diet of the Dallas communities?",
      options: {
        a: "Wild edible plants were a relatively minor element in the diet.",
        b: "Game was less likely to be available to lower-status individuals than were edible plants.",
        c: "The diet was composed primarily of agricultural crops when game was scarce.",
        d: "The diet was obtained entirely from local food sources.",
        e: "The diet was well balanced, especially at harvest-time."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_004.id,
      passage_text: PASSAGE_004.content,
    } as VRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "Answering this question requires recognizing something that is suggested by the passage. The passage indicates that high levels of vanadium in human bone indicate a less nutritious diet that is heavily dependent on edible plants. A low level of vanadium, which is scarce in meat, would serve as evidence for a higher proportion of meat in an individual's diet. The passage also indicates that among the Dallas communities, game, rather than domestic animals, served as the source of meat. The other primary food sources were agricultural crops and wild edible plants, primarily nuts. Finally, the passage indicates high levels of vanadium in the skeletons of lower-status individuals of the Dallas communities. All this information taken together suggests that game was less likely to be available to such lower-status individuals than were edible plants. A. The passage indicates that wild edible plants were one of the three primary elements in the diet of the Dallas communities. B. Correct. The passage suggests that game was less available to lower-status individuals, and implies this from the fact that bones found in the burials of lower-status individuals contained greater quantities of vanadium. C. The passage does not indicate whether, when game was scarce, the diet of the Dallas communities relied on agricultural crops more than on wild edible plants. D. The passage does not indicate whether all of the Dallas communities' food was locally sourced, which leaves open the possibility that some of their food came from elsewhere. E. The passage provides support for the claim that, among the lower-status individuals in the Dallas communities, the diet was not well balanced; furthermore, the passage provides no evidence as to whether the diet of these communities became any more or less balanced at harvest-time.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00561",
    question_number: 561,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The primary purpose of the passage is to",
      options: {
        a: "explore the legal consequences of terminating a worker's employment",
        b: "define the employment-at-will doctrine and chronicle its historical evolution",
        c: "examine reasons underlying a trend away from the employment-at-will doctrine",
        d: "advocate increased protection for workers against wrongful termination by employers",
        e: "discuss a possible drawback of state laws intended to protect workers against wrongful termination"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_005.id,
      passage_text: PASSAGE_005.content,
    } as VRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "This question requires understanding the passage as a whole. The passage discusses the consequences that result from the enactment by state legislatures of laws that expand the concept of wrongful termination. It considers whether protecting workers against wrongful termination raises employers' labor costs, resulting in a reduction in employment in those states. A study by Dertouzos and Karoly confirmed that these laws do have such an effect. A. The passage considers the effect on employment rates of expanding the concept of wrongful termination, not the legal consequences of terminating a worker's employment. B. The passage does define the employment-at-will doctrine and discusses one change made to that doctrine by certain states, but it does not recount a series of specific changes that would constitute an account of its historical evolution. C. The passage simply asserts that some states have made a specific type of change to the employment-at-will doctrine; it does not examine reasons why the change has been made. D. The passage does not advocate increased protection for workers against wrongful termination by employers, but rather indicates that one study has found that certain negative consequences arise from such increased protection. E. Correct. The passage describes the findings of a study showing that state laws intended to protect workers against wrongful termination led to modest declines in employment in that state, indicating a possible drawback to such state laws.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00562",
    question_number: 562,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "Which of the following best describes the organization of the passage?",
      options: {
        a: "An idea is proposed and arguments against it are examined and then refuted.",
        b: "A doctrine is defined and reasons for favoring its adoption are listed.",
        c: "A doctrine is criticized, several possible alternatives are outlined, and one is endorsed.",
        d: "An idea is described, its antithesis is presented, and a synthesis of the two is proposed.",
        e: "A doctrine is defined, a revision to it is described, and the implications of that revision are discussed."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_005.id,
      passage_text: PASSAGE_005.content,
    } as VRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "The passage begins by introducing and defining a doctrine that has historically prevailed in the United States, the doctrine of employment-at-will. The passage then goes on to consider a modification of the doctrine that has been implemented, namely, an expansion of the concept of wrongful termination. Finally, the passage presents the results of a study showing some negative implications of this modification of the doctrine. A. Though the passage does provide some negative effects of the expansion of wrongful termination that could be used in an argument against that expansion, the passage does not refute such an argument. B. The passage does define a doctrine, but the doctrine is already widely implemented, and the passage does not list reasons favoring its adoption. C. The passage does not criticize the doctrine of employment-at-will, though it does present some negative information about a modification of it—the expansion of the concept of wrongful termination. But the passage does not list several alternatives either to the doctrine or to its modification. D. Even if one could describe the discussion of the expansion of wrongful termination as the \"antithesis\" of the doctrine of employment-at-will—a description that is not well supported—the passage does not propose any synthesis of the two. E. Correct. A doctrine (employment-at-will) is defined, a revision—the expansion of the concept of wrongful termination—is discussed, and evidence of negative effects of the revision is discussed.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00563",
    question_number: 563,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The passage suggests which of the following regarding wrongful-termination lawsuits?",
      options: {
        a: "States that do not implement wrongful-termination laws will probably see an increase in wrongful-termination lawsuits.",
        b: "It is less profitable to file wrongful-termination lawsuits against unionized companies than against companies without unions.",
        c: "A wrongful-termination lawsuit is less costly to a company than continuing the employment of an unproductive worker.",
        d: "Obtaining financial compensation is an important motivation for filing wrongful-termination lawsuits.",
        e: "Those who file wrongful-termination lawsuits are likely to be awarded larger settlements under the employment-at-will doctrine than under wrongful-termination laws."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_005.id,
      passage_text: PASSAGE_005.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "Answering this question requires recognizing what the passage suggests regarding wrongful-termination lawsuits. The passage does not directly state that the motivation for filing wrongful-termination lawsuits is obtaining financial compensation, but there are suggestions that this is the case. For instance, the passage discusses the increased cost of labor to employers due to the expansion of the concept of wrongful termination. The fact of wrongful-termination lawsuits leads employers to spend more time and money screening potential employees, suggesting that the cost to employers of successfully being sued for wrongful termination would likely involve some financial payout—or compensation—to the former employees who sue them. Additionally, the passage mentions the various degrees of profitability for employees who file wrongful-termination lawsuits, which results in various degrees of motivation to file such suits, suggesting that financial compensation is a crucial motivation for filing these suits. A. The passage gives no indication that states that do not implement such laws would likely see an increase in wrongful-termination lawsuits. B. The passage does indicate that the reduction in employment due to a state's expansion of the concept of wrongful termination would be smaller for unionized companies than for nonunionized companies. However, the passage suggests that this is because unions have already implemented protection from wrongful termination—and so there would not be much of a change from current practice—and not because the lawsuits would be less profitable. C. The passage states that economic theorists suggest that expanding the concept of wrongful termination will lead firms to be reluctant to terminate less-productive workers, which would not be the case if such lawsuits were less costly than retaining such workers. D. Correct. As discussed above, the passage strongly implies that financial compensation is a significant motivation for such lawsuits. E. If this were the case, the expansion of the concept of wrongful termination would not lead to increased employment costs and a reduction in employment.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00564",
    question_number: 564,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "The primary purpose of the passage is to",
      options: {
        a: "argue against a conventional explanation for the extinction of certain salmon populations and suggest an alternative",
        b: "correct a common misunderstanding about the behavior of salmon in response to environmental degradation caused by human activity",
        c: "compare the effects of human activity on salmon populations with the effects of natural disturbances on salmon populations",
        d: "differentiate the particular effects of various human activities on salmon habitats",
        e: "describe how environmental degradation can cause changes in salmon populations that extend beyond a numerical reduction"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_006.id,
      passage_text: PASSAGE_006.content,
    } as VRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "The passage lists human activities that degrade salmon habitat, reducing salmon populations. Normally, salmon return to their streams of origin to spawn, but some \\\"straying\\\" can occur, with some salmon spawning in nearby streams. If massive environmental disruption causes a spike in straying, genetic fitness of salmon populations joined by large numbers of straying salmon can be adversely affected. A. No \\\"conventional explanation\\\" for the collapse of salmon populations is argued against in the passage. B. The passage does not characterize any opinion about the behavior of salmon as \\\"a common misunderstanding.\\\" C. Although the passage conjectures that salmon straying caused by human disruption of salmon habitats would likely not differ much from the straying caused by the Mount Saint Helens volcano eruption, the primary purpose of the passage is not to make a comparison of this kind. D. The passage does not explore how different human activities—e.g., agriculture and urban development—might differ in their effect on salmon populations. E. Correct. The second and third paragraphs of the passage explore various ways environmental degradation can affect salmon populations. Among the effects discussed are: reduction of populations in particular affected habitats; increased rates of straying by salmon away from their natal streams; and impacts—positive or negative—on the genetic fitness of salmon in habitats to which salmon stray.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00565",
    question_number: 565,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "It can be inferred from the passage that the occasional failure of some salmon to return to their natal streams in order to spawn provides a mechanism by which",
      options: {
        a: "pristine streams that are near polluted streams become polluted themselves",
        b: "the particular adaptations of a polluted stream's salmon population can be preserved without dilution",
        c: "the number of salmon in pristine habitats decreases relative to the number in polluted streams",
        d: "an environmentally degraded stream could be recolonized by new salmon populations should the stream recover",
        e: "the extinction of the salmon populations that spawn in polluted streams is accelerated"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_006.id,
      passage_text: PASSAGE_006.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "The passage describes how it can be ecologically beneficial that some salmon \\\"stray,\\\" i.e., return to spawn in a stream other than their stream of birth. A. The passage neither states nor implies that the straying of salmon away from a stream that has been polluted could spread pollution to the destination stream. B. A contrary idea is expressed: High rates of straying can cause large-scale interbreeding with the population of the destination stream, and this can dilute the genetics that allow the latter population to survive in that habitat. C. The passage suggests quite the opposite: a decrease in salmon populations in polluted streams relative to populations in other streams. D. Correct. According to the passage, one ecological advantage of a low level of straying is that it provides \\\"a mechanism by which a location can be repopulated should the fish there disappear.\\\" E. The passage does not indicate that a homeward-bound salmon straying from its stream of birth that has been degraded would hasten the rate of extinction of salmon in that stream.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00566",
    question_number: 566,
    section: "Verbal Reasoning",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      question_text: "According to the passage, human activity has had which of the following effects on salmon populations?",
      options: {
        a: "An increase in the size of salmon populations in some previously polluted rivers",
        b: "A decline in the number of salmon in some rivers",
        c: "A decrease in the number of straying salmon in some rivers",
        d: "A decrease in the gene flow between salmon populations that spawn in polluted streams and populations that spawn in pristine streams",
        e: "A decline in the vulnerability of some salmon populations to the effects of naturally occurring habitat destruction"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_006.id,
      passage_text: PASSAGE_006.content,
    } as VRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "The passage tells us that habitats can be degraded by human activity but does not mention how human activity might promote recovery of salmon populations in previously degraded habitats. A. The passage neither states nor implies that human activity has led to salmon population increase in previously polluted rivers. However, it does not deny the possibility that successful initiatives to reduce pollution and promote salmon population recovery have occurred. B. Correct. The point concerning decline in salmon populations due to human activity is made in the first sentence of the passage. C. The passage does not state that such a decrease could have resulted from human activity. Given the information in the passage, it seems likely that homeward-bound salmon that stray would be unlikely to spawn in rivers polluted through human activity. D. The passage suggests that human activity has increased straying by causing salmon to abandon polluted natal rivers in favor of clean ones, not that human activity has decreased straying. The passage also suggests that increased straying, rather than decreasing gene flow between affected salmon populations, actually increases it. E. The claim that human activity has reduced the vulnerability of salmon populations to destroyed habitats is neither made nor implied in the passage.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
];
