import {
  VerbalReasoningQuestion,
  VRQuestionData,
  generateMCAnswers,
} from "../types";
import {
  PASSAGE_006,
  PASSAGE_007,
  PASSAGE_008,
  PASSAGE_009,
  PASSAGE_010,
  PASSAGE_011,
  PASSAGE_012,
  PASSAGE_013,
  PASSAGE_014,
  PASSAGE_015,
  PASSAGE_016,
} from "./passages_OG";

export const verbalReasoningQuestionsOG_RC_Hard: VerbalReasoningQuestion[] = [
  {
    id: "VR-GMAT-OG__-00567",
    question_number: 567,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "The author's argument that increased straying can \"lower the overall fitness of subsequent generations\" (see lines 45–46) is based on which of the following assumptions?",
      options: {
        a: "A disturbance of salmonid spawning streams caused by human activity could increase the straying rate of affected salmonid populations as much as the aftermath of the Mount Saint Helens eruption did.",
        b: "In the streams in which the straying salmonids spawn, these straying salmonids would amount to no more than 40 percent of the total spawning population.",
        c: "Salmonids in some streams benefit from particular local adaptations.",
        d: "Nonenvironmental factors have no effect on salmonid straying rates.",
        e: "At least some of the streams in which straying salmonids would spawn are pristine, affected by neither natural nor artificial disturbances."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_006.id,
      passage_text: PASSAGE_006.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "We are asked which option states an assumption used in the passage to support the claim that a dramatic increase in straying can lower fitness in subsequent generations of the destination population. This assumes that the destination population had a gene pool that made it well adapted to its habitat. However, large numbers of straying interlopers could reduce, through interbreeding, the specific local adaptations of that population. A. A natural disaster of the magnitude of the Mount Saint Helens eruption would drastically increase straying. However, the claim in question is not based on an assumption that the dramatic increase in straying be equal to or greater than the increase caused by the Mount Saint Helens eruption. The assumption is merely that the increase would be dramatic even if not quite as large as that caused by the eruption. B. This is not an assumption on which the claim regarding reduction in fitness is based. The \\\"40 percent\\\" does not refer to a maximum rate of straying salmon spawning in the destination streams. C. Correct. The claim in question is based on this assumption. Before interbreeding occurs between straying salmonids and a population native to a relatively pristine habitat, the latter population would likely have developed, over a long period, genetic adaptations to conditions unique to that habitat. D. Nothing in the passage implies or contradicts this, but it is not an assumption on which the claim in question is based. E. This is consistent with the information in the passage, though not an assumption on which the claim under discussion is based.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00568",
    question_number: 568,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "Which of the following does the author mention as support for the view that environmental disturbances caused by human activity could increase straying rates?",
      options: {
        a: "The existence of salmon populations in rivers where the elimination of salmon habitat by human activity had previously made the fish extinct",
        b: "The results of studies measuring the impact on straying rates of habitat loss caused by human activity",
        c: "The potential for disturbances in one environment to cause the introduction of novel genes into salmon populations in neighboring areas",
        d: "The weaknesses in the view that the extinction of entire salmon populations is the only mechanism by which human destruction of salmon habitat reduces genetic diversity in salmon",
        e: "The absence of any reason for believing disturbances brought about by human activity would differ in their effects from comparable disturbances brought about by natural causes"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_006.id,
      passage_text: PASSAGE_006.content,
    } as VRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "What support does the passage offer for the view that salmon habitat disturbances caused by humans could boost the straying rates of salmon returning from the sea? The final paragraph addresses this question. A. This fact is mentioned in the passage, but not in a context relevant to the question asked, only in the context of discussing how limited straying could ultimately help in the restoration of a salmon population to a habitat destroyed by human activity. B. This is denied in the first sentence of the final paragraph, which indicates that no such studies have been conducted. C. This is mentioned in the second paragraph but is not relevant to the question asked concerning an increase in the rate of straying. D. The view referred to here is not mentioned in the passage, so the passage does not discuss any weaknesses in that view. E. Correct. In the final paragraph, the author suggests that habitat disturbances caused by human activity are unlikely to differ qualitatively in their effect on straying from the habitat disturbances caused by the Mount Saint Helens eruption. According to the passage, the eruption caused widespread environmental disruption and a large increase in straying, from an initial 16 percent to more than 40 percent.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00569",
    question_number: 569,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "The passage suggests that WIDC differed from WTUL in which of the following ways?",
      options: {
        a: "WIDC believed that the existing safety regulations were adequate to protect women's health, whereas WTUL believed that such regulations needed to be strengthened.",
        b: "WIDC believed that unions could not succeed in pressuring employers to comply with such regulations, whereas WTUL believed that unions could succeed in doing so.",
        c: "WIDC believed that lead poisoning in white lead factories could be avoided by controlling conditions there, whereas WTUL believed that lead poisoning in such factories could not be avoided no matter how stringently safety regulations were enforced.",
        d: "At the time that the legislation concerning white lead factories was proposed, WIDC was primarily concerned with addressing health conditions in white lead factories, whereas WTUL was concerned with improving working conditions in all types of factories.",
        e: "At the time that WIDC was opposing legislative attempts to restrict women's labor, WTUL had already ceased to do so."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_007.id,
      passage_text: PASSAGE_007.content,
    } as VRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "To answer this question, you need to understand the differences between WIDC and WTUL as they are described in the passage. The only information about WTUL in the passage is that it had stopped opposing restrictions on women's labor in the late 1880s, and that, because existing safety regulations were not being enforced, it supported the proposal to prohibit women from working in white lead factories. WIDC, on the other hand, was formed in 1892 specifically to oppose restrictions on women's labor, and it opposed the proposal. A. According to the passage, WIDC did believe that existing safety regulations, if enforced, could prevent lead poisoning. WTUL may or may not have believed that the safety regulations needed to be strengthened; all the passage states is that WTUL did not believe that the safety regulations were likely to be enforced. B. The passage states that WTUL believed that because there were no unions to pressure employers, the employers would not comply with safety regulations. The passage does not present any information on which to base a conclusion about WIDC's beliefs regarding union pressure on employers. C. Based on information in the passage, both WIDC and SPEW believed that enforcing safety regulations could protect women against lead poisoning. WIDC supported SPEW's position on the matter. WTUL believed that safety regulations were unlikely to be enforced because of the lack of unions. D. The passage states that WIDC viewed the proposal to restrict women's employment in white lead factories as an instance of legislation designed to limit women's work opportunities—precisely the legislation that WIDC was formed to oppose. Thus, WIDC was primarily concerned with the factories' health conditions. E. Correct. WIDC began opposing legislative attempts to restrict women's labor in 1892 and continued to do so through at least 1895, when the Home Secretary proposed prohibiting women from working in white lead factories. WTUL stopped opposing restrictions on women's labor in the late 1880s, before WIDC was even founded. Thus, the passage suggests that WTUL had stopped opposing restrictions on women's labor well before WIDC worked to oppose such legislation.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00570",
    question_number: 570,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "Which of the following, if true, would most clearly support the contention attributed to SPEW in lines 17–20?",
      options: {
        a: "Those white lead factories that most strongly enforced regulations concerning worker safety and hygiene had the lowest incidences of lead poisoning among employees.",
        b: "The incidence of lead poisoning was much higher among women who worked in white lead factories than among women who worked in other types of factories.",
        c: "There were many household sources of lead that could have contributed to the incidence of lead poisoning among women who also worked outside the home in the late nineteenth century.",
        d: "White lead factories were more stringent than were certain other types of factories in their enforcement of workplace safety regulations.",
        e: "Even brief exposure to the conditions typically found in white lead factories could cause lead poisoning among factory workers."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_007.id,
      passage_text: PASSAGE_007.content,
    } as VRQuestionData,
    answers: generateMCAnswers("a"),
    explanation: "This question requires the reader to find a statement that would provide additional support for the contention made in the following statement: SPEW contended, and WIDC concurred, that controllable conditions in such factories were responsible for the development of lead poisoning. Information suggesting that when conditions were controlled, lead poisoning was less likely to develop would provide support for SPEW's contention. A. Correct. If incidences of lead poisoning were low in those factories that enforced hygiene and safety regulations, that would suggest that lead poisoning was not an inevitable result of working in a white lead factory—but rather that lead poisoning was the result of poor hygiene and safety practices. B. It would not be particularly surprising for the incidence of lead poisoning to be higher among women working in white lead factories than among women working in other kinds of factories—but such a finding would say nothing about whether controllable conditions had any effect on the development of lead poisoning. C. The existence of household sources of lead that might contribute to lead poisoning would weaken, not support, SPEW's contention that controllable factory conditions were responsible for the development of lead poisoning. D. If white lead factories enforced workplace safety regulations more stringently than did some other types of factories, it might be the case that SPEW's contention was incorrect: that even controlled conditions could not prevent a high incidence of lead poisoning. E. If the conditions typically found in white lead factories were particularly bad with regard to safety and hygiene, it could conceivably be the case that SPEW's contention was true—that is, that the conditions that caused lead poisoning were controllable. But it might also be the case that an uncontrollable aspect of those conditions caused lead poisoning. Thus, this neither supports nor undermines SPEW's contention clearly.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00571",
    question_number: 571,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "The passage is primarily concerned with",
      options: {
        a: "presenting various groups' views of the motives of those proposing certain legislation",
        b: "contrasting the reasoning of various groups concerning their positions on certain proposed legislation",
        c: "tracing the process whereby certain proposed legislation was eventually enacted",
        d: "assessing the success of tactics adopted by various groups with respect to certain proposed legislation",
        e: "evaluating the arguments of various groups concerning certain proposed legislation"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_007.id,
      passage_text: PASSAGE_007.content,
    } as VRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "Answering this question depends on identifying the overall point of the passage. The passage is mainly concerned with explaining the reasons behind the positions taken by WIDC and SPEW, which opposed the proposal to enact legislation prohibiting women from holding most white lead factory jobs, and the reasoning of WTUL, which supported the proposal. A. The passage explains how WIDC viewed the proposal, but it does not indicate what any of the groups believed about the motivations of the Home Secretary, who made the proposal. B. Correct. The passage contrasts the reasoning of the WIDC and SPEW, both of which believed that enforcing safety regulations would make the proposed legislation unnecessary, with the reasoning of WTUL, which thought that safety regulations were unlikely to be enforced and thus supported the proposal. C. The passage simply states that the proposal was eventually enacted; it does not trace the process by which this occurred. D. The passage implies that WIDC and SPEW were unsuccessful in their opposition to the proposed legislation, but it identifies only one tactic used in opposition to it: SPEW's attempt to challenge it by investigating the causes of lead poisoning. E. The passage does not evaluate the groups' arguments concerning the proposed legislation; rather, it presents those arguments without comment on their quality or value.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00572",
    question_number: 572,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "The author of the passage refers to Robert Filmer (see line 9) primarily in order to",
      options: {
        a: "show that Royalist ideology was somewhat more radical than most historians appear to realize",
        b: "qualify the claim that patriarchalism formed the basis of Royalist ideology",
        c: "question the view that most early feminists were associated with the Royalist faction",
        d: "highlight an apparent tension between Royalist ideology and the ideas of early feminists",
        e: "argue that Royalists held conflicting opinions on issues of family organization and women's political rights"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_008.id,
      passage_text: PASSAGE_008.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "This question asks about the role of Filmer in the passage. The author states that Filmer's radical patriarchalism is associated with Royalist ideology and then goes on to define radical patriarchalism as an ideology that asserts the power of the king and the male head of the household. Early feminists, however, questioned the subordination of women in marriage. Thus, there seems to be a conflict between these two sets of ideas. A. Although the passage refers to Filmer's view as radical patriarchalism, it provides no evidence regarding any differences in the degrees to which historians consider that view, or Royalism in general, to be radical. B. Filmer's work supports the claim that patriarchalism was the basis of Royalist ideology; it does not qualify such a claim. C. That Filmer's approach was one of radical patriarchalism makes it surprising that early feminists were associated with the Royalist faction, but it does not provide any grounds for questioning whether they were so associated. D. Correct. There is apparent tension between Filmer's radical patriarchalism, if that is indeed essential to Royalist ideology, and the ideas of early feminists, who questioned such patriarchalism.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00573",
    question_number: 573,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "The passage suggests which of the following about the seventeenth-century English women mentioned in line 2?",
      options: {
        a: "Their status as forerunners of modern feminism is not entirely justified.",
        b: "They did not openly challenge the radical patriarchalism of Royalist Filmerian ideology.",
        c: "Cavendish was the first among these women to criticize women's subordination in marriage and assert women's equality with men.",
        d: "Their views on family organization and women's political rights were diametrically opposed to those of both Royalist and Parliamentarian ideology.",
        e: "Historians would be less puzzled if more of them were identified with the Parliamentarian side in the English Civil Wars."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_008.id,
      passage_text: PASSAGE_008.content,
    } as VRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "The first sentence of the passage refers to women who are both regarded as forerunners of modern feminism and identified as Royalists. The passage goes on to suggest that, given Royalist ideology's association with Filmer's radical patriarchalism (equating absolute power of the king with absolute power of the male head of household), it is surprising that feminism would find any footing within such an ideology. A. Nothing in the passage disputes the idea that the seventeenth-century English women in question should be considered the forerunners of modern feminism. B. Gallagher provides the example of Margaret Cavendish as a writer who did openly challenge radical patriarchalism—albeit only in her writings. C. The passage states that Cavendish had successors among early feminists, but it does not indicate whether she herself was the first seventeenth-century English woman to assert women's equality. D. The passage does not indicate what the Parliamentarian view of family organization and women's political rights was, so there is no way to determine whether the Royalist forerunners of modern feminism were opposed to that view. E. Correct. The basic puzzle the passage sets out to solve is why the forerunners of modern feminism would have been associated with the Royalist side, which seems to have been based on radical patriarchalism. Historians would most likely have been less surprised if these women had been identified with the Parliamentarian side, which presumably did not embrace radical patriarchalism.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00574",
    question_number: 574,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "The passage suggests that Margaret Cavendish's decision to become an author was motivated, at least in part, by a desire to",
      options: {
        a: "justify her support for the Royalist cause",
        b: "encourage her readers to work toward eradicating Filmerian patriarchalism",
        c: "persuade other women to break free from their political and social isolation",
        d: "analyze the causes for women's exclusion from the pursuit of power",
        e: "create a world over which she could exercise total control"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_008.id,
      passage_text: PASSAGE_008.content,
    } as VRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "This question asks about Margaret Cavendish's reasons for becoming an author. The second paragraph describes her as someone who insisted that she was a self-sufficient being; she understood that, given the real-world strictures in place, she could achieve this self-sufficiency in her own mind and on paper as a writer. So her decision to become a writer can be inferred to be motivated by her desire to exercise power and control. A. The passage states that Cavendish justified her being the center of her own universe by invoking the Royalist figure of the absolute monarch; there is no suggestion in the passage that Cavendish felt the need to justify any support for the actual Royalist cause. B. The passage gives no direct indication that Cavendish was even aware of Filmerian patriarchalism. C. The second paragraph states that Cavendish's idea of absolute singularity carried with it the idea of social and political isolation; Cavendish was most likely not motivated by a desire to persuade other women to break free from such isolation. D. Cavendish took the exclusion of women from the pursuit of power for granted; the passage does not suggest that she was concerned with its causes. E. Correct. According to the passage, Cavendish considered herself a self-sufficient being who was at the center of her own universe; in her writing, she wanted to create a world in which this was also true.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00575",
    question_number: 575,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "The phrase \"a satellite orbiting a dominant male planet\" (lines 41–42) refers most directly to",
      options: {
        a: "Cavendish's concept that each woman is a sovereign self",
        b: "the complete political and social isolation of absolute singularity",
        c: "the immaterial world that a writer can create on paper",
        d: "the absolute subordination of women in a patriarchal society",
        e: "the metaphorical figure of the absolute monarch"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_008.id,
      passage_text: PASSAGE_008.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "The phrase in question is a satellite orbiting a dominant male planet. The passage states that this was the idea that Cavendish was reacting against; she preferred instead the idea that she was the center of her own universe, her own sovereign, subject to no one. A. The idea of a satellite orbiting a dominant male planet refers not to Cavendish's idea that each woman is a sovereign self, but rather to the idea directly opposed to that: each woman must submit to a dominant male. B. A satellite orbiting a dominant male planet is by definition not isolated, nor is it singular. C. According to the passage, Cavendish wished to create her own world as a writer so that she did not have to be a satellite. D. Correct. The phrase refers to the idea that in a patriarchal society, women are as satellites to men, who are the dominant planets. E. While radical patriarchy does equate the monarch with the male head of the household, the phrase in question is most directly about the relationship, under patriarchy, between women and men.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00576",
    question_number: 576,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "The primary purpose of the passage is to",
      options: {
        a: "trace the historical roots of a modern sociopolitical movement",
        b: "present one scholar's explanation for a puzzling historical phenomenon",
        c: "contrast two interpretations of the ideological origins of a political conflict",
        d: "establish a link between the ideology of an influential political theorist and that of a notoriously eccentric writer",
        e: "call attention to some points of agreement between opposing sides in an ideological debate"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_008.id,
      passage_text: PASSAGE_008.content,
    } as VRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "This question asks about the passage as a whole. The passage is mainly concerned with outlining Catherine Gallagher's attempt to explain why, given Royalist ideology's apparent association with radical patriarchalism, Royalist women offered feminist critiques of women's subordination in marriage and asserted their equality with men. A. The passage makes no connection between early feminism and its modern form. B. Correct. The passage presents a puzzling historical phenomenon, that Royalist women critiqued patriarchalism, in the first paragraph, and then presents Catherine Gallagher's explanation for that phenomenon in the second paragraph. C. While the passage discusses the political conflict between the Royalists and Parliamentarians in the English Civil Wars in the first paragraph, neither this conflict, nor its ideological origins are the focus of the passage. Furthermore, the passage does not offer any interpretations of the origins of the conflict. D. The passage attempts to unlink the ideology of political theorist Robert Filmer and the eccentric author Margaret Cavendish by suggesting that Filmer's radical patriarchalism was not the only way of understanding Royalist ideology. Cavendish provided a different understanding entirely. E. While both sides of the ideological debate did agree on the absolute monarchy, the passage as a whole does not focus on this agreement, but rather on the disagreement about where, theoretically, the idea of absolute monarchy leads.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00577",
    question_number: 577,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "Which of the following, if true, would most clearly undermine Gallagher's explanation of the link between Royalism and feminism?",
      options: {
        a: "Because of their privileged backgrounds, Royalist women were generally better educated than were their Parliamentarian counterparts.",
        b: "Filmer himself had read some of Cavendish's early writings and was highly critical of her ideas.",
        c: "Cavendish's views were highly individual and were not shared by the other Royalist women who wrote early feminist works.",
        d: "The Royalist and Parliamentarian ideologies were largely in agreement on issues of family organization and women's political rights.",
        e: "The Royalist side included a sizable minority faction that was opposed to the more radical tendencies of Filmerian patriarchalism."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_008.id,
      passage_text: PASSAGE_008.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "This question asks about how to undermine the way in which Gallagher connects Royalism and feminism. According to Gallagher, Cavendish's work exemplifies the connection between these ideas, because Cavendish took the idea of absolute monarchy and extended that to the idea of absolute self, an idea that should, Cavendish believed, apply to women as well as men. A. Gallagher's explanation of the link between Royalism and feminism does not depend on the education level of Royalist women relative to Parliamentarian women. B. Filmer most likely would have been critical of Cavendish's ideas, had he encountered them, but the passage does not indicate that Gallagher's argument had anything to do with whether Filmer read Cavendish's writings. C. Correct. Gallagher uses Cavendish's work to explain how Royalism gave rise to feminism, but if Cavendish's views were not completely atypical of other Royalist women, then those views cannot explain the link as Gallagher suggests they do. D. The passage states in the first paragraph that if the Royalists and Parliamentarians were in agreement on issues of family organization and women's political rights, then feminists should have been divided between the two sides—but they were not. So this idea, if true, would undermine that statement, but not Gallagher's argument about the link between Royalists and feminists. E. If more Royalists were opposed to Filmer's radical patriarchalism, then Cavendish's writings would seem to be more representative of tendencies in Royalist ideology, thus making Gallagher's case stronger, not weaker.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00578",
    question_number: 578,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "According to the passage, Faue's study and Gabin's study agree in that both",
      options: {
        a: "attribute the inclusion of women in unions to the policies of the CIO",
        b: "emphasize the importance of unions at the community level",
        c: "argue that women played important roles in the establishment of industrial union organizations",
        d: "suggest that women in industrial union organizations played a subordinate role",
        e: "suggest that the interests of women workers were incompatible with those of unions in general"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_009.id,
      passage_text: PASSAGE_009.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "The passage discusses two studies of trade unionism in the United States: Elizabeth Faue's study of the labor movement in Minneapolis in the 1930s and the 1940s and Nancy Gabin's study of industrial unions from the 1930s to the 1970s. What do the two studies have in common? A. The passage indicates that according to Faue, the CIO during the years studied professed nondiscrimination and inclusion, but in practice marginalized women. Gabin's study indicates that though women encountered male domination in the unions, they were able to advance their interests in some CIO unions. B. The passage describes Faue's finding that at a community level, women had been important in building up the labor movement, but this contribution was not reflected in the operation of unions in the 1940s. The passage does not ascribe any emphasis on the importance of unionism at the community level to Gabin. C. Faue's account credits women with building up unionism at local community level. Gabin's study does not describe such a role as performed by women, even though women workers are portrayed as active in unions on behalf of women's issues. D. Correct. The passage represents the studies by Faue and by Gabin as suggesting that women were largely marginalized in terms of holding leadership roles in unions. E. As described in the passage, Gabin's study indicates that women could make some progress on advancing the interests of women workers in at least some unions. Faue's account, the passage suggests, portrays women's contributions as having become \\\"increasingly irrelevant to unions' institutional life\\\" when unions had become strong.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00579",
    question_number: 579,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "Which of the following can be inferred regarding the gender ideology mentioned in line 6?",
      options: {
        a: "It prevented women from making significant contributions to the establishment of industrial unions.",
        b: "It resulted from the marginalization of women in industrial unions.",
        c: "It had a significant effect on the advancement of women's issues within industrial unions.",
        d: "Its primary tenets were nondiscrimination and inclusion.",
        e: "Its effects were mitigated by the growth of industrial unions."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_009.id,
      passage_text: PASSAGE_009.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "The passage indicates that \\\"the prevailing gender ideology\\\" was largely incompatible with the CIO's professed commitment to \\\"principles of nondiscrimination and inclusion.\\\" The ideology in question tended toward a preference for male leadership. For example, Faue is cited as arguing that \\\"women were marginalized by union bureaucratization\\\" as unions disengaged from the community base with which women had been vitally involved. A. The passage indicates that women made such contributions in the early stages of trade union growth at community level, so this was not precluded by the gender ideology. B. The passage represents the marginalization as an effect rather than a cause of the gender ideology. C. Correct. Without significant representation in leadership roles, occupied mainly, if not exclusively, by men, one can infer that women's issues likely fell by the wayside. Moreover, as the community base became \\\"increasingly irrelevant to unions' institutional life,\\\" women's issues in the community were largely ignored by unions. D. The passage indicates that though these principles were professed by unions, they tended to be largely ignored in practice in relation to women's roles and their interests. E. Women were active at community level in the growth of unions, the passage tells us, citing Faue. However, as unions grew powerful, the \\\"gender ideology\\\" mentioned, far from being mitigated, was only reinforced.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00580",
    question_number: 580,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "The author of the passage is primarily concerned with",
      options: {
        a: "presenting two views",
        b: "reconciling two antithetical claims",
        c: "assessing conflicting evidence",
        d: "weakening a generally accepted argument",
        e: "tracing the development of an ideology"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_009.id,
      passage_text: PASSAGE_009.content,
    } as VRQuestionData,
    answers: generateMCAnswers("a"),
    explanation: "What does the passage suggest is the author's primary purpose? A. Correct. The author summarizes the views of two scholars regarding the contributions of women to the development of trade unionism in industrial settings in the United States, as well as some negative aspects in women's experience with trade unions. B. The two views discussed in the passage are presented as differing with respect to the degree to which women succeeded at various times in their efforts to \\\"advance their interests as women\\\" in industrial trade unions, but these views are not strictly antithetical. C. References to conflicting evidence occur in the passage, but assessing that evidence is not the author's primary concern. D. No information tending to weaken an argument the passage represents as generally accepted is to be found in the passage. E. The author indicates that both historical studies agree in seeing the persistence of a gender ideology of male domination in the culture and leadership of many industrial trade unions in the United States over several decades from the 1930s. However, the author does not trace the development of that ideology.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00581",
    question_number: 581,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "The primary purpose of the passage is to",
      options: {
        a: "assess the validity of a certain view",
        b: "distinguish between two phenomena",
        c: "identify the causes of a problem",
        d: "describe a disturbing trend",
        e: "allay concern about a particular phenomenon"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_010.id,
      passage_text: PASSAGE_010.content,
    } as VRQuestionData,
    answers: generateMCAnswers("a"),
    explanation: "This question requires understanding, in general terms, the purpose of the passage as a whole. The first paragraph identifies an area of concern: declines in amphibian populations may constitute a crisis, one that indicates humans' catastrophic effects on the environment. The passage then goes on to query, as the second paragraph states, whether claims of crisis-level extinctions as a result of human activity are valid. In making this evaluation, the passage discusses the possible causes of extinctions, biologists' prioritization of population declines over extinctions, and the fact that we lack extensive long-term data on amphibian populations. A. Correct. The passage's main purpose is to assess whether the view that humans are causing crisis-level declines in amphibian populations is valid. B. The passage takes care, particularly in the third paragraph, to distinguish between population declines and extinctions, but this is not its primary purpose. C. The passage makes clear that it is difficult to identify the real extent of the problem facing amphibian populations, much less identify its causes. D. The first paragraph notes what may seem to be a disturbing trend—the decline in amphibian populations—but the rest of the passage is concerned not with describing that trend in greater detail, but rather with determining whether it is in fact occurring. E. While the passage provides possible grounds for concluding that concern about declining amphibian populations is overblown, it concludes by suggesting that we might, because we lack data, doom species and ecosystems to extinction. Thus, the overall purpose is not to allay concern.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00582",
    question_number: 582,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "It can be inferred from the passage that the author believes which of the following to be true of the environmentalists mentioned in lines 5–6?",
      options: {
        a: "They have wrongly chosen to focus on anecdotal reports rather than on the long-term data that are currently available concerning amphibians.",
        b: "Their recommendations are flawed because their research focuses too narrowly on a single category of animal species.",
        c: "Their certainty that population declines in general are caused by environmental degradation is not warranted.",
        d: "They have drawn premature conclusions concerning a crisis in amphibian populations from recent reports of declines.",
        e: "They have overestimated the effects of chance events on trends in amphibian populations."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_010.id,
      passage_text: PASSAGE_010.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "This question asks about the author's view of the environmentalists mentioned in the first paragraph. These environmentalists have claimed, based on amphibian population declines, that the situation is a crisis and that immediate action must be taken. The author, however, states that the declines are only apparently drastic and questions whether they are real, thus suggesting that the environmentalists are drawing conclusions in the absence of a complete consideration of the situation. A. The passage indicates that anecdotal reports are insufficient, but so too are other resources. The fourth paragraph of the passage makes clear that there is not enough long-term data available on which to base conclusions about amphibian populations. B. The passage does not indicate that the environmentalists under discussion have conducted research on any animal species. C. The passage does not indicate that the environmentalists in question hold, with certainty, any particular view regarding population declines in general. D. Correct. The author argues that the recent declines may have several different causes, and that environmentalists have jumped to a conclusion about the cause of the declines as well as their significance. E. The environmentalists, in attributing population declines to intentional human activity, have more likely underestimated than overestimated the effects of chance events on amphibian populations.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00583",
    question_number: 583,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "It can be inferred from the passage that the author believes which of the following to be true of the amphibian extinctions that have recently been reported?",
      options: {
        a: "They have resulted primarily from human activities causing environmental degradation.",
        b: "They could probably have been prevented if timely action had been taken to protect the habitats of amphibian species.",
        c: "They should not come as a surprise, because amphibian populations generally have been declining for a number of years.",
        d: "They have probably been caused by a combination of chance events.",
        e: "They do not clearly constitute evidence of general environmental degradation."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_010.id,
      passage_text: PASSAGE_010.content,
    } as VRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "The author suggests throughout the passage that recently reported amphibian extinctions may have several different causes: they may be due to any number of chance events, for example, or may simply be the result of a small population that finds itself unable to continue under difficult conditions, whatever causes those conditions. A. The author states in the second paragraph that extinctions may occur without a proximate cause in human activities and does not make a commitment to any particular explanation of the amphibian extinctions. B. That chance events can cause extinctions suggests that even if habitats had been protected, extinctions still might have occurred. C. In the second paragraph, the author says that extinctions should come as no great surprise, but this option is imprecise. The amphibian populations have not generally been declining for a number of years. The author says in the fourth paragraph that amphibian populations show strong fluctuations; further, in the fourth paragraph, the author says that there is insufficient long-term data to conclude that amphibian populations have been, or are, in decline. D. The author suggests that the extinctions may have been caused by chance events, but there is not enough data to know whether or not this is probable. E. Correct. The reported extinctions could have resulted from several different causes; thus, they are not clear evidence of general environmental degradation.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00584",
    question_number: 584,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "According to the passage, each of the following is true of endangered amphibian species EXCEPT:",
      options: {
        a: "They are among the rarest kinds of amphibians.",
        b: "They generally have populations that are small in size.",
        c: "They are in constant danger of extinction.",
        d: "Those with decreasing populations are the most likely candidates for immediate extinction.",
        e: "They are in danger of extinction due to events that sometimes have nothing to do with human activities."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_010.id,
      passage_text: PASSAGE_010.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "This question asks what the passage does not say is true of endangered amphibian species. The second paragraph discusses endangered species, stating that they are always rare, almost always small, and, by definition, under constant threat of extinction, which may be caused by chance events. The possibility of their extinction, the passage states, depends only on the population size, and not whether that population is increasing or decreasing. A. The second paragraph mentions rarity as a characteristic of endangered amphibian species. B. According to the second paragraph, endangered amphibian species are generally those of small populations. C. The second paragraph states that an endangered population is under constant threat of extinction. D. Correct. The last sentence of the second paragraph states that the probability of extinction due to chance events is independent of how a population changes in size. Immediate extinction would more likely come from such events, whereas population decline is gradual, even if fairly rapid. E. Endangered species, according to the second paragraph, may become extinct due to chance events—that is, events that have nothing to do with human activities.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00585",
    question_number: 585,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "Which of the following most accurately describes the organization of the passage?",
      options: {
        a: "A question is raised, a distinction regarding it is made, and the question is answered.",
        b: "An interpretation is presented, its soundness is examined, and a warning is given.",
        c: "A situation is described, its consequences are analyzed, and a prediction is made.",
        d: "Two interpretations of a phenomenon are described, and one of them is rejected as invalid.",
        e: "Two methods for analyzing a phenomenon are compared, and further study of the phenomenon is recommended."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_010.id,
      passage_text: PASSAGE_010.content,
    } as VRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "This question asks about the organization of the passage as a whole. In the first paragraph, the author tells about a situation that has been interpreted in a particular way by environmentalists. The passage then proceeds to consider whether that interpretation is valid, and while it does not come to a definitive conclusion on that point, the final paragraph warns about the possible consequences of not taking the action recommended by the environmentalists. A. The passage does initially raise a question regarding whether the environmentalists' interpretation of events is valid, but it does not answer that question, for the appropriate long-term data are not available. B. Correct. The passage presents environmentalists' interpretation of recent news regarding amphibians, then examines the soundness of that interpretation. Finally, the author warns that postponing environmental action may have disastrous consequences. C. The first paragraph describes a situation of possibly drastic declines in amphibian populations but does not follow this description with an analysis of its consequences. D. The passage suggests that apparent declines in amphibian populations may or may not constitute a crisis, but it does not reject either idea. E. While the passage does imply, in its final paragraph, that long-term data on amphibian populations should be collected, the passage does not compare two methods for analyzing amphibian populations or population declines in those populations.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00586",
    question_number: 586,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "Which of the following best describes the function of the sentence in lines 35–38?",
      options: {
        a: "To give an example of a particular kind of study",
        b: "To cast doubt on an assertion made in the previous sentence",
        c: "To raise an objection to a view presented in the first paragraph",
        d: "To provide support for a view presented in the first paragraph",
        e: "To introduce an idea that will be countered in the following paragraph"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_010.id,
      passage_text: PASSAGE_010.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "The sentence in question discusses the way in which anecdotal reports of population decreases cannot help biologists determine whether those decreases are normal fluctuations, take populations to lower levels that are not actually worrisome, or actually threaten extinctions. This indicates that the view mentioned in the first paragraph—reports of declines indicate a catastrophic crisis—may be mistaken. A. The sentence does not address a particular kind of study; it objects to the use of anecdotal reports in place of actual study. B. The previous sentence describes the possibilities referred to in the sentence in question. The sentence does not cast doubt on any of those possibilities. C. Correct. The view that reports of amphibian population declines indicate a crisis, as presented in the first paragraph, is countered by the objection here that there are several possible causes for population declines, and anecdotal reports cannot distinguish among those possibilities. D. The first paragraph is concerned with articulating the view that amphibian population declines constitute a crisis. This sentence does not support that view; instead, it offers reason to question it. E. The sentence introduces the idea that amphibian populations have fluctuated in the past, and the following paragraph supports this idea by stating that several amphibian species that appeared almost extinct in the 1950s and 1960s have recovered. Thus, the paragraph does not counter the sentence.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00587",
    question_number: 587,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "The passage mentions which of the following as a factor that affects the role of P. ochraceus as a keystone species within different habitats?",
      options: {
        a: "The degree to which the habitat is sheltered from waves",
        b: "The degree to which other animals within a habitat prey on mussels",
        c: "The fact that mussel populations are often not dominant within some habitats occupied by P. ochraceus",
        d: "The size of the P. ochraceus population within the habitat",
        e: "The fact that there is great species diversity within some habitats occupied by P. ochraceus"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_013.id,
      passage_text: PASSAGE_013.content,
    } as VRQuestionData,
    answers: generateMCAnswers("a"),
    explanation: "This question depends on recognizing what the passage states about the factors affecting P. ochraceus's role as a keystone species, which is different in different habitats. According to the passage, P. ochraceus consumes and suppresses mussel populations in some habitats—specifically, those that are wave-exposed—making it a keystone predator in those habitats. But in wave-sheltered habitats, P. ochraceus does not play the same role in suppressing mussel populations. A. Correct. The passage clearly states that P. ochraceus's role in wave-exposed habitats differs from its role in wave-sheltered habitats. B. The passage says that the impact of P. ochraceus predation on mussels is not strong in wave-sheltered habitats, but this is not the case—at least not at all sites—because other animals are preying on the mussels; rather, at least at some sites, it is because mussels are controlled by sand burial. C. The passage does not suggest that mussel populations are dominant in any habitats occupied by P. ochraceus. D. The size of the P. ochraceus population affects the size of the mussel population within wave-exposed habitats, but the passage does not suggest that P. ochraceus's role as a keystone species depends on the size of its population within those habitats. E. The only other species the passage mentions in conjunction with P. ochraceus habitats is the mussel; the passage does not address species diversity in these habitats.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00588",
    question_number: 588,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "Which of the following hypothetical experiments most clearly exemplifies the method of identifying species' roles that the author considers problematic?",
      options: {
        a: "A population of seals in an Arctic habitat is counted in order to determine whether it is the dominant species in that ecosystem.",
        b: "A species of fish that is a keystone species in one marine ecosystem is introduced into another marine ecosystem to see whether the species will come to occupy a keystone role.",
        c: "In order to determine whether a species of monkey is a keystone species within a particular ecosystem, the monkeys are removed from that ecosystem and the ecosystem is then studied.",
        d: "Different mountain ecosystems are compared to determine how geography affects a particular species' ability to dominate its ecosystem.",
        e: "In a grassland experiencing a changing climate, patterns of species extinction are traced in order to evaluate the effect of climate changes on keystone species in that grassland."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_013.id,
      passage_text: PASSAGE_013.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "Answering this question depends on recognizing what the author says about identifying species' roles in habitats and then extending that to another situation. The author considers a particular method of studying keystone species problematic: removing a suspected keystone species from its habitat and observing what happens to the ecosystem. The author finds this problematic because interactions among species are complex. The author states explicitly that removing a species from a habitat in order to determine its keystone status is problematic. Removing the monkeys from their habitat is a clear example of this problematic practice.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00589",
    question_number: 589,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "Which of the following, if true, would most clearly support the argument about keystone status advanced in the last sentence of the passage (lines 24-31)?",
      options: {
        a: "A species of bat is primarily responsible for keeping insect populations within an ecosystem low, and the size of the insect population in turn affects bird species within that ecosystem.",
        b: "A species of iguana occupies a keystone role on certain tropical islands but does not play that role on adjacent tropical islands that are inhabited by a greater number of animal species.",
        c: "Close observation of a savannah ecosystem reveals that more species occupy keystone roles within that ecosystem than biologists had previously believed.",
        d: "As a keystone species of bee becomes more abundant, it has a larger effect on the ecosystem it inhabits.",
        e: "A species of moth that occupies a keystone role in a prairie habitat develops coloration patterns that camouflage it from potential predators."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_013.id,
      passage_text: PASSAGE_013.content,
    } as VRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "To answer this question, focus on the argument advanced in the last sentence of the passage and identify what information would support that argument. In the last sentence of the passage, the author claims that keystone status depends on context. The author then offers three contextual factors that may affect a species' keystone status: geography, community diversity (i.e., the number of species in a given habitat), and length of species interaction. Evidence supporting this argument would show that context is important to a species' keystone status. That the iguana is a keystone species in a location that has limited species diversity but not a keystone species in a location that has greater species diversity suggests that keystone status does indeed depend on context. Thus, this example supports the author's argument in the last sentence of the passage.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00590",
    question_number: 590,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "The passage suggests which of the following about the identification of a species as a keystone species?",
      options: {
        a: "Such an identification depends primarily on the species' relationship to the dominant species.",
        b: "Such an identification can best be made by removing the species from a particular ecosystem and observing changes that occur in the ecosystem.",
        c: "Such an identification is likely to be less reliable as an ecosystem becomes less diverse.",
        d: "Such an identification seems to depend on various factors within the ecosystem.",
        e: "Such an identification can best be made by observing predation behavior."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_013.id,
      passage_text: PASSAGE_013.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "Answering this question requires identifying how the passage suggests that keystone species should be identified. The passage identifies a particular way in which keystone status should not be determined: removing a species and observing what happens to the ecosystem. The passage also argues that keystone status depends strongly on context: that is, an ecosystem's characteristics, including its geography and inhabitants, determining its keystone species. If, as the passage suggests, keystone status for any given species depends on the context of the ecosystem in which it lives, then it is likely that identifying keystone species depends strongly on understanding what factors of the ecosystem contribute to creating keystone status. The passage lists such factors as geography, community diversity, and species interaction.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00591",
    question_number: 591,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "According to the passage, the anatomical evidence provided by the preserved soft bodies of conodonts led scientists to conclude that",
      options: {
        a: "conodonts had actually been invertebrate carnivores",
        b: "conodonts' teeth were adapted from protective bony scales",
        c: "conodonts were primitive vertebrate suspension feeders",
        d: "primitive vertebrates with teeth appeared earlier than armored vertebrates",
        e: "scientists' original observations concerning the phosphatic remains of conodonts were essentially correct"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_014.id,
      passage_text: PASSAGE_014.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "This question depends on understanding how a particular type of evidence—the preserved soft bodies of conodonts—supports a particular conclusion stated in the passage. The third paragraph makes this relationship explicit, explaining that certain features of conodonts show them to be more primitive than other vertebrates. Further, those features indicate that they came before ostracoderms and other armored jawless fishes. These remains support the conclusion stated in the second paragraph regarding teeth being more primitive than external armor. The third paragraph explains how conodonts' remains support the conclusion that teeth were more primitive than external armor.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00592",
    question_number: 592,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "The second paragraph in the passage serves primarily to",
      options: {
        a: "outline the significance of the 1981 discovery of conodont remains to the debate concerning the development of the vertebrate skeleton",
        b: "contrast the traditional view of the development of the vertebrate skeleton with a view derived from the 1981 discovery of conodont remains",
        c: "contrast the characteristics of the ostracoderms with the characteristics of earlier soft-bodied vertebrates",
        d: "explain the importance of the development of teeth among the earliest vertebrate predators",
        e: "present the two sides of the debate concerning the development of the vertebrate skeleton"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_014.id,
      passage_text: PASSAGE_014.content,
    } as VRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "This question depends on understanding the second paragraph in the context of the passage as a whole. The second paragraph begins by noting the traditional view of the vertebrate skeleton—that it was a defense against predators—and then goes on to explain that other paleontologists argued against this idea, claiming instead that vertebrates began as predators and that teeth were a more primary feature than external armor. According to the passage, the debate concerning the development of the vertebrate skeleton hinges on whether vertebrates began as predators, with teeth, or whether skeletal defenses such as external armor evolved first. The primary purpose of the second paragraph is to distinguish these two sides.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00593",
    question_number: 593,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "It can be inferred that on the basis of the 1981 discovery of conodont remains, paleontologists could draw which of the following conclusions?",
      options: {
        a: "The earliest vertebrates were sedentary suspension feeders.",
        b: "Ostracoderms were not the earliest vertebrates.",
        c: "Defensive armor preceded jaws among vertebrates.",
        d: "Paired eyes and adaptations for activity are definitive characteristics of vertebrates.",
        e: "Conodonts were unlikely to have been predators."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_014.id,
      passage_text: PASSAGE_014.content,
    } as VRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "What could paleontologists conclude, based on the 1981 discovery of conodont remains? That discovery, according to the passage, supported the view of certain paleontologists that the earliest vertebrates were predators with teeth—unlike the ostracoderms, which had no jaws. According to the third paragraph, the conodonts' body structures indicated that they were more primitive than the ostracoderms, so the ostracoderms must not have been the earliest vertebrates.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00594",
    question_number: 594,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "The passage implies that which of the following was a reason that the proportion of verdicts in favor of patentees began to increase in the 1830s?",
      options: {
        a: "Patent applications approved after 1836 were more likely to adhere closely to patent law.",
        b: "Patent laws enacted during the 1830s better defined patent rights.",
        c: "Judges became less prejudiced against patentees during the 1830s.",
        d: "After 1836, litigated cases became less representative of the population of patent disputes.",
        e: "The proportion of patent disputes brought to trial began to increase after 1836."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_016.id,
      passage_text: PASSAGE_016.content,
    } as VRQuestionData,
    answers: generateMCAnswers("a"),
    explanation: "The question asks which statement can be reasonably inferred, from information provided in the passage, to be a reason for the increase in proportion of verdicts favoring patentees, starting in the 1830s. The second paragraph argues that what changed in that decade was not judges' attitudes toward patent law but the types of patent cases that were litigated. It explains that a law passed in 1836 required that, for the first time in U.S. history, applications for patents had to be examined for their adherence to patent law before a patent would be issued. This information implies that patents granted after 1836 were more likely to adhere to patent law and were thus more likely to be upheld in court. The passage implies that patents granted after the 1836 law went into effect were more likely to adhere to patent law.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00595",
    question_number: 595,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "The passage implies that the scholars mentioned in line 8 would agree with which of the following criticisms of the American patent system before 1830?",
      options: {
        a: "Its definition of property rights relating to inventions was too vague to be useful.",
        b: "Its criteria for the granting of patents were not clear.",
        c: "It made it excessively difficult for inventors to receive patents.",
        d: "It led to excessive numbers of patent-infringement suits.",
        e: "It failed to encourage national economic growth."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_016.id,
      passage_text: PASSAGE_016.content,
    } as VRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "This question asks about a statement implied by the passage. The scholars mentioned in line 8 question whether U.S. patent law achieved its goal. That goal is described in the first sentence of the passage: to encourage America's economic growth. Thus, it is reasonable to conclude that the scholars would criticize the pre-1830 patent system for failing to encourage economic growth. The scholars doubt that patent law helped to achieve its goal, which was to encourage economic growth.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00596",
    question_number: 596,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "It can be inferred from the passage that the frequency with which pre-1830 cases have been cited in court decisions is an indication that",
      options: {
        a: "judicial support for patent rights was strongest in the period before 1830",
        b: "judicial support for patent rights did not increase after 1830",
        c: "courts have returned to judicial standards that prevailed before 1830",
        d: "verdicts favoring patentees in patent-infringement suits did not increase after 1830",
        e: "judicial bias against patentees persisted after 1830"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_016.id,
      passage_text: PASSAGE_016.content,
    } as VRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "The question asks what is indicated by the frequency with which pre-1830 cases have been cited in court decisions. The second paragraph rejects some scholars' claims that judges prior to the 1830s were antipatent, while judges after that time were more accepting of patent rights. The passage supports its critique by pointing out that decisions made by judges before the 1830s have been cited as precedents by later judges just as frequently as post-1830s decisions have been. This implies that later judges' attitudes toward patent rights were similar to those of pre-1830s judges. Thus, there is no reason to believe judges' attitudes toward patent rights changed at that time. Pre-1830s court decisions have been cited as frequently as later decisions, suggesting no change in judges' attitudes.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00597",
    question_number: 597,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "It can be inferred from the passage that the author and the scholars referred to in line 21 disagree about which of the following aspects of the patents defended in patent-infringement suits before 1830?",
      options: {
        a: "Whether the patents were granted for inventions that were genuinely useful",
        b: "Whether the patents were actually relevant to the growth of the United States economy",
        c: "Whether the patents were particularly likely to be annulled by judges",
        d: "Whether the patents were routinely invalidated for reasons that were arbitrary",
        e: "Whether the patents were vindicated at a significantly lower rate than patents in later suits"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_016.id,
      passage_text: PASSAGE_016.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "The question depends on recognizing differences between two explanations—one favored by the scholars mentioned in line 21, the other favored by the author—for the frequency with which patents were invalidated in U.S. courts prior to 1830. The first paragraph describes the scholars' view that judges before 1830 were antipatent and rejected patentees' claims for arbitrary reasons. The author of the passage rejects that view. As an alternative explanation, the author implies in the second paragraph that earlier patents often violated patent law; this view is supported with reference to an 1836 revision to the patent system which instituted a procedure by which patent applications were inspected to ensure adherence to patent law. The scholars claim that judges before 1830 decided against patentees for arbitrary reasons, but the passage suggests that the patents may have been invalidated because they failed to adhere to patent law.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00598",
    question_number: 598,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "The author of the passage cites which of the following as evidence challenging the argument referred to in lines 14-15?",
      options: {
        a: "The proportion of cases that were decided against patentees in the 1820s",
        b: "The total number of patent disputes that were litigated from 1794 to 1830",
        c: "The fact that later courts drew upon the legal precedents set in pre-1830 patent cases",
        d: "The fact that the proportion of judicial decisions in favor of patentees began to increase during the 1830s",
        e: "The constitutional rationale for the 1836 revision of the patent system"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_016.id,
      passage_text: PASSAGE_016.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "The question asks what evidence the author brings to bear against the argument referred to in lines 14-15. In the first paragraph, the author summarizes scholars' argument to the conclusion that judges' attitudes toward patent rights shifted in the 1830s, based on the fact that judges earlier had routinely ruled against patentees in lawsuits whereas judges after that time provided more protection for patent rights. In the second paragraph, the author challenges those scholars' attitudes shifted. The author provides evidence that judges after the 1830s cited legal precedents set in pre-1830s cases, suggesting that their views had not changed. The fact that judges after 1830 cited earlier cases as precedents is used as evidence to challenge scholars' claims that judges' attitudes shifted around 1830.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00599",
    question_number: 599,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "The author of the passage discusses Krontiris primarily to provide an example of a writer who",
      options: {
        a: "is highly critical of the writings of certain Renaissance women",
        b: "supports Kelly's view of women's status during the Renaissance",
        c: "has misinterpreted the works of certain Renaissance women",
        d: "has rejected the views of both Burckhardt and Kelly",
        e: "has studied Renaissance women in a wide variety of social and religious contexts"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_016.id,
      passage_text: PASSAGE_016.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "This question focuses on the author's reason for mentioning Krontiris's work. The passage states that Krontiris, in her discussion of six Renaissance women writers, is an example of scholars who are optimistic about women's achievements but also suggest that these women faced significant obstacles. She is a writer who, in other words, agrees with neither Kelly's negative views nor Burckhardt's positive approach. The author uses Krontiris as an example of those feminist scholars who have rejected the overgeneralized approaches of both Kelly and Burckhardt.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00600",
    question_number: 600,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "According to the passage, Krontiris's work differs from that of the scholars mentioned in line 12 in which of the following ways?",
      options: {
        a: "Krontiris's work stresses the achievements of Renaissance women rather than the obstacles to their success.",
        b: "Krontiris's work is based on a reinterpretation of the work of earlier scholars.",
        c: "Krontiris's views are at odds with those of both Kelly and Burkhardt.",
        d: "Krontiris's work focuses on the place of women in Renaissance society.",
        e: "Krontiris's views are based exclusively on the study of a privileged group of women."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_016.id,
      passage_text: PASSAGE_016.content,
    } as VRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "This question asks what the passage directly states about the difference between Krontiris's work and the feminist scholars mentioned in the first paragraph. The feminist scholars mentioned in the first paragraph explore differences among Renaissance women, particularly their social status and religion, and thus complicate Burckhardt's and Kelly's generalizations. Krontiris's work, on the other hand, focuses on Renaissance women writers, who are a distinctly privileged and small social group. The feminist scholars mentioned in the first paragraph are concerned with women of different social classes and religions, whereas Krontiris's work focuses on a limited social group.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00601",
    question_number: 601,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "According to the passage, feminist scholars cite Burckhardt's view of Renaissance women primarily for which of the following reasons?",
      options: {
        a: "Burckhardt's view forms the basis for most arguments refuting Kelly's point of view.",
        b: "Burckhardt's view has been discredited by Kelly.",
        c: "Burckhardt's view is one that many feminist scholars wish to refute.",
        d: "Burckhardt's work provides rich historical evidence of inequality between Renaissance women and men.",
        e: "Burckhardt's work includes historical research supporting the arguments of the feminist scholars."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_016.id,
      passage_text: PASSAGE_016.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "This question asks what the passage says explicitly about why feminist scholars reference Burckhardt's view of Renaissance women. The first paragraph states that Burckhardt's view is that Renaissance women enjoyed perfect equality with men, and then follows that by noting how feminist scholars have repeatedly cited this view to contrast it with extensive evidence of women's inequality during the Renaissance. Many feminist scholars wish to refute Burckhardt's view that Renaissance women and men were equal.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00602",
    question_number: 602,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "It can be inferred that both Burckhardt and Kelly have been criticized by the scholars mentioned in line 12 for which of the following?",
      options: {
        a: "Assuming that women writers of the Renaissance are representative of Renaissance women in general",
        b: "Drawing conclusions that are based on the study of an atypical group of women",
        c: "Failing to describe clearly the relationship between social status and literacy among Renaissance women",
        d: "Failing to acknowledge the role played by Renaissance women in opposing cultural stereotypes",
        e: "Failing to acknowledge the ways in which social status affected the creative activities of Renaissance women"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_016.id,
      passage_text: PASSAGE_016.content,
    } as VRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "Line 12 refers to feminist scholars who have rejected both Kelly's and Burckhardt's views of the status of Renaissance women. The next sentence states that the feminist scholars use class and religious differences among Renaissance women to argue against Kelly's and Burckhardt's generalizations, which were based on upper-class Italian women. The feminist scholars mentioned study different types of Renaissance women and so reject Kelly's and Burckhardt's conclusions that were based on a group that was not in fact typical.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00603",
    question_number: 603,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "The author of the passage suggests that Krontiris incorrectly assumes that",
      options: {
        a: "social differences among Renaissance women are less important than the fact that they were women",
        b: "literacy among Renaissance women was more prevalent than most scholars today acknowledge",
        c: "during the Renaissance, women were able to successfully oppose cultural stereotypes relating to gender",
        d: "Renaissance women did not face many difficult social obstacles relating to their gender",
        e: "in order to attain power, Renaissance women attacked basic assumptions in the ideologies that oppressed them"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_016.id,
      passage_text: PASSAGE_016.content,
    } as VRQuestionData,
    answers: generateMCAnswers("a"),
    explanation: "",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00604",
    question_number: 604,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "The last sentence in the passage serves primarily to",
      options: {
        a: "suggest that Krontiris's work is not representative of recent trends among feminist scholars",
        b: "undermine the argument that literate women of the Renaissance sought to oppose social constraints imposed on them",
        c: "show a way in which Krontiris's work illustrates a \"cautiously optimistic\" assessment of Renaissance women's achievements",
        d: "summarize Krontiris's view of the effect of literacy on the lives of upper- and middle-class Renaissance women",
        e: "illustrate the way in which Krontiris's study differs from the studies done by Burckhardt and Kelly"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_016.id,
      passage_text: PASSAGE_016.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00605",
    question_number: 605,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "The author of the passage implies that the women studied by Krontiris are unusual in which of the following ways?",
      options: {
        a: "They faced obstacles less formidable than those faced by other Renaissance women.",
        b: "They have been seen by historians as more interesting than other Renaissance women.",
        c: "They were more concerned about recording history accurately than were other Renaissance women.",
        d: "Their perceptions are more likely to be accessible to historians than are those of most other Renaissance women.",
        e: "Their concerns are likely to be of greater interest to feminist scholars than are the ideas of most other Renaissance women."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_016.id,
      passage_text: PASSAGE_016.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00606",
    question_number: 606,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "The passage implies which of the following about the five asteroids mentioned in line 12?",
      options: {
        a: "Their rotation rates are approximately the same.",
        b: "They have undergone approximately the same number of collisions.",
        c: "They are monoliths.",
        d: "They are composed of fragments that have escaped the gravity of larger asteroids.",
        e: "They were detected only recently."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_011.id,
      passage_text: PASSAGE_011.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "In line 12, five observed asteroids refers to the five asteroids whose rotation rates are exceptions to the strict limit on the rate of rotation found in all other observed asteroids. These five asteroids all have diameters smaller than 200 meters. The passage indicates that if asteroids were all monoliths—that is, single rocks—then their rotation rates would form a bell curve when graphed, but if asteroids were piles of rubble, the tail of the bell curve indicating very fast rotation rates would be missing. Among asteroids larger than 200 meters, this tail is missing, and only the five asteroids described as exceptions have rotation rates falling at the very high end of the bell curve. The second paragraph states that most small asteroids should be monolithic, and the five observed asteroids are all smaller than 200 meters in diameter.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00607",
    question_number: 607,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "The discovery of which of the following would call into question the conclusion mentioned in line 16?",
      options: {
        a: "An asteroid 100 meters in diameter rotating at a rate of once per week",
        b: "An asteroid 150 meters in diameter rotating at a rate of 20 times per hour",
        c: "An asteroid 250 meters in diameter rotating at a rate of once per week",
        d: "An asteroid 500 meters in diameter rotating at a rate of once per hour",
        e: "An asteroid 1,000 meters in diameter rotating at a rate of once every 24 hours"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_011.id,
      passage_text: PASSAGE_011.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "The conclusion that the text in line 16 points to is that asteroids with diameters greater than 200 meters are multicomponent structures or rubble piles. To call that conclusion into question, an observation would have to suggest that asteroids larger than 200 meters across are not such multicomponent structures. According to the first paragraph, rubble piles cannot be fast rotators: spinning faster than once every few hours would make them fly apart. Assuming that an asteroid composed of a pile of rubble is of a great enough density, a rotation rate greater than one revolution every few hours—that is, faster than the crucial speed—would fly apart if it were not a monolith. The conclusion states that all asteroids larger than 200 meters are multicomponent structures—that is, are not monoliths—so the discovery of a 500-meter asteroid rotating at a rate of once an hour would call into question that conclusion.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00608",
    question_number: 608,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "According to the passage, which of the following is a prediction that is based on the strength of the gravitational attraction of small asteroids?",
      options: {
        a: "Small asteroids will be few in number.",
        b: "Small asteroids will be monoliths.",
        c: "Small asteroids will collide with other asteroids very rarely.",
        d: "Most small asteroids will have very fast rotation rates.",
        e: "Almost no small asteroids will have very slow rotation rates."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_011.id,
      passage_text: PASSAGE_011.content,
    } as VRQuestionData,
    answers: generateMCAnswers("b"),
    explanation: "Regarding small asteroids, the second paragraph states that they have feeble gravity. Any fragments from impacts would escape that gravity, and thus, the passage states, the small asteroids should be monolithic. This prediction is offered in the second paragraph, based on the fact that small asteroids do not have strong gravitational attraction. Any impact fragments will easily escape the weak gravitational attraction of the small asteroids.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00609",
    question_number: 609,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "The author of the passage mentions \"escape velocity\" (see line 22) in order to help explain which of the following?",
      options: {
        a: "The tendency for asteroids to become smaller rather than larger over time",
        b: "The speed with which impact fragments reassemble when they do not escape an asteroid's gravitational attraction after a collision",
        c: "The frequency with which collisions among asteroids occur",
        d: "The rotation rates of asteroids smaller than 200 meters in diameter",
        e: "The tendency for large asteroids to persist after collisions"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_011.id,
      passage_text: PASSAGE_011.content,
    } as VRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "This question asks about the purpose of the author's use of the phrase escape velocity in the second paragraph. The author is discussing what occurs after an asteroid collision, in which a large asteroid might be blasted to bits. The bits, according to the author, will move slower than their mutual escape velocity—that is, the speed at which they would have to move to get away from each other and not reassemble, under the influence of gravity, into a rubble pile. After a collision, it is the asteroid fragments' failure to reach escape velocity that allows the fragments' gravitational pull to reassemble them into a rubble pile.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00610",
    question_number: 610,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "The author of the passage mentions calculations about tunneling time and barrier thickness in order to",
      options: {
        a: "suggest that tunneling time is unrelated to barrier thickness",
        b: "explain the evidence by which Wigner and Eisenbud discovered the phenomenon of tunneling",
        c: "describe data recently challenged by Raymond Chiao and colleagues",
        d: "question why particles engaged in quantum tunneling rarely achieve extremely high speeds",
        e: "explain the basis for Wigner and Eisenbud's hypothesis"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_012.id,
      passage_text: PASSAGE_012.content,
    } as VRQuestionData,
    answers: generateMCAnswers("e"),
    explanation: "This question asks why the author discusses calculations about tunneling time and barrier thickness. According to the passage, these calculations provided the grounds for Wigner and Eisenbud's hypothesis that tunneling particles may travel faster than light. The calculations about tunneling time and barrier thickness supported Wigner and Eisenbud's hypothesis that quantum tunneling could occur at speeds faster than that of light.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00611",
    question_number: 611,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      question_text: "The passage implies that if tunneling time reached no maximum in increasing with barrier thickness, then",
      options: {
        a: "tunneling speed would increase with barrier thickness",
        b: "tunneling speed would decline with barrier thickness",
        c: "tunneling speed would vary with barrier thickness",
        d: "tunneling speed would not be expected to increase without limit"
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_012.id,
      passage_text: PASSAGE_012.content,
    } as VRQuestionData,
    answers: generateMCAnswers("d"),
    explanation: "The passage states that because tunneling time reaches a maximum, then tunneling speed must increase as barrier thickness increases. But if tunneling time did not reach such a maximum, then speed need not increase without limit; the particle could have as low a speed in thicker barriers as in thinner ones and take longer to tunnel through a barrier. The tunneling particle could have as low a speed in thicker barriers as in thinner ones and simply take longer to make its way through a thicker barrier.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
  {
    id: "VR-GMAT-OG__-00612",
    question_number: 612,
    section: "Verbal Reasoning",
    difficulty: "hard",
    difficultyLevel: 5,
    questionData: {
      question_text: "Which of the following statements about the earliest scientific investigators of quantum tunneling can be inferred from the passage?",
      options: {
        a: "They found it difficult to increase barrier thickness continually.",
        b: "They anticipated the later results of Chiao and his colleagues.",
        c: "They did not suppose that tunneling particles could travel faster than light.",
        d: "They were unable to observe instances of successful tunneling.",
        e: "They made use of photons to study the phenomenon of tunneling."
      },
      image_url: null,
      image_options: null,
      passage_id: PASSAGE_012.id,
      passage_text: PASSAGE_012.content,
    } as VRQuestionData,
    answers: generateMCAnswers("c"),
    explanation: "This question asks about the earliest investigators of quantum tunneling. The passage notes that quantum tunneling's extreme rapidity was observed in 1932; thus, the earliest investigators of this phenomenon knew of its existence at that time. Not until 1955 did Wigner and Eisenbud hypothesize that the particles traveled faster than light. Thus, it is logical to infer that the earliest investigators did not imagine such a speed. The passage suggests that prior to 1955, investigators of quantum tunneling had not hypothesized that the particles could travel faster than the speed of light.",
    categories: ["Reading Comprehension"],
    questionSubtype: "reading-comprehension",
  },
];
