import {
  DataInsightsQuestion,
  TAQuestionData,
  generateTAAnswers,
} from "../types";

// GMAT Online Question Bank (OQBK) - Data Insights: Table Analysis
// Generated on 2026-02-23 by generate_oqbk_typescript.py
// Source: GMAT Online Question Bank screenshots (Data Insights GI - TA Custom Pool)
// DO NOT EDIT MANUALLY — re-run generate_oqbk_typescript.py to regenerate

export const dataInsightsOQBK_TA: DataInsightsQuestion[] = [
  {
    id: "DI-GMAT-OQBK-00009",
    question_number: 9,
    section: "Data Insights",
    difficulty: "easy",
    difficultyLevel: 2,
    questionData: {
      di_type: "TA",
      table_title: "",
      stimulus_text: "For each of $20$ composers, the table lists the year of birth, the year of death, and the number of performances in 2010 of works written by that composer.\n\nFor each of the following statements, select Yes if the statement accurately reflects the information in the table; otherwise select No.",
      column_headers: ["Composer", "Year of birth", "Year of death", "Number of performances"],
      table_data: [
        ["Bach", "1685", "1750", "$1{,}388$"],
        ["Beethoven", "1770", "1827", "$2{,}859$"],
        ["Brahms", "1833", "1897", "$1{,}848$"],
        ["Chopin", "1810", "1849", "$748$"],
        ["Dvořák", "1841", "1904", "$1{,}071$"],
        ["Handel", "1685", "1759", "$757$"],
        ["Haydn", "1732", "1809", "$989$"],
        ["Mendelssohn", "1809", "1847", "$865$"],
        ["Mozart", "1756", "1791", "$3{,}035$"],
        ["Prokofiev", "1891", "1953", "$931$"],
        ["Puccini", "1858", "1924", "$723$"],
        ["Rachmaninov", "1873", "1943", "$673$"],
        ["Ravel", "1875", "1937", "$864$"],
        ["Schubert", "1797", "1828", "$1{,}023$"],
        ["Schumann", "1810", "1856", "$1{,}460$"],
        ["Shostakovich", "1906", "1975", "$779$"],
        ["Strauss", "1864", "1949", "$720$"],
        ["Stravinsky", "1882", "1971", "$849$"],
        ["Tchaikovsky", "1840", "1893", "$2{,}295$"],
        ["Verdi", "1813", "1901", "$845$"],
        ["Total", "----", "---", "$24{,}722$"],
      ],
      statements: [
        { text: "Composers born in the 1700s accounted for less than a third of the total performances.", is_true: true },
        { text: "Music by composers ranked first, second, and third, in terms of number of performances, together accounted for more than half of the total number of performances.", is_true: false },
        { text: "The mean number of performances per composer exceeded the median by more than $300$ performances.", is_true: true },
      ],
      correct_answer: {
        stmt0: "col1",
        stmt1: "col2",
        stmt2: "col1"
      },
      answer_col1_title: "Yes",
      answer_col2_title: "No",
      statement_column_title: "",
      explanation: "A: Infer\n\nSorting the table by \"Year of birth,\" we find four composers who were born in the 1700s. The total number of performances for these composers in 2010 was $989 + 3{,}035 + 2{,}859 + 1{,}023 = 7{,}906$, which is somewhat fewer than $8{,}000$. Note that the total for all of the performances in 2010 was $24{,}722$. Because $3 \\times 8{,}000 = 24{,}000 < 24{,}722$, we see that the number of performances for the composers born in the 1700s, $7{,}906$, is less than one-third of the total number of performances.\n\nThe correct answer is Yes.\n\nB. Infer\n\nSorting the table by the number of performances, we see that the composers ranked first, second, and third, in terms of number of performances, together accounted for $3{,}035 + 2{,}859 + 2{,}295$ of the performances. This is fewer than $12{,}000$, which in turn is less than half of $24{,}722$, the total number of performances.\n\nThe correct answer is No.\n\nC. Infer\n\nSorting the table by the number of performances, we find that the median number of performances was $\\frac{931+865}{2} = 898$. Given that the total number of performances for all of the $20$ composers was $24{,}722$, we find that the mean number of performances per composer, rounded to the nearest unit, was $1{,}236$. This exceeds the median, $898$, by $338$.\n\nThe correct answer is Yes.",
    } as TAQuestionData,
    answers: generateTAAnswers({
      stmt0: "col1",
      stmt1: "col2",
      stmt2: "col1"
    }),
    categories: ["Table Analysis"],
  },
  {
    id: "DI-GMAT-OQBK-00010",
    question_number: 10,
    section: "Data Insights",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      di_type: "TA",
      table_title: "",
      stimulus_text: "The table summarizes information in several categories about the $9$ stores in a small grocery chain. The table also includes chain-wide averages where appropriate.\n\nFor each of the following statements, select True if the statement can be verified to be true based on the information provided. Otherwise, select False.",
      column_headers: ["Store", "Self-check express lanes", "Self-check unlimited lanes", "Pharmacy", "Fuel", "Restaurant", "Average customer age"],
      table_data: [
        ["A", "8", "4", "yes", "no", "no", "34.50"],
        ["B", "8", "6", "no", "no", "no", "28.40"],
        ["C", "6", "4", "yes", "no", "yes", "32.00"],
        ["D", "8", "0", "yes", "no", "no", "50.50"],
        ["E", "12", "4", "yes", "yes", "no", "42.50"],
        ["F", "8", "6", "no", "no", "yes", "34.60"],
        ["G", "8", "0", "no", "yes", "no", "38.80"],
        ["H", "4", "8", "yes", "no", "yes", "29.90"],
        ["I", "0", "0", "yes", "yes", "yes", "56.70"],
        ["averages", "6.89", "3.56", "-", "-", "-", "38.66"],
      ],
      statements: [
        { text: "In each store whose average customer age falls between $34$ and $36$, the number of self-check express lanes is above average.", is_true: true },
        { text: "There is a negative correlation between the number of self-check unlimited lanes and the average customer age.", is_true: true },
        { text: "Stores in this table that have fewer self-check express lanes than the chain-wide average are less likely to have restaurants than stores that have more self-check express lanes than the chain-wide average.", is_true: false },
      ],
      correct_answer: {
        stmt0: "col1",
        stmt1: "col1",
        stmt2: "col2"
      },
      answer_col1_title: "True",
      answer_col2_title: "False",
      statement_column_title: "Statement",
      explanation: "",
    } as TAQuestionData,
    answers: generateTAAnswers({
      stmt0: "col1",
      stmt1: "col1",
      stmt2: "col2"
    }),
    categories: ["Table Analysis"],
  },
  {
    id: "DI-GMAT-OQBK-00011",
    question_number: 11,
    section: "Data Insights",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      di_type: "TA",
      table_title: "Women Enrolled, as a Percent of Total Enrollment",
      stimulus_text: "The table lists the women enrolled as a percent of the total enrollment for each of the $3$ universities - University X, University Y, and University Z - in Province A for the fall term of several consecutive years. For the fall term of each of these years, the table also lists the women enrolled at the $3$ universities combined as a percent of the total combined enrollment at the $3$ universities.",
      column_headers: ["Fall", "University X", "University Y", "University Z", "Province A"],
      table_data: [
        ["2000", "52.8", "44.2", "58.5", "50.6"],
        ["2001", "53.1", "44.1", "58.9", "50.7"],
        ["2002", "53.6", "44.0", "55.8", "50.8"],
        ["2003", "53.3", "43.6", "58.6", "50.5"],
        ["2004", "53.0", "43.9", "58.1", "50.5"],
        ["2005", "52.5", "43.7", "58.3", "50.2"],
        ["2006", "52.2", "43.8", "58.1", "50.1"],
        ["2007", "52.0", "43.2", "57.8", "49.7"],
        ["2008", "51.4", "43.8", "58.3", "49.7"],
      ],
      statements: [
        { text: "Of the $3$ universities, University Y had the smallest total fall enrollment in each of the years 2000 through 2008.", is_true: false },
        { text: "In 2008, fewer women were enrolled in college in Province A than in 2000.", is_true: false },
        { text: "Each of the $3$ universities experienced at least one decline from one fall to the next in the number of women enrolled as a percent of the total enrollment.", is_true: true },
      ],
      correct_answer: {
        stmt0: "col2",
        stmt1: "col2",
        stmt2: "col1"
      },
      answer_col1_title: "T",
      answer_col2_title: "F",
      statement_column_title: "Statement",
      explanation: "",
    } as TAQuestionData,
    answers: generateTAAnswers({
      stmt0: "col2",
      stmt1: "col2",
      stmt2: "col1"
    }),
    categories: ["Table Analysis"],
  },
  {
    id: "DI-GMAT-OQBK-00012",
    question_number: 12,
    section: "Data Insights",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      di_type: "TA",
      table_title: "",
      stimulus_text: "The table above gives information for 2008 on total passengers (total passengers enplaned and deplaned with passengers in transit counted once) and total movements (landing and takeoff of an aircraft) for $21$ airports throughout the world. The $21$ airports were chosen for inclusion in the table because, in 2008, each was among the busiest $30$ airports in the world in terms of both total passengers and total movements. In addition to the numbers of total passengers and total movements for each airport, the table also gives the percent of increase and decrease over the numbers for 2007 and the rank of the airport for total passengers and total movements.\n\nConsider each of the following statements about these airports. For each statement indicate whether the statement is true or false, based on the information provided in the table.",
      column_headers: ["City", "Country", "Code", "Number", "% change", "Rank", "Number", "% change", "Rank"],
      table_data: [
        ["Amsterdam", "NLD", "AMS", "47,430,019", "-0.8", "14", "446,592", "-1.7", "17"],
        ["Atlanta", "USA", "ATL", "90,039,280", "0.7", "1", "978,824", "-1.6", "1"],
        ["Beijing", "CHN", "PEK", "55,937,289", "4.4", "8", "431,670", "8.0", "21"],
        ["Charlotte", "USA", "CLT", "34,739,020", "4.7", "26", "536,253", "2.6", "9"],
        ["Chicago", "USA", "ORD", "69,353,876", "-9.0", "2", "881,566", "-4.9", "2"],
        ["Dallas/Ft Worth", "USA", "DFW", "57,093,187", "-4.5", "7", "656,310", "-4.3", "3"],
        ["Denver", "USA", "DEN", "51,245,334", "2.8", "10", "619,503", "0.9", "5"],
        ["Detroit", "USA", "DTW", "35,135,828", "-2.4", "24", "462,520", "-1.0", "15"],
        ["Frankfurt", "DEU", "FRA", "53,467,450", "-1.3", "9", "485,783", "1.4", "12"],
        ["Houston", "USA", "IAH", "41,709,389", "-3.0", "16", "576,062", "-4.6", "7"],
        ["Las Vegas", "USA", "LAS", "43,208,724", "-8.0", "15", "578,949", "-5.0", "6"],
        ["London", "GBR", "LHR", "67,056,379", "-1.5", "3", "478,518", "-0.6", "13"],
        ["Los Angeles", "USA", "LAX", "59,497,539", "-4.7", "6", "622,506", "-8.6", "4"],
        ["Madrid", "ESP", "MAD", "50,824,435", "-2.4", "11", "469,740", "-2.6", "14"],
        ["Miami", "USA", "MIA", "34,063,531", "1.0", "29", "371,519", "-3.8", "29"],
        ["Minneapolis", "USA", "MSP", "34,056,443", "-3.0", "30", "450,044", "-0.7", "16"],
        ["Munich", "DEU", "MUC", "34,530,593", "1.7", "27", "432,296", "0.1", "20"],
        ["Newark", "USA", "EWR", "35,360,848", "-2.8", "23", "434,428", "-0.4", "19"],
        ["Paris", "FRA", "CDG", "60,874,682", "1.6", "5", "559,816", "1.3", "8"],
        ["Phoenix", "USA", "PHX", "39,891,193", "-5.4", "17", "502,499", "-6.8", "10"],
        ["San Francisco", "USA", "SFO", "37,234,592", "4.7", "21", "387,710", "2.2", "24"],
      ],
      statements: [
        { text: "The airport experiencing the greatest percent decrease in total passengers from 2007 to 2008 also experienced the greatest decrease in the percent of movements.", is_true: false },
        { text: "The airport with the median rank based on total number of passengers is the same as the airport with the median rank based on total number of movements.", is_true: false },
        { text: "Exactly $50\\%$ of the airports that experienced an increase in both total number of passengers and in total number of movements are located in the United States (USA).", is_true: true },
      ],
      correct_answer: {
        stmt0: "col2",
        stmt1: "col2",
        stmt2: "col1"
      },
      answer_col1_title: "True",
      answer_col2_title: "False",
      statement_column_title: "",
      explanation: "A. Infer\n\nPercent decreases correspond to negative percent changes, for which lesser values correspond to greater percent decreases. We may thus sort the table on the column for percent change in passengers and note that the Chicago airport had the greatest percent decrease in number of passengers from 2007 to 2008. However, sorting the table on percent change in number of movements, we find that a different airport, in Los Angeles, had the greatest percent decrease in number of movements.\n\nThe correct answer is False.\n\nB. Infer\n\nSorting the table on number of passengers and then identifying the middle row - both 11th from the top and 11th from the bottom - we find that the Amsterdam airport had the median number of passengers. However, sorting the table on the number of movements and again identifying the middle row, we find that the Frankfurt airport had the median number of movements. The median rank based on total number of passengers is therefore different from the median rank based on total number of movements.\n\nThe correct answer is False.\n\nC. Infer\n\nNote that the airports that experienced an increase in both total number of passengers and in total number of movements must be the airports for which both of the percent changes are positive. With the table sorted according to percent change in number of passengers, we see that the airports that experienced an increase in both total number of passengers and in total number of movements are the $6$ airports listed in the bottom $6$ rows. Exactly $3$ of these rows, $50\\%$ of the $6$, have USA as the indicated country.\n\nThe correct answer is True.",
    } as TAQuestionData,
    answers: generateTAAnswers({
      stmt0: "col2",
      stmt1: "col2",
      stmt2: "col1"
    }),
    categories: ["Table Analysis"],
  },
  {
    id: "DI-GMAT-OQBK-00013",
    question_number: 13,
    section: "Data Insights",
    difficulty: "medium",
    difficultyLevel: 3,
    questionData: {
      di_type: "TA",
      table_title: "",
      stimulus_text: "The table lists all the employees of the Metro Corporation's human resources department. Each employee's immediate supervisor is identified by the supervisor's employee ID number displayed in the last column on the right of the table. If one employee, say A, supervises another, say B, then A also supervises every employee supervised by B. Note that the hire date is given in the format month/day/year.\n\nFor each of the following, select Yes if it identifies an employee who, within the human resources department, supervises no one and who has at least $5$ supervisors within the human resources department above her or him. Otherwise, select No.",
      column_headers: ["Employee ID", "First name", "Surname", "Hire date", "Supervisor's employee ID"],
      table_data: [
        ["1", "Sally", "Lee", "4/12/2002", "6"],
        ["2", "Lauren", "Schickler", "3/16/2007", "10"],
        ["3", "Jonathan", "Ogura", "10/8/1998", "1"],
        ["4", "Shana", "Serpaio", "11/23/2000", "9"],
        ["5", "Michele", "Dockett", "5/11/2002", "11"],
        ["6", "Ben", "Rivera", "9/15/2003", "14"],
        ["7", "Lee", "Patel", "8/7/2010", "3"],
        ["8", "Eli", "O'Neill", "6/17/2009", "11"],
        ["9", "Ondrea", "Ribah", "3/12/1992", "1"],
        ["10", "Ben", "Rubenstein", "12/12/2005", "6"],
        ["11", "Jonica", "Diaz", "1/30/2004", "4"],
      ],
      statements: [
        { text: "O'Neill", is_true: true },
        { text: "Patel", is_true: false },
        { text: "Schickler", is_true: false },
      ],
      correct_answer: {
        stmt0: "col1",
        stmt1: "col2",
        stmt2: "col2"
      },
      answer_col1_title: "Yes",
      answer_col2_title: "No",
      statement_column_title: "",
      explanation: "",
    } as TAQuestionData,
    answers: generateTAAnswers({
      stmt0: "col1",
      stmt1: "col2",
      stmt2: "col2"
    }),
    categories: ["Table Analysis"],
  },
  {
    id: "DI-GMAT-OQBK-00014",
    question_number: 14,
    section: "Data Insights",
    difficulty: "hard",
    difficultyLevel: 4,
    questionData: {
      di_type: "TA",
      table_title: "Number of Kilometers Between Clients",
      stimulus_text: "Jorge travels to meet once daily with exactly six clients, Clients A through F. When scheduling these meetings, Jorge schedules the most urgent meeting to be the first of the day and then schedules each subsequent meeting according to which client is the least distance from the meeting immediately prior to it. The table shows the distances between Jorge's clients.\n\nOn Tuesday, Jorge's most urgent meeting will be with Client E. For each of the following pairs of clients, select Yes if Jorge will schedule meetings with the given clients in the given order. Otherwise, select No.",
      column_headers: ["Client", "A", "B", "C", "D", "E", "F"],
      table_data: [
        ["A", "0", "7", "3", "4", "2", "1"],
        ["B", "7", "0", "2", "15", "17", "4"],
        ["C", "3", "2", "0", "3", "18", "6"],
        ["D", "4", "15", "3", "0", "12", "7"],
        ["E", "2", "17", "18", "12", "0", "9"],
        ["F", "1", "4", "6", "7", "9", "0"],
      ],
      statements: [
        { text: "Client B then Client C", is_true: true },
        { text: "Client C then Client D", is_true: true },
        { text: "Client D then Client A", is_true: false },
      ],
      correct_answer: {
        stmt0: "col1",
        stmt1: "col1",
        stmt2: "col2"
      },
      answer_col1_title: "Yes",
      answer_col2_title: "No",
      statement_column_title: "",
      explanation: "",
    } as TAQuestionData,
    answers: generateTAAnswers({
      stmt0: "col1",
      stmt1: "col1",
      stmt2: "col2"
    }),
    categories: ["Table Analysis"],
  },
  {
    id: "DI-GMAT-OQBK-00015",
    question_number: 15,
    section: "Data Insights",
    difficulty: "easy",
    difficultyLevel: 2,
    questionData: {
      di_type: "TA",
      table_title: "",
      stimulus_text: "Ten people participated in the first round of a competition, after which their scores were analyzed to determine which people would compete in the second round. The table shows the participants' first-round scores, the difference between each participant's score and the average (arithmetic mean) score of all participants, and the square of that difference.\n\nBefore the second round of competition, one or more of the listed participants were disqualified. A new mean and new standard deviation will be calculated from only those players who were not disqualified.\n\nFor each of the following statements, select True if the statement is true based on the information provided. Otherwise, select False.",
      column_headers: ["Participant Name", "Score", "Difference from Mean", "Square of Difference from Mean"],
      table_data: [
        ["Arceneaux", "$56$", "$-9$", "$81$"],
        ["Cabrera", "$89$", "$24$", "$576$"],
        ["Costantino", "$34$", "$-31$", "$961$"],
        ["Fournier", "$24$", "$-41$", "$1{,}681$"],
        ["Hough", "$109$", "$44$", "$1{,}936$"],
        ["Keffala", "$56$", "$-9$", "$81$"],
        ["Lasek", "$120$", "$55$", "$3{,}025$"],
        ["Sauer", "$6$", "$-59$", "$3{,}481$"],
        ["Tsakiris", "$78$", "$13$", "$169$"],
        ["Willems", "$78$", "$13$", "$169$"],
      ],
      statements: [
        { text: "The disqualification of Sauer would decrease the standard deviation more than any other single disqualification.", is_true: true },
        { text: "The disqualification of Lasek would decrease the standard deviation more than any other single disqualification.", is_true: false },
        { text: "If Fournier and Sauer were both disqualified and no other changes were made, the standard deviation would decrease.", is_true: true },
      ],
      correct_answer: {
        stmt0: "col1",
        stmt1: "col2",
        stmt2: "col1"
      },
      answer_col1_title: "True",
      answer_col2_title: "False",
      statement_column_title: "",
      explanation: "",
    } as TAQuestionData,
    answers: generateTAAnswers({
      stmt0: "col1",
      stmt1: "col2",
      stmt2: "col1"
    }),
    categories: ["Table Analysis"],
  },
];
